### ISSUE TITLE
Param parsing when commas are involved

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1000]
## Describe the bug
String parameters including `,` characters seem to break the parser.

## To Reproduce
1. Run `porter install --param msg="testing 1, 2, 3"` (on any bundle... `msg` doesn't need to even be a valid param; it will fail before validation)
2. See error:
```
Error: invalid parameter ( 2), must be in name=value format`
````

Other special characters (`.`, `!`, etc.)  in the string parse fine:

```
 $ porter install --param msg="testing 1! 2! 3!"
installing whalesay...
...
 $ porter instance show -o json | jq -r '.parameters'
{
  "msg": "testing 1! 2! 3!",
  "porter-debug": false
}
```

## Expected behavior
A supplied string parameter containing `,` characters should parse fine.
## Porter Command and Output
```
 $ porter install --param msg="testing 1, 2, 3"
Error: invalid parameter ( 2), must be in name=value format
```

## Version
Copy the output of `porter version` below

```
 $ porter version
porter v0.26.0-beta.1-19-g7c6eb425 (7c6eb425)
```

**Comment by ei09010** [comment]
Hi, I wouldn't mind fixing this bug if no one else is doing it.

**Comment by carolynvs** [comment]
@ei09010 That would be great, thanks! The PR should target the main branch.

**Comment by carolynvs** [comment]
I think this is a bug in cobra. Let's confirm and submit a patch and use our fork until it's merged.

https://github.com/spf13/cobra/issues/661#issuecomment-902406803

**Comment by sleepypioneer** [comment]
We have inadvertently added the fix for this in this PR https://github.com/getporter/porter/pull/1931 (FYI @Simpcyclassy) I hope this has not caused any inconvenience to @ei09010

**Comment by carolynvs** [comment]
No that's fine! 👍
