### ISSUE TITLE
Store sensitive data in a secret store, not Porter's database

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1027]
Claims store sensitive data (parameters) and should not be stored in the database. We should come up with a way to store sensitive data from claims and other tables in the user's secret store, then when we retrieve the data, look up the sensitive values if needed to get a full document.

For some calls, maybe we don't need the data, we are just listing claims, but others like retrieving outputs and showing the values, will need to get the real values from the secret store.

**Comment by carolynvs** [comment]
We can also just encrypt the sensitive bits
claim:
name: foo
parameters: ENCRYPTED # key in porter config

**Comment by VinozzZ** [comment]
The current plan is to allow users to specify a destination for porter output through the same secrete plugin they use for resolving secrete values that needed to run bundle.
It would look something like this
`
default-secrets = "mysecrets"
   
[[secrets]]
name = "mysecrets"
plugin = "azure.keyvault"
   
[secrets.config]
input-vault = "myinputvault"
output-vault = "myoutputvault"
`

After checking the limitations on Azure key vault and Hashicorp vault, it looks like the upper limit for number of keys stored in a vault is only affected by the underlying storage space. However, Hashicorp does have a[ per object size limit](https://www.vaultproject.io/docs/internals/limits#storage-related-limits). Therefore, I plan to store each installation output separately using installation id or run id.

**Comment by carolynvs** [comment]
This sounds like a good plan, looking forward to your PR! 🚀

**Comment by VinozzZ** [comment]
I will start work on the Quickstart document

**Comment by VinozzZ** [comment]
Started on the Task document

**Comment by VinozzZ** [comment]
After looking at the example output from azure keyvault, we probably should add an dash in the secret key to make it more friendly to users to see

**Comment by carolynvs** [comment]
Is this okay to close?
