### ISSUE TITLE
Documentation issue with good first issues on CONTRIBUTING

### ISSUE THREAD

**Issue by iennae** [getporter/porter#1031]
## Bug with Documentation

On the [CONTRIBUTING](https://porter.sh/src/CONTRIBUTING.md) doc, the link to good first issues takes you to the project board which has a single first issue. This may not be as helpful to new people to the project. 

Additionally, 
- [x] A great first issue "What is Porter" is missing from the project board. (ETA, we've added this issue to the project board)
- [ ] Maybe remove the link to the project board from the "Find an Issue" section, or modify where it clicks to, or add a "See good examples below" example. 

Collaborating on bug report with @jacciboggs, @cjthune, and @alynch-code

## Expected behavior
1. Remove the links to good first issue and help wanted from the first paragraph under "find an issue"
1. Link to them instead later underneath the bullet points that explain what they mean. For example, let's say "Go to our project board and filter the issues by good first issue (link) or help wanted (link) to see available issues".
1. Add a sentence after we mention the project board in the first paragraph that explains that our project board contains issues from all of the Porter repositories so that it's easier to find issues without looking in each repo, e.g. "We use an organization level project board so we can see all issues associated with the project at once"

**Comment by nhcarrigan** [comment]
Coming from the stream - could I poke at this? 😁

**Comment by iennae** [comment]
@nhcarrigan Please do :D
