### ISSUE TITLE
Document how to work with bundles as an end-user

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1045]
We have pieces of documentation on various concepts, such as 
* porter explain
* [credentials](https://porter.sh/credentials/)
* porter install
* credentials generate

But for someone new to bundles, especially someone who didn't create a bundle, we really need another page that walks through the series of commands that they should be using to work with a bundle and go from explain to install. Understanding when to create credentials, how to pass parameters, etc. Something that ties together the entire workflow.

I'm not sure if this should update the existing quickstart, maybe it's too advanced and should be a next step after the quick start?

**Comment by vdice** [comment]
Agreed, this is a natural/needed next piece of documentation, it seems.  I'd suggest a next step/separate document with an overview of how to work w/ bundles as an end-user, ideally with its own top-level link added to the main sidebar on porter.sh.  (Would not preclude additions to the existing quickstart, if that made sense as well.)

**Comment by carolynvs** [comment]
Here's a great example of a doc that introduces concepts incrementally

https://kitchen.ci/docs/getting-started/introduction/

**Comment by carolynvs** [comment]
Yay we finally have all of this!
