### ISSUE TITLE
Use debian-slim

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1049]
I'm wondering if we can shave off a few dozen MB from our bundles by using debian-slim instead of debian for our base invocation image? It removes things from the base image that aren't needed by containers.

> These tags are an experiment in providing a slimmer base (removing some extra files that are normally not necessary within containers, such as man pages and documentation), and are definitely subject to change.

> See the debuerreotype-slimify script (debuerreotype linked above) for more details about what gets removed during the "slimification" process.

https://hub.docker.com/_/debian

TODO:
* Edit our template dockerfiles to use debian:stretch-slim. They are located in https://github.com/getporter/porter/tree/main/pkg/templates
* Look through our repository for documentation or tests that references the old `debian:stretch` and update them to use the slim image instead.

**Comment by chris-crone** [comment]
Anecdotal information: Using `debian:buster-slim` with the Helm and Terraform mixins, I haven't run into any issues.

My `Dockerfile.tmpl`:
```dockerfile
```

**Comment by wisdommatt** [comment]
@carolynvs i would like to work on this
