### ISSUE TITLE
porter build failed to add local helm chart repo

### ISSUE THREAD

**Issue by sajuptpm** [getporter/porter#1051]
## Describe the bug
I am using local helm chart registry. "$porter build" command failed to execute "$helm repo add"
Does porter has option to pass /etc/hosts entry or --add-host to "docker build" command ?
Fix: we need to add an entry in /etc/hosts file while building docker image, How we can do that in porter ?

## To Reproduce

Configure local helm repository in porter.yaml
```
$cat porter.yaml
mixins:
- helm:
    clientVersion: v2.15.2
    repositories:
      myhrepo:
        url: "https://myharbor.com" <--- local helm chart registry
        cafile: "/certs/ca.crt"
        certfile: "/certs/myharbor.com.crt"
        keyfile: "/certs/myharbor.com.key"
        username: "admin"
        password: "12345"
```
Then run $porter build --debug

## Expected behavior
no error

## Porter Command and Output
```
$ porter build --debug

Step 27/32 : RUN helm repo add myhrepo https://myharbor.com --cert-file /certs/myharbor.com.crt --key-file /certs/myharbor.com.key --ca-file /certs/ca.crt --username admin --password 12345
 ---> Running in e5c3ab3ade3e
Error: Looks like "https://myharbor.com" is not a valid chart repository or cannot be reached: Get https://myharbor.com/index.yaml: dial tcp: lookup myharbor.com on 10.10.10.10:53: no such host
Error: unable to build CNAB invocation image: failed to stream docker build output: The command '/bin/sh -c helm repo add myhrepo https://myharbor.com --cert-file /certs/myharbor.com.crt --key-file /certs/myharbor.com.key --ca-file /certs/ca.crt --username admin --password 12345' returned a non-zero code: 1
```

**Comment by vdice** [comment]
This is an interesting use case.  Delaying implementation discussion, the first question I have is around the practicality of bundles that rely on artifacts from a local host during runtime.  This implies the bundle is only really meant to be run locally, as it is tightly-coupled to the aforementioned host.

This is of course still a valid use case, but not one we've been prioritizing.  Rather, we've been emphasizing distributed/team-wide collaboration on a bundle and/or distributing bundles for other users to consume -- both of which necessitate that any artifacts that the bundle attempts to fetch during runtime are publicly available (or at least available within the intended consumer's/collaborator's domain.)

Can you expand on the use case(s) for this feature request?  Have alternatives been considered, such as serving artifacts from a publicly available url (though, of course, it could still be protected via auth) or copying in artifacts into the bundle's working directory at build-time such that fetching at runtime can be avoided?

**Comment by MChorfa** [comment]
Hi @sajuptpm You need to install the CA into your invocation image, thus the certs that were sent by your registry would be trusted. And then you can add the repo, therefore costume the charts. hope it helps
