### ISSUE TITLE
Howto: Porter credentials and Docker secrets

### ISSUE THREAD

**Issue by decentral1se** [getporter/porter#1057]
**Is your feature request related to a problem? Please describe.**
It is unclear to me how to navigate the usage of docker secrets with porter credentials. I am using the `exec` mixin and `--allow-docker-host-access` for the purposes of deploying on Docker swarm.

Looking at https://docs.docker.com/compose/compose-file/#secrets, I case see that I should do something like:

```yaml
# docker-compose.yml
---
services:
  mything:
    secrets:
      - mysecret

secrets:
  mysecret:
    external: true
```

But how do I get `porter` to run `docker secret create` for me when I use a credentials defnition in my `porter.yaml` file and pass values in from the `porter` side? I can quite easily pass environment variables to my `docker-compose.yml` file:

```yaml
# docker-compose.yml
---
services:
  mything:
    environment:
      - MYSECRET=${MYSECRET}
```

However, the advantage of using Docker secrets proper is that they are immutable and therefore if I can have guarantees that I can make rollbacks successfully when running further updates.

I guess this requires a docker mixin proper but even if that existed now I am not sure how this interaction could work.

**Describe the solution you'd like**
It is clear how to use Docker secrets with Porter credentials.

**Describe alternatives you've considered**
Using the `environment` stanza to pass in credentials via the environment.

**Additional context**
Porter is pretty rad :partying_face:

**Comment by vdice** [comment]
Hi @decentral1se, thanks for this issue.  I encountered some new learnings when investigating this!

To start, as you're probably aware by now, [Porter credentials](https://porter.sh/wiring/#credentials) can have their destination be an environment variable or a filepath within the invocation image. 

As for interactions with Docker Compose, a couple things threw me for a loop.  When reading up on the [compose-file secrets doc](https://docs.docker.com/compose/compose-file/#secrets) (as kindly linked above), I see that there are two options for the secret source: a file or a reference to an external secret.

For the former, it took me a bit to realize that the file path as declared in the compose yaml should be relative to the Docker daemon.  In this case, our current [examples](https://github.com/deislabs/porter-docker-compose/tree/master/examples/compose) use a precedent of accessing the _host_ Docker daemon when running bundles that use the [docker-compose](https://github.com/deislabs/porter-docker-compose) mixin.  The file for the Docker secret should then exist on the host system and not within the invocation image.  So, there's no need to pass the secret in via a [Porter credential](https://porter.sh/wiring/#credentials) to be placed in a file within the invocation image, as that file would not be used.

As the bundle requires a file to be present on the host, the utility of the bundle is severely limited (can't be executed on a different host without the same file(s) present, etc.)

(In the near future, I'd like to create a bundle that actually runs the docker daemon within the invocation image, at which point it _would_ use a file existing within that image and everything could be self-contained.  I'll update once I get that working...)

For the latter, I did use a Porter credential to setup a secret in the form of an environment variable in the invocation image (as `MY_SECRET`).  I used an `exec` step to [create the docker secret](https://github.com/vdice/porter-bundles/blob/compose-secrets/compose/create_secret.sh) successfully.  Alas, I encountered the following error when attempting to reference this external secret in the compose file:
```
Service "web" uses secret "my_created_secret" which is external. External secrets are not available to containers created by docker-compose.
```
Here I'll admit my Docker Compose/Swarm knowledge is not extensive, so there may be ways to get this working.

I was using the following [example bundle](https://github.com/vdice/porter-bundles/tree/compose-secrets/compose) for testing; see also https://github.com/vdice/porter-bundles/blob/compose-secrets/compose/secret_creation.md.

I'll keep exploring.  Perhaps we can compare notes and work towards documenting a How-To.  Thanks!

**Comment by vdice** [comment]
> (In the near future, I'd like to create a bundle that actually runs the docker daemon within the invocation image, at which point it would use a file existing within that image and everything could be self-contained. I'll update once I get that working...)

A bit of a tangent here, but I thought it worth updating.  I started a new bundle around this effort but quickly realized its usefulness would be limited. 
 Since the Docker daemon (and secrets, containers, etc.) would be entirely isolated within the invocation image, it all goes away after the invocation image exists from a given action.  Since the current pattern in Porter (and CNAB in general) is that each action (install, upgrade, uninstall) is intended to complete (and the invocation image exit), we don't currently have a way to persist container state between actions and/or re-use a running container.  So, although we might be able to get a completely self-contained compose cluster running on `install`, it'd just be torn down after the action finishes.

**Comment by decentral1se** [comment]
> it'd just be torn down after the action finishes.

Most people use docker within the invocation image to deploy containers to an external docker daemon which means when the invocation image command finishes, the resulting containers live on on the host.

**Comment by decentral1se** [comment]
> I'll keep exploring. Perhaps we can compare notes and work towards documenting a How-To. Thanks!

Thank you! I've been working from https://git.autonomic.zone/decentral1se/gitea-cnab, maybe it is useful to see it. Since I need to interact with the swarm quite directly with secret generation and such and am quite familiar with the Ansible modules, I am using Ansible in the bundle command steps. 

As you have already seen, some parts are a bit awkward. However, I've managed to arrange it such that you can `porter credential generate`, create a `parameters.txt` and then run `porter install --tag decentral1se/gitea:0.1.0 --allow-docker-host-access --param-file params.txt --cred gitea` and Gitea comes up against a local docker daemon which has been `docker swarm init`'d.

The current issue I'm facing is that in order to `upgrade`, I need to version my secret and configs because they are immutable in Docker swarm. So, I am currently playing around with checksumming those, which you can see in the repo posted above.

I am also hoping once I get through all this experimenting I can come out of it and see a simple pattern and potentially bundle that up into a mixin. I am unsure. However, the idea of `porter` as a uniform interface and "you don't need to know what goes on inside the bundle" has already gained some traction in my organisation for deployments. I'll keep running with that :)

> we don't currently have a way to persist container state between actions

That is indeed a bit problematic since I can't have my `install` command generate anything on the fly to be injected into the deployed containers. Everything must come from the user as a credential/parameter. Which is OK but it means users have to care about generating internal secrets which could just be generated on the fly and otherwise hidden inside the bundle.

**Comment by carolynvs** [comment]
Closing the issue though because we do not have any plans for docker secrets in our roadmap.
