### ISSUE TITLE
Refactor: Create reusable table printing function (Cred, Param Set, other?)

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1085]
Can we make a reusable function to initialize this table here any in any other places that use this?

_Originally posted by @carolynvs in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDI5ODM0MzEy/pull_request_reviews/more_threads_

**Comment by carolynvs** [comment]
We are in a lot better place after I refactored the table printing to wrap properly.
