### ISSUE TITLE
Improve installation of mixins from the search results

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1109]
When I do a `porter mixin search NAME` it shows me that there is a mixin, but it's left up to the user to figure out what command to run. It's not always clear what to run next.

What if we did this instead?

In the search listings, we change URL to Home and we calculate what the value should be. Right now URL may not be a location that the user can go to. If they go to the download link for example, they will get a 404. If it's a github URL we should point them to the root of the repo instead.

It also removes the URL Type because now we are having people use the search results to move on to the show command. They aren't interacting directly with the URL anymore.

```
$ porter mixins search kustomize
Name        Description                           Author        Home
kustomize   A mixin for using the kustomize cli   Don Stewart   https://github.com/donmstewart/porter-kustomize
```

Then we introduce a new command `porter mixin show NAME` that provides details about a mixin:

```
$ porter mixin show kustomize
Name         kustomize
Description  A mixin for using the kustomize cli
Author       Don Stewart
Home         https://github.com/donmstewart/porter-kustomize

Install this mixin:
porter mixin install kustomize --version VERSION --URL URL
```

The above is displayed for a mixin that has not been installed yet. Porter would use the list of tags to determine the version to display to the user. If `latest` is available, we would show that. Otherwise we show the most recent tag.

```
$ porter mixin show kustomize
Name         kustomize
Description  A mixin for using the kustomize cli
Author       Don Stewart
Home         https://github.com/donmstewart/porter-kustomize
Version      0.2-beta-3-0e19ca4
Location     /Users/carolynvs/.porter/mixins/kustomize

Upgrade this mixin:
porter mixin install kustomize --version VERSION --URL URL
```

The above is displayed for a mixin that has been installed. Porter includes the installed version and the location of the installed mixin.

**Calculating Home**
* For github URLs we can go to the root of the repo
* For atom feeds, we use the most recent version's link with a `rel=related`, if none is found we use the author uri
* If we don't recognize it we give the raw URL

**Comment by vdice** [comment]
Love it! Definite UX improvements here.  👍

**Comment by carolynvs** [comment]
Closing in favor of [PEP005 - Mixins are Bundles](https://github.com/getporter/proposals/blob/main/pep/005-mixins-are-bundles.md). When we have that we won't "install" mixins anymore, just pull and run like a docker image.

So you will still have a way to search for mixins, but the "install" experience, where you pick a mixin to use in your bundle will be completely different from what is proposed here.
