### ISSUE TITLE
Proposal: Naming/Versioning Manifest updates

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1151]
# Proposal: Naming/Versioning Manifest updates

This issue proposes to update the naming and versioning fields in the Porter manifest, as well as prescribe some immediate follow-ups around Porter build and publish functionality to utilize the simplification these updates bring.

## Manifest updates

- [x] https://github.com/getporter/porter/issues/1333

Currently, the naming and versioning fields in the Porter manifest are: `name`, `version` and `tag`.  The last one of these has heretofore been used to capture the full name of the bundle reference, e.g. `myregistry/myorg/mybuns:v0.1.0`.

We intend to preserve `name` (as the common name of the bundle) and `version` (as the semantic version of the bundle) but replace `tag` with `registry` (and, optionally, `reference`).

* `registry`: this is the OCI registry and org/subdomain for the bundle, e.g. `myregistry.com/myorg`.  Porter will then construct the full bundle reference using this and the values for `name` and `version`, e.g. `myregistry.com/myorg/mybuns:v0.1.0` from the example below.

* `reference`: (OPTIONAL) this can be used to specify the full bundle reference when needed.  When the bundle is published this value will be used rather than the value constructed from the `name`, `version` and `registry` values.

```
name: mybuns
version: 0.1.0
registry: myregistry.com/myorg
# Optional: can use reference to specify the exact bundle reference (correlate to deprecated `tag` field)
# reference: myregistry.com/myorg/mybuns:v0.1.0
```

For a few issues and added context that led to the genesis of this proposed update, see https://github.com/deislabs/porter/issues/459 and https://github.com/deislabs/porter/issues/1146.

## Build functionality

- [x] https://github.com/getporter/porter/issues/1334

There's long been a wish to override the values above at bundle build-time.  See https://github.com/deislabs/porter/issues/694 and https://github.com/deislabs/porter/issues/814.  Being able to dynamically override these values opens up CI/automation possibilities for building and testing different bundle variants.

Assuming we proceed with the aforementioned manifest updates, the following added functionality is proposed to be added to the `porter build` command.

### Added flags

* `--name`: override the bundle name value
* `--version`: override the bundle version value
* `--registry`: override the bundle registry value
* `--reference`: override the full bundle reference

For all of the above, Porter would update the manifest being referenced with the supplied overrides and save these changes.

## Publish functionality

- [ ] https://github.com/getporter/porter/issues/1335

Today, Porter's publish command offers the `-t/--tag` flag to override the bundle reference (and update the invocation image name accordingly) prior to pushing to an OCI registry.  The flag naming was directly inspired by the correlate from the `docker build` command, but we've since realized that we'd like to restrict it to just representing a Docker tag override, rather than an override for the bundle reference.  Therefore, we propose to redefine this flag's purpose and add a new flag, `--repository`, to serve the purpose of this flag's previous responsibility.

* `-t/--tag`: override the Docker tag of the bundle reference (and invocation image), e.g. `latest`, `v0.1.1`, etc.
* `--reference`: override the bundle reference entirely (and rename the invocation image accordingly), e.g. `otherregistry.com/otherorg/mybuns:v0.1.0`

**Comment by carolynvs** [comment]
I'm a bit concerned about the `-r` short flag, since it is going to inevitably get confused with the `--repository` flag. Since we have a conflict, and can't provide short flags for everything, what do you think about just having the long flags initially and not committing to short flags in the first iteration?

**Comment by vdice** [comment]
Good call re: potential confusion around the short flags.  I've updated the proposal to remove them for the initial implementation.  Thanks!

**Comment by MChorfa** [comment]
It would be nice to have a way to authenticate against a private registry, without having to do `docker login` and `docker logout` on each stage.

**Comment by carolynvs** [comment]
@MChorfa Was this comment intended for another issue?

**Comment by MChorfa** [comment]
Sorry wrong issue :(

**Comment by squillace** [comment]
This looks good, start with the long flags -- these will mostly be automated anyway. One question, @vdice. We discussed somewhile ago the idea that Porter would include the built docker file's digest automatically, so that you don't have to build the bundle, publish it (to establish the invocationImage's digest) and THEN go back into the porter file to update with the digest of the image to make it possible to use as a thick bundle.

Do we have a proposal for that kind of thing yet?

**Comment by squillace** [comment]
Other questions: 
- is there EVER a UX scenario in which the installer image would differ in tag from the bundle?
- why on god's green earth would someone use the name, registry, and tag elements and then also use the repository key? what would you GET out of that? It this merely to rename the current --tag item?

**Comment by vdice** [comment]
@squillace 

> We discussed somewhile ago the idea that Porter would include the built docker file's digest automatically, so that you don't have to build the bundle, publish it (to establish the invocationImage's digest) and THEN go back into the porter file to update with the digest of the image to make it possible to use as a thick bundle.

Hmm, I don't believe we have a proposal for this.  Do we have an issue(s) already?

> is there EVER a UX scenario in which the installer image would differ in tag from the bundle?

I wouldn't think so.  There's no longer a way to set a custom invocation image name in Porter, so if bundles are built via recent versions of Porter, then they'll always match.

> why on god's green earth would someone use the name, registry, and tag elements and then also use the repository key? what would you GET out of that? It this merely to rename the current --tag item?

I don't think we're expecting users to override all four.  Rather, I can see use cases for overriding only the `tag` _or_ only the `registry` _or_ only the `name` _or_, if the full repository value should be overridden (which itself is in the form of `registry/name:tag`, but could also include sub-domains under a given `registry`), then they can go straight to overriding `repository` and not mess with the others.  Does that make sense?  However, you raise a good point: if a user supplies values for all four, which do we defer to?  I'd say `repository`.

**Comment by squillace** [comment]
@vdice

> I don't think we're expecting users to override all four. Rather, I can see use cases for overriding only the tag or only the registry or only the name or, if the full repository value should be overridden (which itself is in the form of registry/name:tag, but could also include sub-domains under a given registry), then they can go straight to overriding repository and not mess with the others. Does that make sense? However, you raise a good point: if a user supplies values for all four, which do we defer to? I'd say repository.

I agree, good point. Here's an example of what I did in order to repoint a bundle at two different registries (Notice that GHCR requires a format of registry/org/repo/imagename:imagetag, which is a different formal requirement than others. So breaking them out is good, and letting me rewrite the entire thing is good for non-standard strings. https://github.com/squillace/gh-cnab/blob/58554f1e665890c778b79168364113ae50c61894/.github/workflows/main.yml#L33

**Comment by vdice** [comment]
Edit note: changed `repository` to `reference` in OP per https://github.com/getporter/porter/issues/1335#issuecomment-714691517
