### ISSUE TITLE
Rename, move, and hide Porter's generated Dockerfile

### ISSUE THREAD

**Issue by gaurimadhok** [getporter/porter#1162]
**Is your feature request related to a problem? Please describe.**
The dockerfile that Porter generates and uses to build the invocation image is named Dockerfile and is in the directory with the rest of the bundle. If someone is trying to use Docker within their bundle and wants to make their own dockerfile, they will have to name it something else. 

**Describe the solution you'd like**
A potential solution suggested by @carolynvs is to rename the generated Dockerfile to Dockerfile.porter or .Dockerfile.porter and put it in the .cnab directory. The .cnab directory is already hidden to prevent confusion,  so adding the Dockerfile within that directory to hide it will also help limit confusion. When building the invocation image, the docker build command could be adapted by simply adding .cnab/ before the name of the dockerfile and changing the name of the file.

**Comment by carolynvs** [comment]
Yeah I think if we can make this command work essentially (but automated through porter, we don't really run a raw docker command), then it would be less confusing for people:

```
docker build -t INVOCATIONIMAGE -f .cnab/Dockerfile .
```

If we can get it to work with the Dockerfile moved under .cnab, then we wouldn't even need to rename it. 👍

**Comment by carolynvs** [comment]
Heads up when this is implemented, we will need to tweak the exclude fix with the updated Dockerfile/dockerignore names per https://github.com/getporter/porter/pull/1263
