### ISSUE TITLE
Mixin schema not embedded in published mixin binary

### ISSUE THREAD

**Issue by gaurimadhok** [getporter/porter#1174]
## Describe the bug
When a mixin is published, its schema is not embedded in the binary. This is a problem because a person using the mixin will not be able to see what parameters are accepted as part of the schema which could lead to errors they do not know how to fix. 

## To Reproduce
1. Run `porter mixins install docker`
2. Use the docker mixin in the porter.yaml
3. See that VS code does not recognize the schema.

## Expected behavior
The mixin schema should be embedded in the binary when the mixin is published. 

## Version
porter v0.26.3-beta.1-21-g16e5e7ee

**Comment by gaurimadhok** [comment]
assign @carolynvs

**Comment by carolynvs** [comment]
This has been fixed in the docker mixin and skeletor updated to add an integration test that checks that the schema is embedded properly.
