### ISSUE TITLE
Find invocation image in user facing text and replace with the term bundle image/container

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1188]
Everyone I talk to who encounters the term "invocation image" has an immediate negative confused reaction to the term. I think this is a term that maybe makes sense for CNAB but is something that Porter should abstract for its users. 

I recommend that we use the term "installer" for user facing documentation and text, replacing any text in the CLI output or documentation. We already use that term when we set the invocationImage name e.g. bundlename-installer and it has worked well for people seeming to get it.

**Comment by carolynvs** [comment]
Now that we don't even create an image at all that is distinct from the bundle for the invocation image, I think we can simplify this even further and replace "invocation image" with the bundle's image/container.

**Comment by kichristensen** [comment]
Handled in #175
