### ISSUE TITLE
Validate that the author didn't use reserved parameter names during porter lint

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1226]
Porter has reserved parameter names, for example `porter-debug`, that authors can't use for their own bundles. We should check that the author didn't use any reserved names that would collide with our own naming conventions for parameters, outputs, etc during `porter lint` and hard fail.

**Comment by Simpcyclassy** [comment]
Hello, @carolynvs I would like to work on this ticket.

**Comment by carolynvs** [comment]
Thank you that would be great!
