### ISSUE TITLE
Document how to share a porter config file

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1232]
When working as a team, is there a good best practice for sharing and getting someone setup with a porter config file?

**Comment by squillace** [comment]
@carolynvs what do you mean here? what does "share" mean?

**Comment by carolynvs** [comment]
Say that a team manages their bundles with Porter and stores their secrets and Porter history in the cloud. Each of their config will look terribly similar if not identical. Now a new person comes on the team and needs to get set up with Porter. 

What does that setup experience look like for them?
Are they copying around a magic config file from their co-workers?


This is a placeholder to think about if Porter could help with this, either through:

* documentation, perhaps an article with recommendations
* improvements in how the config file is set up so that it's better suited for sharing some parts and letting individuals customize other parts
* providing commands to work with the config file

**Comment by squillace** [comment]
Aren't you suggesting that config.toml is just a dotfile? I'd imagine that the settings in the config.toml would also be matched by env vars set in .bashrc eventually, too.

**Comment by carolynvs** [comment]
I think with the ability to access secrets from a config file, this fixes what I was most concerned about.
