### ISSUE TITLE
Move out of deislabs organization

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1249]
As part of the acceptance of our CNCF sandbox application, we are moving out of the deislabs github organization into one that we created a while back just for this purpose: https://github.com/getporter/

Our larger set of tasks for the application is being tracked in https://github.com/cncf/toc/issues/533.

https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

- [x] Create teams in the new organization that reflect our current teams:
  * @deislabs/porters -> @getporter/contributors - Members of this group have merged a PR and can have issues assigned to them and be mentioned.
  * @deislabs/porter-contributor -> @getporter/TBD - Members of this group have helped for a while and have triage rights so that they can apply labels. We are still working on this role and how to make it useful with github's permissions honestly. There's more work to be done here.
  * @deislabs/porter-maintainers -> @getporter/maintainers - Members of this group have maintainer on the repositories. They can merge pull requests.
  * @deislabs/porter-admins -> @getporter/admins - Members of this group have admin on the repositories and can modify dangerous repository settings.
- [x] Invite members of old teams to new teams.
- [x] Transfer repositories, removing the porter prefix. For example, deislabs/porter-packages becomes getporter/packages. The main repo keeps the same name, deislabs/porter -> getporter/porter.
  - [x] Transfer our project board Porter and Mixins to the getporter org
    **edit(vdice): the [Roadmap board](https://github.com/deislabs/porter/projects/4) as well, right? Though, in reading https://docs.github.com/en/github/managing-your-work-on-github/managing-project-boards, I'm not sure if we can move projects from one org to another** 🤔 
   **next edit(vdice): alas, it seems we lost GH projects that were on the repo itself (like Roadmap) and for org projects (like Porter and Mixins), although the template copied over, none of the issues did.  We'll have to figure out a way to re-populate with the issues (from https://github.com/orgs/deislabs/projects/2 to https://github.com/orgs/getporter/projects/1.** 
  - [x] Fix the githhub action in the porter repo so that it keeps auto adding issues to the board
- [x] Edit netlify /src redirects to to go to the new github organization. These redirect https://porter.sh/src/CODE/PATH to a github code file.
- [x] Find raw github paths and swap them for the netlify /src redirects when possible as that is easier to manage, especially on the website.
  - [x] getporter/porter
  - [x] the rest of the porter repos
- [x] Update porter-vanity to use new organization. This is used by the go client when locating our source code. This organization move is why we have a vanity import path, `get.porter.sh`, so that we don't need to update code.
- [x] Update text on all assets to change to new organization. **edit(vdice): need to get clarification on this one, but we do have PRs open for updating text in all of the porter repos**
- [x] Update builds on Azure Pipelines to reference new repository locations. Pretty sure we can't "update" and it actually is delete job, recreate from relocated repo.
  * Create new pipelines org, getporter
  * Look into import/export
  * Recreate and attach variable group

**Comment by iennae** [comment]
pretty sure Azure Pipelines is a delete/recreate as well as it's based off the org name and it would change based on location. Leaving it even if it works might be problematic.

**Comment by carolynvs** [comment]
Ah okay yeah makes sense. I'll make a new pipelines org called getporter and recreate them there.

**Comment by carolynvs** [comment]
@vdice By assets I just meant URLs, github markdown, website text, etc. I think this is covered by everything you have been doing for the past few days so when you think you are done, feel free to close.

**Comment by vdice** [comment]
Although some PRs still await reviews, all the work in this ticket has been implemented!  Closing.
