### ISSUE TITLE
Add DCO check

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1250]
As part of the move to the CNCF, we will drop the Microsoft CLA bot and switch to DCO.

https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

- [x] Update docs to explain the DCO and remove any reference to the CLA bot. 
- [x] Remove the CLA Bot as a required pull request check.
- [x] Remove the Microsoft users from our repositories that runs the CLA bot.
- [x] Enforce the DCO on pull requests.

**Comment by vdice** [comment]
For `Enforce the DCO on pull requests`, we'll have to do this on an ad hoc basis.  The new check will only become eligible for making required once the next PR is issued in a given repo.

**Comment by carolynvs** [comment]
Are we ready to enable the DCO bot?

**Comment by vdice** [comment]
It's enabled on all repos in this org, so should run checks automagically.  We see it doing so in getporter/porter, but let's double-check in any of the others.

**Comment by carolynvs** [comment]
Oh cool, how did you turn it on?

**Comment by vdice** [comment]
When I configured the integration (via https://github.com/apps/dco), I selected 'apply to all repos' (or something like that)... so, all of the repos we migrated automatically get the check.  (And all subsequently-created repos in this org will get it; but we can update the app config if this isn't what we wish in the future.)

**Comment by vdice** [comment]
I've now set the DCO check as required in all Porter repos as I push PRs for org updates.  Closing!
