### ISSUE TITLE
Transfer porter.sh to CNCF

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1252]
- [x] Transfer domain registration to CNCF/LF
- [x] Move to CNCF netlify team, transfer DNS + website there
- [x] Ask if we can use Netlify analytics and drop google analytics
- [x] ~If not, transfer our GA website somehow or change the code if need be (really hope we can do netlify analytics instead)!~

**Comment by carolynvs** [comment]
@flynnduism Is the domain transfer complete?

**Comment by carolynvs** [comment]
Transfer complete!

**Comment by flynnduism** [comment]
Yes the domain handover is complete
