### ISSUE TITLE
Is there a CHANGELOG?

### ISSUE THREAD

**Issue by coryodaniel** [getporter/porter#1270]
**What is your question?**
Does porter have a changelog?

**What have you tried already?**
I haven't interacted with it in a while and I'm curious about what has changed!

**Where have you looked already to figure this out?**
Grepped the repo and couldn't find one.

**Was the existing documentation unclear or had gaps?**
If you found a page that should have answered your question but didn't, let us know what would have been helpful to have on that page so we can improve it.

**Comment by vdice** [comment]
Hi @coryodaniel,

Great question.  Porter doesn't currently have a CHANGELOG, but I'd think it would definitely be worth considering adding one.  Right now, the best way to get an overview of changes over time is to scan the release notes on the [Porter releases](https://github.com/getporter/porter/releases) page.

**Comment by coryodaniel** [comment]
That's a well kept release page! Thanks.
