### ISSUE TITLE
blog design: dangling date in single blog post view

### ISSUE THREAD

**Issue by iennae** [getporter/porter#1302]
I'm not sure if it's intentional or not but it seems like the date is dangling off to the side on the single blog post view. 

Example page: https://porter.sh/blog/docker-mixin-blog-post/

If it's intentional just close this issue. 

---
Notes:
* Goal: Make the date look prettier for blog post pages. Either directly under the title or what I was trying to do was make it on the same level as the title but on the right hand side.
* The changes need to be made to our Hugo theme Sass and/or layouts in https://github.com/getporter/porter/tree/main/docs/themes/porter. Blog posts use the layouts/blog/single.html page and the sass is mostly in static/sass/helm-blog.scss
* You can preview your changes by following the instructions in the [Contributing Guide](https://porter.sh/src/CONTRIBUTING.md#preview-documentation).

**Comment by carolynvs** [comment]
I've just created a new label "website" for items related to graphic design, html, css, etc. That way people with those skills can filter for issues that they can help with. 

Unfortunately, those are skills that I am always happy to timebox and do the best I can but can't promise to be able to achieve what is asked for. 🤷‍♀️
