### ISSUE TITLE
Using file type parameters from parameterset on published bundle fails with base64 encoding issue

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#1320]
## Describe the bug
When I have a parameter of type 'file', it is correctly available when invoking actions for the bundle in the current working directory, but if invoking the action on a published bundle (porter install --tag ...) it fails with "invalid base64 value"

## To Reproduce
1. Define a parameter of type 'file' and set a destination path.
2. Create a parameterset and specify a value for the parameter
3. Publish the bundle to a registry
4. Run "porter install -p <name of parameterset>"
5. See error

## Expected behavior
I would expect that the file is mounted as is, just like it is if you run it from the local bundle or if you set the parameter using "--param <param_name>=<path_to_file>
It seems to only happen when the parameter is in a parameterset

## Porter Command and Output
```
$ porter publish
$ porter parameters generate temp
$ porter install --tag localhost:5000/temp:v0.1.0 -p temp
installing HELLO...
Error: invalid parameters: cannot use value: dummy: value as parameter dummy_file: invalid base64 value: dummy: value
```
If I base64 encode the content of the file, then it works just like when the bundle is local or if using a --param option instead of parameterset.

## Version
Copy the output of `porter version` below
porter v0.29.1 (2e0f3648)

**Comment by vdice** [comment]
Thank you for the bug report.  I'll take a look.
