### ISSUE TITLE
porter uninstall REQUIRES the tag if installed from tag

### ISSUE THREAD

**Issue by squillace** [getporter/porter#1326]
## Describe the bug
`porter uninstall` requires the usage of a `--tag` switch if the bundle was installed from a `--tag`. I expect to be able to install from a tag, and uninstall from the `installations` name. 

## To Reproduce
1. `porter install --tag ghcr.io/squillace/cncf-projects-app/cncf:v0.1.8 -c <creds name>`
2. After installation, run `porter uninstall cncf-projects-app -c cncf`

## Expected behavior
Expected behavior is that the installation name means something, and that porter locates the installation and invokes the uninstall action.

## Porter Command and Output
```
squillace@dellsquill:~/work/squillace$ porter uninstall cncf-projects-app -c cncf
uninstalling cncf-projects-app...
Unable to find image 'ghcr.io/squillace/cncf-projects-app/cncf-installer:v0.1.8' locally
Error: 1 error occurred:
        * Error response from daemon: Get https://ghcr.io/v2/squillace/cncf-projects-app/cncf-installer/manifests/v0.1.8: unauthorized


squillace@dellsquill:~/work/squillace$ porter uninstall -c cncf --tag ghcr.io/squillace/cncf-projects-app/cncf:v0.1.8
uninstalling cncf-projects-app...
executing uninstall action from cncf-projects-app (installation: cncf-projects-app)
Deleting the cluster issuer to work with cert manager....
clusterissuer.cert-manager.io "letsencrypt" deleted
Deleting the cert manager chart resources.
/usr/local/bin/helm3 helm3 uninstall cert-manager --namespace ingress-basic
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: *******
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: *******
```

## Version
Copy the output of `porter version` below

porter v0.29.1 (2e0f3648)

**Comment by squillace** [comment]
Now this is interesting. Above, the output and version are from WSL Ubuntu 20.04 running on Windows VM. 

Note this on Mac, and the porter version:

```
 🔋 99% (4:16)  porter uninstall -c cncf cncf-projects-app                                                                                                ✔  10220  19:58:02
uninstalling cncf-projects-app...
Unable to find image 'ghcr.io/squillace/cncf-projects-app/cncf-installer:v0.1.8' locally
v0.1.8: Pulling from squillace/cncf-projects-app/cncf-installer
Digest: sha256:7ebcb7aea6f5758caea78f9321d60f941f03a23b801a287ef48d6c9a20a8728b
Status: Downloaded newer image for ghcr.io/squillace/cncf-projects-app/cncf-installer:v0.1.8
executing uninstall action from cncf-projects-app (installation: cncf-projects-app)
Deleting the cluster issuer to work with cert manager....
clusterissuer.cert-manager.io "letsencrypt" deleted
Deleting the cert manager chart resources.
/usr/local/bin/helm3 helm3 uninstall cert-manager --namespace ingress-basic
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: *******
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: *******
```

porter v0.29.0 (5e7240cf)

So there may be a regression between .29.0 and .29.1. ???

**Comment by squillace** [comment]
I've updated to .29.1 on mac, and it kicks off. so perhaps I need to go test this on WSL/Windows and figure out whether there's some pathing that affects what happens? Or that the docker socket is subtly different?

 🔋 97% (5:14)  porter uninstall -c cncf cncf-projects-app                                                                                                ✔  10226  20:05:48
uninstalling cncf-projects-app...
executing uninstall action from cncf-projects-app (installation: cncf-projects-app)
Deleting the cluster issuer to work with cert manager....
clusterissuer.cert-manager.io "letsencrypt" deleted
Deleting the cert manager chart resources.
/usr/local/bin/helm3 helm3 uninstall cert-manager --namespace ingress-basic
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: *******
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: *******

**Comment by squillace** [comment]
GOT IT. if I specify the option `-c creds` at the end, AFTER the installation name, it fails. but if I reverse it. This is pretty much what it says in the documentation, but the precise order was unexpected. Not great, imho, but not a problem to concern ourselves with. :-)

```
porter uninstall [INSTALLATION] [flags]
The first argument is the installation name to uninstall.
```

```
squillace@dellsquill:~$ porter uninstall -c cncf cncf-projects-app
uninstalling cncf-projects-app...
executing uninstall action from cncf-projects-app (installation: cncf-projects-app)
Deleting the cluster issuer to work with cert manager....
clusterissuer.cert-manager.io "letsencrypt" deleted
Deleting the cert manager chart resources.
/usr/local/bin/helm3 helm3 uninstall cert-manager --namespace ingress-basic
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: *******
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: *******
```

**Comment by carolynvs** [comment]
This actually looks like it may either be a bug or we are missing a bit of what happened between the first and second command from your issue repro steps.

In the first command, Porter recognized the installation name just fine. So the arguments were parsed. It seems like the problem was that perhaps you weren't logged into the registry and the bundle's invocation image wasn't in the docker cache anymore?

```
$ porter uninstall cncf-projects-app -c cncf

uninstalling cncf-projects-app...
Unable to find image 'ghcr.io/squillace/cncf-projects-app/cncf-installer:v0.1.8' locally
Error: 1 error occurred:
        * Error response from daemon: Get https://ghcr.io/v2/squillace/cncf-projects-app/cncf-installer/manifests/v0.1.8: unauthorized
```

I can't tell if you then _immediately_ ran this next command back to back, or if you did anything in between, like perhaps a login?

```
$ porter uninstall -c cncf --tag ghcr.io/squillace/cncf-projects-app/cncf:v0.1.8

uninstalling cncf-projects-app...
executing uninstall action from cncf-projects-app (installation: cncf-projects-app)
Deleting the cluster issuer to work with cert manager....
clusterissuer.cert-manager.io "letsencrypt" deleted
Deleting the cert manager chart resources.
/usr/local/bin/helm3 helm3 uninstall cert-manager --namespace ingress-basic
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: *******
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: *******
```

If you ran `docker login` in between, it would explain why it worked suddenly. If you didn't then maybe there's a bug in porter and how it handles --tag, maybe we should pull the bundle if it's not on the computer (i.e. it's a bug).

Can you help fill in the blanks a bit?

\* Side note: what you did there was taking advantage of something we should shut down in porter. Looks like porter defaulted the name of the installation from the name of the bundle defined in the bundle.json from the tag, and it happened to match a bundle installed already. We really should require an installation name for everything other than install.

**Comment by carolynvs** [comment]
@squillace I'm closing because I haven't heard back and it sounds like this may not be happening anymore. Please reopen if you have more info!
