### ISSUE TITLE
Split up PORTER_HOME 

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1328]
Currently PORTER_HOME (defaults to ~/.porter) contains all kinds of files: porter binaries, mixins, plugins, cache, bundle installation data, etc. This doesn't follow standards for separating installation data from user data and is a problem for us packaging up [Porter for Homebrew](https://github.com/getporter/porter/discussions/1310) (and will probably be a problem for Chocolatey as well).

Let's split up the where we store data based on its type:

## System
The installation of Porter to the system. Depending on how it is installed: homebrew, chocolately, manual download, script; it will be a different location. For example homebrew's system directory for Porter would be `/usr/local/Cellar/porter/<version>/`. This would contain the following files:

* porter

## User
These are files specific to the user and can vary when there are multiple users on a machine. The location is determined using a hierarchy of checks:

1. PORTER_HOME
1. [XDG_DATA_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
1. HOME/.porter or USERPROFILE/.porter

If none of these environment variables are defined, it is an error condition. We are not going to guess where your home directory is and require that you set PORTER_HOME when nothing else is available.

* runtimes/porter-linux-amd64 (previously porter-runtime*)
* mixins
* plugins
* cache (When XDG is defined, we should use XDG_CACHE_HOME)
* config.* (When XDG is defined, we should use XDG_CONFIG_HOME)

\* This needs to move because eventually we are going to support multiple invocation image runtime formats, and looking up the location of the runtime binary from the user directory is where it's going to end up eventually anyway. We may need to do this separately but I wanted to call out that it may be more work to keep it in system.

## Data
These are data files for working with installations. They are logically separate because they may not even be stored on the filesystem. This data is processed through the storage plugin to allow for sharing with other people via a shared location in the cloud. When they are stored on the filesystem, they go in PORTER_HOME.

* installations
* claims
* results
* outputs
* credentials
* parameters

# Notes

The changes necessary to support this are mostly in place. For example, when Porter needs to find a mixin, it looks for the porter home directory first, then /mixins/MIXIN. Same for plugins, and the cache. What needs to change is:

* makefile install target
* Our installation script
* [pkg/config.GetHomeDir](https://github.com/getporter/porter/blob/2fcaeb4b1490adaf9e33a2af1dedfa7c93413251/pkg/config/config.go#L86) which is used to find the user directory (e.g. PORTER_HOME)
* [pkg/cache.GetCacheDir](https://github.com/getporter/porter/blob/2fcaeb4b1490adaf9e33a2af1dedfa7c93413251/pkg/cache/cache.go#L162)
* [Reading config file](https://github.com/getporter/porter/blob/2fcaeb4b1490adaf9e33a2af1dedfa7c93413251/pkg/config/datastore/loader.go#L46)
* Resolution of porter binary, [pkg/config.GetPorterPath](https://github.com/getporter/porter/blob/2fcaeb4b1490adaf9e33a2af1dedfa7c93413251/pkg/config/config.go#L129)
* Resolution of porter-runtime binary, e.g. [pkg/config.GetPorterRuntimePath](https://github.com/getporter/porter/blob/2fcaeb4b1490adaf9e33a2af1dedfa7c93413251/pkg/config/config.go#L139)

**Comment by sestegra** [comment]
`make install` target should be adapted as well.

``` Makefile
install: install-porter install-mixins

install-porter:
	mkdir -p $(HOME)/.porter
	cp bin/porter* $(HOME)/.porter/
	ln -f -s $(HOME)/.porter/porter /usr/local/bin/porter

install-mixins:
	cp -R bin/mixins $(HOME)/.porter/
```

**Comment by sestegra** [comment]
I suggest to use `runtimes` with a `s`, because others directories are plural.

**Comment by carolynvs** [comment]
Thanks! I've updated the OP with your feedback so it's all in one place.
