### ISSUE TITLE
is gcr fully supported for porter workflow

### ISSUE THREAD

**Issue by sdeoras** [getporter/porter#1332]
**What is your question?**
I am trying to use gcr private registry for cnab bundles via porter and running into some issues.

**What have you tried already?**
porter publish pushed all the layers but gave an error at the end:
```
porter publish --debug
<redacted>
Starting to copy image gcr.io/my-registry/my-app-cnab-installer:v0.1.0...
Completed image gcr.io/my-registry/my-app-cnab-installer:v0.1.0 copy
Error: error pushing the bundle to gcr.io/my-registry/my-app-cnab:v0.1.0: unexpected status: 400 Bad Request
```
Despite error I do see container images on gcr, however, tags are not displayed correctly. In particular, `my-app-cnab-installer` tags are correct, but `my-app-cnab` image tags are not present at all.

I then edited the tags manually and tried to pull the images:
```
porter install --cred=my-cred --tag gcr.io/my-registry/my-app-cnab:v0.1.0
Error: unable to pull bundle before installation: unable to pull bundle gcr.io/my-registry/my-app-cnab:v0.1.0: unable to pull remote bundle: invalid media type "application/vnd.docker.distribution.manifest.v2+json" for bundle manifest
```

That said, I am able to push/pull via `docker` w/o errors.

**Where have you looked already to figure this out?**
I tried to search but there is not much info available considering cnab's are relatively new. I did see that GCR is listed as a CNAB compatible registry, however, it has not been validated by the porter team. It would be great to get your thoughts on it.

**Was the existing documentation unclear or had gaps?**
If you found a page that should have answered your question but didn't, let us know what would have been helpful to have on that page so we can improve it.

**Comment by squillace** [comment]
huh! I believe people have had success, but lemme try it

**Comment by carolynvs** [comment]
That first error really doesn't give enough info, even in debug mode does it? Drat. Either way, I'll fix the error handling so that it says _what_ it was doing when it got the 400 error.

**Comment by sdeoras** [comment]
Thanks @carolynvs for the fix. I have updated the description with the error message from `gcr.io`.

**Comment by carolynvs** [comment]
@squillace If I had to guess based on the new error messages, grc doesn't support the cnab media type. Perhaps it is returning the 400 because it doesn't understand it, and leaves the bundle in the registry with a docker manifest media type. That would explain the error when porter pulls the bundle.

Let us know when you have time to re-verify grc and cnab!

**Comment by sdeoras** [comment]
Hi @squillace and @carolynvs, looking forward to hearing if GCR is supported... wondering if you had any updates? thanks.

**Comment by squillace** [comment]
No, sorry @sdeoras these past two weeks have been a mess for me; I'll see about trying this out. I'll also reach out to the goog folks for their take.

**Comment by carolynvs** [comment]
Did we ever hear back about gcr support?

**Comment by squillace** [comment]
No. Was so far down on the totem pole that I failed to do this. @sdeoras, I'll pick this back up again. Apologies.

**Comment by sdeoras** [comment]
thank you @carolynvs and @squillace for following up. we would love to see GCR supported. thank you!

**Comment by iennae** [comment]
@carolynvs and @squillace, do y'all already have someone you are talking about with this? Happy to advance discussions here with the necessary folks.

**Comment by squillace** [comment]
Not yet, @iennae it would be great if you can ping the proper humans. I'd have to go through lasker to get the right person.... feel free to start an email thread (firstname.lastname@megacorp.com)

**Comment by iennae** [comment]
I'm able to replicate your error. I'll check in with the Container Registry folks to see if this is expected. I also tested the recommended Artifact Registry (replacement service for GCR with more repository options) and it works as intended. 

More details: 

The first step I've done is worked on replicating the error. I'm new to gcloud, so I noticed that Artifact Registry is recommended as a replacement to gcr. My configuration looks like 

```
REGION-docker.pkg.dev/PROJECTNAME/REPO-NAME/porter-hello:v0.1.0
```

I didn't run into any issues with Artifact Registry. 

Configuration in porter.yaml file
```
tag: us-west1-docker.pkg.dev/sigje-tutorials/porter/porter-hello:v0.1.0
```

Porter output
```
 porter install --tag us-west1-docker.pkg.dev/sigje-tutorials/porter/porter-hello:v0.1.0
installing HELLO...
Unable to find image 'us-west1-docker.pkg.dev/sigje-tutorials/porter/porter-hello@sha256:c13d59835c09ddf958eba1bb3b1a7661f65e4a90b909da31a47578beebf942ea' locally
us-west1-docker.pkg.dev/sigje-tutorials/porter/porter-hello@sha256:c13d59835c09ddf958eba1bb3b1a7661f65e4a90b909da31a47578beebf942ea: Pulling from sigje-tutorials/porter/porter-hello
Digest: sha256:c13d59835c09ddf958eba1bb3b1a7661f65e4a90b909da31a47578beebf942ea
Status: Downloaded newer image for us-west1-docker.pkg.dev/sigje-tutorials/porter/porter-hello@sha256:c13d59835c09ddf958eba1bb3b1a7661f65e4a90b909da31a47578beebf942ea
executing install action from HELLO (installation: HELLO)
Install Hello World2
Hello World
execution completed successfully!
```

With Container Registry I am able to replicate your error. 

➜  my-bundle porter publish
Pushing CNAB invocation image...
The push refers to repository [gcr.io/sigje-tutorials/porter-hello-installer]


Rewriting CNAB bundle.json...
Starting to copy image gcr.io/sigje-tutorials/porter-hello-installer:v0.1.0...
Completed image gcr.io/sigje-tutorials/porter-hello-installer:v0.1.0 copy
Error: unexpected status: 400 Bad Request

**Comment by squillace** [comment]
oooo are there docs for the artifact regsitry? I wanna try that....

**Comment by iennae** [comment]
@squillace https://cloud.google.com/artifact-registry/docs

**Comment by iennae** [comment]
other than the initial setup for gcloud 

Set up credentials
```
gcloud components install docker-credential-gcr
gcloud artifacts locations list # to figure out where the possible locations are
 gcloud auth configure-docker us-west1-docker.pkg.dev
 gcloud auth login
 ```
 
Configuring and Setting up the Artifact Registry Repository
```
 gcloud services enable artifactregistry.googleapis.com
 gcloud artifacts repositories create REPOSITORYNAME --repository-format=docker --location=us-west1 --description="Porter repository"
 gcloud artifacts repositories list
 ```

**Comment by carolynvs** [comment]
Sounds like https://porter.sh/compatible-registries/ to say that GCR doesn't work with CNAB and add a new entry for Google Artifact Registry?

**Comment by squillace** [comment]
Yup, sure sounds like that to me. Thanks, @iennae !!!!
