### ISSUE TITLE
Manifest: Use registry and repository instead of tag

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1333]
Implementation for the corresponding section of https://github.com/getporter/porter/issues/1151:

Currently, the naming and versioning fields in the Porter manifest are: `name`, `version` and `tag`.  The last one of these has heretofore been used to capture the full name of the bundle reference, e.g. `myregistry/myorg/mybuns:v0.1.0`.

We intend to preserve `name` (as the common name of the bundle) and `version` (as the semantic version of the bundle) but replace `tag` with `registry` (and, optionally, `reference`).

* `registry`: this is the OCI registry and org/subdomain for the bundle, e.g. `myregistry.com/myorg`.  Porter will then construct the full bundle reference using this and the values for `name` and `version`, e.g. `myregistry.com/myorg/mybuns:v0.1.0` from the example below.

* `reference`: (OPTIONAL) this can be used to specify the full bundle reference when needed.  When the bundle is published this value will be used rather than the value constructed from the `name`, `version` and `registry` values.

```
name: mybuns
version: 0.1.0
registry: myregistry.com/myorg
# Optional: can use reference to specify the exact bundle reference (correlate to deprecated `tag` field)
# reference: myregistry.com/myorg/mybuns:v0.1.0
```

## AC

- the `tag` field is removed from the Porter manifest
- the `registry` and `reference` fields are added to the Porter manifest
- legacy manifests using the `tag` field continue to be supported
- docs updated/added

**Comment by vdice** [comment]
@carolynvs ah, had forgotten about the dependency declarations in a manifest.  Previously, we still used `tag` to specify the full bundle reference: https://github.com/getporter/porter/blob/main/pkg/manifest/manifest.go#L504

Should we also update this field?  It would be updated to `reference`.

**Comment by carolynvs** [comment]
Yup! I'm so glad you caught that. 💯
