### ISSUE TITLE
[ERR] yamux: Failed to write header: write unix @->/tmp/plugin726244114: write: broken pipe

### ISSUE THREAD

**Issue by f0rmiga** [getporter/porter#1359]
## Describe the bug

When doing a `porter install ...`, I got:

```
execution completed successfully!
2020/11/10 15:22:53 [ERR] yamux: Failed to write header: write unix @->/tmp/plugin726244114: write: broken pipe
```

This appeared only once since I started to use Porter a few hours ago.

## To Reproduce

Seems intermittent.

## Expected behavior

Not get an error.

## Porter Command and Output
```
$ porter install --cred <mycred>
... lots of output ...
execution completed successfully!
2020/11/10 15:22:53 [ERR] yamux: Failed to write header: write unix @->/tmp/plugin726244114: write: broken pipe
```

## Version

porter v0.30.1 (2931a5c3)

**Comment by carolynvs** [comment]
Hmm, yeah I have seen that sometimes as well but it doesn't appear to cause anything to fail. I think it is coming from our communication with a plugin. Perhaps we aren't closing the connection properly or are trying to log plugin messages after the connection is closed?

I'm not sure yet. 😀

**Comment by f0rmiga** [comment]
@carolynvs Yeah, I thought so too. Perhaps writing to the connection on a different goroutine than the one that closes it? Can be lots of things and I know practically nothing from the porter.sh src at this point. If the plugin at least had wrapped its context in the error message, it'd be easier to trace it back to the problematic code.
