### ISSUE TITLE
Adding Sprig for mutating outputs -> vars

### ISSUE THREAD

**Issue by coryodaniel** [getporter/porter#1364]
**Is your feature request related to a problem? Please describe.**

Sometimes an output needs to be manipulated for an input to another mixin invocation.

Say a bundle has two mixin invocations. 

The first one has an output that’s a list of IPs. 

The second one needs a single IP address as an input.

Using sprig we could split the IP list on comma and take the first IP. 

{{ bundle.outputs.ip_list | splitList “,” | first }}

**Describe the solution you'd like**
Including the [sprig](http://masterminds.github.io/sprig/) library to provide more template functions.

**Comment by carolynvs** [comment]
Thanks for the pointer to sprig! We most definitely want to have stronger templating features so that transforming outputs is easier.
