### ISSUE TITLE
[Helm] Helmv3 support

### ISSUE THREAD

**Issue by xiechengsheng** [getporter/porter#1384]
**What is your question?**
when I use helmv3 client in `porter.yaml`, in the install stage an error occurs:
```
Error: supplied clientVersion "v3.4.0" does not meet semver constraint "^v2.x"
Error: unable to generate Dockerfile: error generating the Dockerfile: error generating Dockefile content for mixins: 1 error occurred:
	* error encountered from mixin "helm": exit status 1
```

Is there a roadmap for supporting helmv3?

**Comment by MChorfa** [comment]
Hi, @xiechengsheng,
By default Porter comes with helm2 mixing. If you wish to use helm3 you need the install the mixin from: https://github.com/MChorfa/porter-helm3
Or 'porter mixin install helm3 --feed-url https://mchorfa.github.com/porter-helm3/atom.xml'

Hope this helps

**Comment by carolynvs** [comment]
We are working on updating our documentation and naming for the helm mixins to make it more clear that everyone should be using @MChorfa 's helm3 mixin. Sorry it was so unclear!
