### ISSUE TITLE
Explain should include the Porter version inside the bundle

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1407]
When I run `porter explain` I want to see which version of Porter was used to build the bundle, and therefore what version is embedded _inside_ the bundle.

```console
$ porter explain  --tag getporter/porter-hello:v0.1.0
Name: porter-hello
Description: An example Porter configuration
Version: 0.1.0
Porter Version: v0.30.1
```

In order to accomplish this we must add an entry into the bundle.json's custom section with information about Porter during `porter build`:

```json
{
  "custom": {
    "sh.porter": {
      "version": "v0.30.0",
      "commit": "3b7c85ba"
    }
//... rest of bundle definition
}
```

This change can be made in the following function:

Save the porter version (get.porter.sh/pkg -> pkg.Version + pkg.Commit) during `porter build`:
https://github.com/getporter/porter/blob/5efddb87b292184baceaf64a3301639e3949e4d1/pkg/cnab/config-adapter/stamp.go#L63

https://github.com/getporter/porter/blob/5efddb87b292184baceaf64a3301639e3949e4d1/pkg/cnab/config-adapter/stamp_test.go#L17

Print the porter version during `porter explain`:
1. Add PorterVersion field to https://github.com/getporter/porter/blob/5efddb87b292184baceaf64a3301639e3949e4d1/pkg/porter/explain.go#L22
2. Load the stamp from the bundle using pkg/cnab/config-adapter.LoadStamp(bundle) and set PorterVersion https://github.com/getporter/porter/blob/5efddb87b292184baceaf64a3301639e3949e4d1/pkg/porter/explain.go#L186-L191
3. Update the test here: https://github.com/getporter/porter/blob/5efddb87b292184baceaf64a3301639e3949e4d1/pkg/porter/explain_test.go#L123

**Comment by carolynvs** [comment]
Thank you, @nunix, for the suggestion. I was rewatching a demo video of yours and you mentioned that you set the bundle version to match the porter version so you could see it via `porter explain`.

**Comment by momporter** [comment]
Ok

**Comment by nunix** [comment]
oh so nice, I'm always setting the version of my bundles to the version of Porter, specially in the early days, so I knew if the bundle was able to leverage a feature from Porter.

Hope this helps others 😄

**Comment by joshuabezaleel** [comment]
Hi @carolynvs ! May I take a stab on this one? 🙂

**Comment by carolynvs** [comment]
I'm 3 days late but thanks for picking this up! 🎉

**Comment by joshuabezaleel** [comment]
@carolynvs no worries 🙂  I've put up a PR on this particular issue that was finished much easier since your explanation on the issue was really helpful. Looking forward to the review! 🙂
