### ISSUE TITLE
Helm Mixin Version 3 - Default installation

### ISSUE THREAD

**Issue by lucidprogrammer** [getporter/porter#1413]
**Is your feature request related to a problem? Please describe.**
It will be nice that I could specify that I don't want the helm (version 2) mixin to be installed, instead install helm version 3 by default.

**Describe the solution you'd like**
Ideally default to helm version 3 as it is generally the standard now, atleast possibly give the option which version you need.

**Comment by carolynvs** [comment]
Our plan is to stop installing mixins by default soon, and instead just install the exec mixin when you install porter. Then people who are scripting out their installs can add calls to porter mixin install to get what they need. #1192 is the one to subscribe to for updates on when we implement this.

**Comment by carolynvs** [comment]
I'm going to close this since the work will happen on that other issue. With the helm2->3 switch, it's bumping up in priority. Thank you for the feedback!
