### ISSUE TITLE
porter build --version doesn't accept semver with commit hash properly

### ISSUE THREAD

**Issue by squillace** [getporter/porter#1431]
## Describe the bug
porter is documented as accepting a SemVer --version option. The format to append a commit hash would be from https://github.com/Masterminds/semver might look like: `porter build --version 0.1.7+$(git rev-list --max-count=1 HEAD)`. 

However, the output is:
```
build --version 0.1.7+$(git rev-list --max-count=1 HEAD)
Error: could not set bundle tag to "v0.1.7+58d98af56c3a4c40c69535654216bd4a1fa701e7": invalid tag format
```

## To Reproduce
1. Run `porter build --version 0.1.7+$(git rev-list --max-count=1 HEAD)`.
2. See error

## Expected behavior
Porter should build and tag the bundle and installer with the complete version string.

## Version
Copy the output of `porter version` below

porter v0.32.0 (8e03c7da)

**Comment by vdice** [comment]
Thanks for the issue, @squillace .  My thinking is that Porter should sanitize the provided semver `version` value to a valid [Docker tag](https://docs.docker.com/engine/reference/commandline/tag) when tagging the invocation image and bundle.

For example, if the bundle version is: `0.1.0-beta.1+abcd1234`, the image/bundle tags could be sanitized to comply with Docker tag restrictions.  In this case, `0.1.0-beta.1-abcd1234` would comply.  (`+` is not allowed, but `-` and `_` are).

**Comment by carolynvs** [comment]
I like Vaughn's suggestion to default the tag to a sanitized version string when necessary, and printing a warning when we do that. We should also clearly document the limitations of docker tags on our website and on the existing blog post about using CI/C with these flags.

We should probably research a bit on what replacement character to use, in case there's already an accepted workaround for this semver -> docker tag problem.

**Comment by squillace** [comment]
related to #1432 as well

**Comment by MikkelHegn** [comment]
I'm running into this as well currently. What's the reasoning behind making semver a requirement, as opposed to just a recommendation?

I'm considering only using the commit id to identify my bundle.

**Comment by vdice** [comment]
> What's the reasoning behind making semver a requirement, as opposed to just a recommendation?

Good question.  This originates from the CNAB Spec for the underlying bundle.json that each Porter bundle is represented as.  Currently, the spec states that the version field [must be a SemVer2 string](https://github.com/cnabio/cnab-spec/blob/master/101-bundle-json.md#name-and-version-identifying-metadata).

**Comment by squillace** [comment]
the SemVer states the topology of the action surface and the semantics of the actions -- but the commit really targets the commit, which is great but doesn't speak to anything else. 

I would like to see us use the semver by default, but add the commit if you need to. as the semver is really six chars, but the git commit is a TON, having the semver isn't really a hit and conveys human information.

**Comment by carolynvs** [comment]
Setting the bundle version to _just_ a commit hash just isn't an option, it would create an invalid bundle definition that violates the CNAB spec. I really like Vaughn's solution:

`porter build --version v0.1.7+58d98af56c3a4c40c69535654216bd4a1fa701e7` would set the bundle version to `v0.1.7+58d98af56c3a4c40c69535654216bd4a1fa701e7` and would output an invocation image to `myorg/mybundle:v0.1.7_58d98af56c3a4c40c69535654216bd4a1fa701e7`.

That's the best we can do with the limitations in the the CNAB and OCI specs.

**Comment by squillace** [comment]
without the version, the bundle doesn't convey human information anyway.

**Comment by squillace** [comment]
whoops. was just trying to agree but I can't navigate buttons without more coffee
