### ISSUE TITLE
porter build --version should support leading 'v' in supplied semver

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1432]
Currently, `porter build --version` strictly enforces that the supplied version value adheres to semver.  This is fine, and what we want, but many users will supply e.g. `v0.1.0` instead of `0.1.0`, where the former isn't strictly semver and the latter is.

Therefore, to improve usability, Porter should support versions with a leading `v` and then trim as needed in the code.

**Comment by carolynvs** [comment]
This would be a good candidate for a good first issue once we add more information to the OP.

**Comment by carolynvs** [comment]
This was fixed in #1524
