### ISSUE TITLE
Docs invalid for dependencies yaml tag

### ISSUE THREAD

**Issue by JeremyGHutchins** [getporter/porter#1434]
## Describe the bug
I have two bundles (a and b) such that b requires a.  To enforce this, I am adding "dependencies:" in the porter.yaml for project b.  However, when I use the format provided in the docs...

```
dependencies:
  - name: mysql
    reference: getporter/mysql:v0.1.3
```
I get an error...

```
 Error: error unmarshaling the typed manifest: yaml: unmarshal errors:
   line 49: cannot unmarshal !!seq into map[string]manifest.Dependency
```

It seems, based off trial and error, that the format may instead be...

```
dependencies:
  project-a:
    tag: my-corp/project-a:tag
```

## To Reproduce
1. Create a project using dependencies as documented
2. Run `porter build`
4. See above error

## Expected behavior
Documentation matches behavior

## Porter Command and Output
```
$ porter build
Error: error unmarshaling the typed manifest: yaml: unmarshal errors:
  line 49: cannot unmarshal !!seq into map[string]manifest.Dependency
```

## Version
Copy the output of `porter version` below
porter v0.27.2 (aee93e98)

**Comment by JeremyGHutchins** [comment]
Bah!  Never mind.  I appear to have an older version.  No wonder.  Sorry.

**Comment by carolynvs** [comment]
Sorry, that really is not a helpful error! I'm glad you figured it out and shared the solution. 🙇‍♀️
