### ISSUE TITLE
Image digest validation can fail when building bundles locally

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1439]
## Describe the bug
I'm not sure how to perfectly reproduce this but it's happened a number of times. 

## To Reproduce
1. Build a bundle locally
2. Push the bundle
2. Install it using --reference
3. Uninstall it using the name

It seems that since the invocation image is already in the docker cache, it doesn't pull what was pushed. The local image doesn't have the repository digest. So it fails the repo digest validation.

## Expected behavior
We should update the cache with the pushed image so this doesn't happen, or detect it and try to pull it down.

## Porter Command and Output
```
/tmp$ porter uninstall porterops -c porterops
uninstalling porterops...
params: [porter-debug]
creds: [kubeconfig]
Error: 1 error occurred:
	* image digest validation failed: image ghcr.io/getporter/porter-operator-installer:v0.1.0 has no repo digests

```

## Version
v0.33.0

**Comment by carolynvs** [comment]
Ignore the merged PR that says it targeted this issue. I had to back it out in #1736 because it caused regressions.

**Comment by VinozzZ** [comment]
I'm not able to reproduce this bug. I checked the invocation image after running `porter build` with `docker image inspect` and see no `RepoDigests` is set. Then I ran `porter publish` and can see that `RepoDigest` is populated and updated.
Then When I run `porter install` using a reference and `porter uninstall` with a name, both commands are successful

**Comment by carolynvs** [comment]
I haven't reproduced this in like a year and just checked the git blame on the publish file and seems like I fixed this in August last year.
