### ISSUE TITLE
Content Digest Mismatch Error

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1445]
## Describe the bug
We have a flag for actions, --force, that repulls the bundle before running the action. It's useful when you are unrepentantly flaunting best practices in dev and are force pushing over a tag repeatedly while testing your bundle.

It doesn't work anymore now that we check if the repo digest of the invocation image matches what is declared in the bundle.

## To Reproduce
1. Publish a bundle
2. Install the bundle
3. Change the bundle and publish using the same reference
4. Run `porter upgrade INSTALLATION --force`

## Expected behavior
The bundle is re-pulled and I can run upgrade against that version of the bundle. I think we need to update the bundle definition in the claim when we repull? I'm not sure but I assume we are just updating the cached artifact in the local docker cache which isn't enough.

## Porter Command and Output
```console
# This doesn't
$ porter invoke porterops --action=create-namespace --param namespace=nstest -c porterops --force
invoking porterops...
params: [namespace porter-debug porterRepository porterVersion pullPolicy serviceAccount volumeSize]
creds: [config.toml kubeconfig azure-client-id azure-client-secret azure-connection-string azure-tenant-id]
Error: 1 error occurred:
	* image digest validation failed: content digest mismatch: invocation image ghcr.io/getporter/porter-operator-installer:v0.1.0 was defined in the bundle with the digest sha256:2fcf8ba278c3d7d4083817041550fed52a2331ee4c33aeb8431c0cffc76bf34b but no matching repoDigest was found upon inspecting the image

# This works
$ porter invoke porterops --action=create-namespace --param namespace=nstest -c porterops --reference ghcr.io/getporter/porter-operator:v0.1.0
invoking porterops...
params: [pullPolicy serviceAccount volumeSize namespace porter-debug porterRepository porterVersion]
creds: [azure-client-id azure-client-secret azure-connection-string azure-tenant-id config.toml kubeconfig]
Unable to find image 'ghcr.io/getporter/porter-operator@sha256:fee9b161d503dd3fd9873c3222e29d45d53a1b2bcf1890a20306628904ec1068' locally
ghcr.io/getporter/porter-operator@sha256:fee9b161d503dd3fd9873c3222e29d45d53a1b2bcf1890a20306628904ec1068: Pulling from getporter/porter-operator
Digest: sha256:fee9b161d503dd3fd9873c3222e29d45d53a1b2bcf1890a20306628904ec1068
Status: Downloaded newer image for ghcr.io/getporter/porter-operator@sha256:fee9b161d503dd3fd9873c3222e29d45d53a1b2bcf1890a20306628904ec1068
```

## Version
v0.33.0

**Comment by carolynvs** [comment]
Here is a report of the same underlying error "content digest mismatch" only this time it's happening with `porter archive`.

https://github.com/getporter/porter/discussions/1518

**Comment by carolynvs** [comment]
Here is another way this can manifest:

1. Publish a bundle from machine A.
2. Publish that bundle from machine B overwriting the same tag.
3. Run porter archive from machine A.

```
$ porter archive -r getporter/porter-hello:v0.1.1 test1.tgz
Error: Error preparing artifacts: content digest mismatch: image getporter/porter-hello-installer:v0.1.1 has digest sha256:b1b2599964d9c6eec89ed72609cdf6a7063e6aedd632c7ffdd92442215ded6e8 but the digest should be sha256:8b59c816ffcbec68089bd4e479ab183b204eb38a8d70e60d9bedd7db477529d6 according to the bundle manifest
```

The problem is that machine A has a cached definition of the bundle. When archive is run, the invocation image is pulled and the digest on that invocation image is compared with the CACHED definition of the bundle. They won't match because the bundle was rebuilt on machine B.

The workaround is to run archive with --force, so that the cached definition of the bundle is cleared out and the bundle re-pulled.

In this case, I'm not sure what we want to do. It is calling out a legit problem, someone overwrite a bundle. So one option is to tell people to run with --force in the error message and explain that the bundle has been force pushed. Another option is that we add a "is our cache stale for a bundle" check, that uses a cheap operation to query the registry to see if the bundle is out of date. I'm not confident we have enough information to do that yet though.

**Comment by VinozzZ** [comment]
I could not reproduce the error with porter `v1.0.0-alpha.20`
I tried to run both the original reproduce steps and the one from Apr 26, 2021. I was able to archive the bundle successfully

**Comment by carolynvs** [comment]
Great, thanks for checking!
