### ISSUE TITLE
Description column in tables should wrap

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1448]
## Describe the bug
When a description for a parameter or credential is long, it breaks the table layout.

## To Reproduce
```
porter explain -r ghcr.io/getporter/porter-operator:v0.1.0
```

## Expected behavior
The text should wrap at a certain character count and stay in its column.

## Porter Command and Output

![Screen Shot 2021-02-11 at 2 48 52 PM](https://user-images.githubusercontent.com/1368985/107697083-63bae480-6c78-11eb-86cf-fe29b74a566e.png)

## Version
v0.33.0

**Comment by carolynvs** [comment]
I don't have a recommendation for how to accomplish this. It would be great if there is an existing table writer library out there that can do this for us.

**Comment by carolynvs** [comment]
I think the table writer that we use has support for this!

https://github.com/olekukonko/tablewriter/pull/85/files#diff-8832bc7378a6534270b1de626d6a05245f7a7229847e1fc88cb08df569688e56R528

Here is a screenshot of text being wrapped in one of their tests
![Screen Shot 2022-01-26 at 4 09 29 PM](https://user-images.githubusercontent.com/1368985/151255385-86b7cde8-541a-4581-9472-89137c3b6d6e.png)

**Comment by joshuabezaleel** [comment]
I guess this issue can be closed since the addressing PR is already merged. 
I really like the output in comparison to the previous one, way much neater ❤️ 
![image](https://user-images.githubusercontent.com/7043511/155289739-35624d61-fd7d-4fa0-99b6-35d209d68138.png)
