### ISSUE TITLE
In wiring images section of the documentation, better document which fields are optional/required

### ISSUE THREAD

**Issue by scottbuckel** [getporter/porter#1464]
## Describe the bug

https://porter.sh/wiring/#wiring-images

In your talk to CNCF, you mentioned you can use tags OR digest with Porter (although digest isn't in the CNAB Spec). If you use a tag, Porter will resolve it for you. That wasn't clear until watching the talk linked below:
https://www.youtube.com/watch?t=314&v=IFWIBSzhgM4&feature=youtu.be

**Comment by carolynvs** [comment]
Closing and we'll track the problems with the images.NAME.tag field in #1357
