### ISSUE TITLE
Windows install script broken

### ISSUE THREAD

**Issue by karchf** [getporter/porter#1467]
It looks like the install-windows.ps1 is incorrectly referencing 0.34.1 when it should be 0.34.0. This is likely left over from 0.33.1, which was the previous version.

As such, the windows dynamic install does not function.

**Comment by carolynvs** [comment]
Thanks for letting us know!

**Comment by karchf** [comment]
Looks great now! And now on .34.2, no less! :)

**Comment by carolynvs** [comment]
Thanks for verifying and sorry about the borked install script!
