### ISSUE TITLE
Design: Bundle dependencies and parameterisation

### ISSUE THREAD

**Issue by glyn** [getporter/porter#147]
The current dependency model appears to require parameters to be provided as in this example:
https://github.com/deislabs/porter/blob/55e259ce57aabb7138c28668210f6dbfcc0243a0/build/testdata/bundles/wordpress/porter.yaml#L8-L12

Sometimes this may be appropriate, but not always:
* The _user_ (i.e. the person installing the bundles) may need to supply some or all of the parameters of the bundle being depended upon. For example, the bundle being depended upon may contain a well-known component, e.g. Kafka, with lots of external configuration.
* Two or more bundles may depend on the same bundle. It would be clunky if all the bundles depending on the common bundle had to provide the common bundle's parameters. It would be tricky if these parameters were not provided with consistent values.
* The bundle depended upon may need to be installed strictly before the bundle(s) which depend on it.

The purpose of this issue is to consider options and decide on a way forward.

**Comment by carolynvs** [comment]
I've made an issue (https://github.com/deislabs/porter/issues/148) to document how Porter merges manifests of dependencies. I put in some notes there that clarify some of your comments, and explain how porter really works today.

The part that isn't well defined and needs more consideration are:
* what cases can porter not automatically handle, such as incompatible redeclarations of parameters (different types is one example)
* how can porter help point the user towards a solution (vs. just failing during `porter build` and leaving the user with no path forward)

**Comment by glyn** [comment]
Thanks @carolynvs. I guess the piece I don't yet understand is the relationship between the bundles which are input to porter and those which are output. You talk of "merging" which makes me wonder if the relationship is that porter combines input bundles into an output (root?) bundle?

**Comment by glyn** [comment]
Here's my potted summary of @carolynvs's explanation in a [slack thread](https://cloud-native.slack.com/archives/CEX1W7WMD/p1549895512009800):
* Porter merges its input bundles (a "root" bundle and its dependencies) and creates a single CNAB bundle as output.
* The invocation image of the output bundle drives the dependencies' actions before those of the root bundle.
* (Porter mixins may contribute both [build time](https://porter.sh/mixin-architecture/#build-time) as well as [run time](https://porter.sh/mixin-architecture/#run-time) behaviour.)

**Comment by carolynvs** [comment]
@glyn I've made a PR to take what we've discussed and document how Porter works today: #156

**Comment by carolynvs** [comment]
Closing since Porter no longer merges dependencies into a bundle anymore. See https://github.com/getporter/proposals/pull/8 for our latest plans with dependencies. That PEP doesn't specifically address parameters, however CNAB now supports parameter sources, where a bundle can satisfy parameters from the output of its dependencies.
