### ISSUE TITLE
Mixin descriptions should be optional

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1480]
Allow a mixin step to not specify a description, because I am lazy. The mixin is allowed to still require one but porter should be able to handle it being empty. When it is empty, if porter needs to print the description of the step, use some form of  "NAME mixin [index]"

**Comment by carolynvs** [comment]
Here is what needs to happen for this issue:

1. Only print the step description if it's set
https://github.com/getporter/porter/blob/ae88364c4c29e950813f8955168785bae212ca32/pkg/runtime/runtime.go#L76-L77
2. Return an empty string when the mixin step doesn't define a description (either because it's empty or not present)
https://github.com/getporter/porter/blob/ae88364c4c29e950813f8955168785bae212ca32/pkg/manifest/manifest.go#L762-L781

**Comment by ThorstenHans** [comment]
👋🏼 I would love to take this one

**Comment by carolynvs** [comment]
All yours!
