### ISSUE TITLE
Rename "table" format to plaintext

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1491]
We have two formats right now that both mean human readable text: plaintext (used by version) and table (used everywhere else). Table isn't really a good description of our output, consider porter show which has lots of different formatted text. The key difference is we want human formatted text, whether it's a table or ascii art doesn't matter.

I suggest we standardize on "plain" (or whatever) before we hit 1.0 as it impacts our flags.

## How to fix
Find instances in the code where we use the term "table" for the --output flag and replace it with "plaintext". We already have a constant defined for that value, so let's use that new constant and delete the table constant.

https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/printer/printer.go#L11-L16

Make sure to run the unit tests with `make test-unit` to identify any tests that relied upon the old "table" string.

**Comment by ThorstenHans** [comment]
what about `default`

**Comment by carolynvs** [comment]
My concern with default is that it doesn't tell you anything about what the output will be, only that it's the default displayed when the flag isn't specified. The other output values: json, yaml, tell you what you are going to get, you know?

**Comment by ThorstenHans** [comment]
Totally agree. However it is currently a mix of plain and table 😂

**Comment by carolynvs** [comment]
Yup! That is the point of this issue, to become consistent by selecting either plaintext or table and then updating existing commands to use the agreed upon term.

**Comment by joshuabezaleel** [comment]
May I have a try on this one? @carolynvs

**Comment by carolynvs** [comment]
It's all yours, @joshuabezaleel!

**Comment by carolynvs** [comment]
Fixed in #1803
