### ISSUE TITLE
Explain how to use a bundle for the first time

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1511]
This is how we expect people to use a bundle for the first time:
1.	User knows the bundle they want to use, e.g. porter explain -r ghcr.io/squillace/kubeflow:v0.1.9
2.	They run `porter explain --reference porter explain -r ghcr.io/squillace/kubeflow:v0.1.9` which tells you lots of information about the bundle, such as what parameters it accepts, and if credentials are required.
3.	They figure out where to get those credentials or what values they want to pass as parameters using porter credentials generate or porter parameters generate.
4.	They then run porter install passing in parameters and credentials.

It would be great if the `porter explain` command told you at the end of its output which commands to run next. For example,

```console
$ porter explain --reference getporter/hello-llama:v0.1.1
Name: hello-llama
Description: An example Porter bundle with parameters
Version: 0.1.1
Porter Version: v0.38.1-32-gb76f5c1c

No credentials defined

Parameters:
Name   Description                           Type     Default   Required   Applies To
name   Name of to whom we should say hello   string   llama     false      All Actions

No outputs defined

No custom actions defined

No dependencies defined

To install this bundle run the following command, passing --param KEY=VALUE for any parameters you want to customize:
porter install --reference getporter/hello-llama:v0.1.1
```

* Any required parameters should be included in the installation command, with `--param name=TODO`
* If credentials are defined, the output should tell them to run `porter credentials generate hello-llama --reference getporter/hello-llama:v0.1.1` first and then have the installation command include `--cred hello-llama`, e.g.

```
To install this bundle, run the following commands, passing --param KEY=VALUE for any parameters you want to customize:
porter credentials generate hello-llama --reference getporter/hello-llama:v0.1.1
porter install --reference getporter/hello-llama:v0.1.1 --cred hello-llama
```

The code for this command is located [here](https://github.com/getporter/porter/blob/7f8906befde8d9cd0e9a735bcc81e7b67127f17d/pkg/porter/explain.go#L311).

**Comment by joshuabezaleel** [comment]
Hi @carolynvs may I give a shot on this one? :)

**Comment by carolynvs** [comment]
@joshuabezaleel Please do so!

**Comment by joshuabezaleel** [comment]
I think this issue can be closed since the corresponding PR is already merged.
