### ISSUE TITLE
In task, how to display output value of prior task?

### ISSUE THREAD

**Issue by philliphoff** [getporter/porter#1516]
In my `porter.yaml`, I have one task that outputs a value that I want displayed in the deployment logs (e.g. the HTTP endpoint created by that task).  I tried to pass the output value to a subsequent `exec` task which just echos the value to the console.  However, the value ends up being masked (e.g. `******`).

Is there a way to disable this masking?

(I see other issues suggesting a `sensitive` flag that can be turned off, but it doesn't look like it applies to outputs.

**Comment by vdice** [comment]
Hi @philliphoff great question.  Alas, step/task-level outputs indeed don't yet support the `sensitive` toggle.  An outstanding feature request around changing this is here: https://github.com/getporter/porter/issues/855

However, if the output is declared at the bundle-level (it may still be used in the same tasks), it will default to *not* being sensitive (but it may be marked as such).  See https://porter.sh/author-bundles/#outputs

Therefore, if convenient, as a workaround until 855 is addressed, if the HTTP endpoint output is added to the global/bundle-level `outputs` section, I believe you would be able to see the unmasked value echo'd in that `exec` task.  It will also be possible to retrieve its value after the action has run, via `porter installation outputs show <output name>`.

**Comment by philliphoff** [comment]
Yes, this works, thanks!

**Comment by carolynvs** [comment]
Oh weird! That seems confusing that sometimes outputs are sensitive and sometimes they aren't (by default). I'm adding another vote to fixing #855 before v1 then.
