### ISSUE TITLE
porter explain does not list parameters which are scoped using 'applyTo'

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#1539]
## Describe the bug
When doing 'porter explain' only parameters that do apply to all actions are shown.

## To Reproduce
1. Run `porter create`
2. In the porter.yaml comment in the "parameters" section
3. Create another parameter, but for this add a scope like:
  - name: mysql_user2
    type: string
    default: wordpress
    applyTo:
      - install

4. Run `porter explain`
5. See that only "mysql_user" which had no "applyTo" is listed

## Expected behavior
All parameters in porter yaml should be listed and the "Applies To" column should list the action which it applies to.

## Porter Command and Output
```
$ porter explain
Name: porter-hello
Description: An example Porter configuration
Version: 0.1.0
Porter Version: v0.37.2

No credentials defined

Parameters:
Name         Description   Type     Default     Required   Applies To
mysql_user                 string   wordpress   false      All Actions

No outputs defined

No custom actions defined

No dependencies defined
```

## Version
porter v0.37.2 (26299559)

**Comment by carolynvs** [comment]
Thanks for letting us know!
