### ISSUE TITLE
Add field for maintainers to porter.yaml

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1559]
Maintainers is a field in bundle.json but isn't in porter.yaml. The bundles that we produce are still CNAB compliant but there isn't a way to populate this data using Porter right now.

**porter.yaml**
```yaml
maintainers:
- name: Yoko
   email: yoko@example.com
   url: https://yoko.example.com
```

1. Add `maintainers` field to the porter.yaml definition in https://github.com/getporter/porter/blob/bcf925b3b67851f48630b3163b620d0a79bcfb8d/pkg/manifest/manifest.go#L26. Both maintainers and the fields within should be optional, so that someone can for example just write their name but not include an email.
2. Update the test for the manifest https://github.com/getporter/porter/blob/bcf925b3b67851f48630b3163b620d0a79bcfb8d/pkg/manifest/manifest_test.go#L15
2. Map `maintainers` from the porter.yaml to the CNAB bundle definition bundle.json in https://github.com/getporter/porter/blob/bcf925b3b67851f48630b3163b620d0a79bcfb8d/pkg/cnab/config-adapter/adapter.go#L47
3. Update the test for the adapter here https://github.com/getporter/porter/blob/bcf925b3b67851f48630b3163b620d0a79bcfb8d/pkg/cnab/config-adapter/adapter_test.go#L19

If you'd like to work on this, just reply to this issue letting us know. Don't forget to checkout our contributing [tutorial](https://porter.sh/contribute/tutorial) to get started!

**Comment by ThorstenHans** [comment]
can I take this one?

**Comment by ThorstenHans** [comment]
🙏😁


https://thorsten-hans.com
________________________________
