### ISSUE TITLE
List hashicorp plugin on plugins page

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1587]
We should link to the @dev-drprasad 's hashicorp plugin on https://porter.sh/plugins, just like we do for the azure plugin.

* Here is where we need a page for hashicorp: https://github.com/getporter/porter/tree/main/docs/content/plugins
* The page should contain a subset of the information on the readme, the same type of information as with the azure plugin: https://github.com/dev-drprasad/porter-hashicorp-plugins

**Comment by DARK-art108** [comment]
Can I work on this issue?

**Comment by carolynvs** [comment]
@DARK-art108 Yes please! 👍
