### ISSUE TITLE
List kubernetes plugin on the plugins page

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1591]
We should document the Kubernetes plugin on our [plugins](https://porter.sh/plugins/) page.

* Here is where we need a page added: https://github.com/getporter/porter/tree/main/docs/content/plugins
* The page should contain a subset of the information on the [kubernetes plugin readme](https://github.com/getporter/kubernetes-plugins/blob/main/README.md), and show the same type of information as with the [azure plugin](https://porter.sh/plugins/azure).

**Comment by DARK-art108** [comment]
Can I work upon this issue!

**Comment by carolynvs** [comment]
@DARK-art108 sure thing, thanks for helping!
