### ISSUE TITLE
Iterate on outputs modeling in porter.yaml

### ISSUE THREAD

**Issue by RomainMuller** [getporter/porter#160]
As initially mentioned in #136, it would be interesting to iterate over how `outputs` are defined, possibly using a scheme similar to #159.

**Comment by jeremyrickard** [comment]
As part of this we should ensure that there is a mechanism in place for either dealing with conflicting definitions or documenting how they are handled (first wins? last wins?)

**Comment by jeremyrickard** [comment]
@RomainMuller thanks for opening this!

**Comment by carolynvs** [comment]
The current behavior is first wins. If another step further down uses the same output name, it will result in an error message `Error: output already set: mysql-root-password`
