### ISSUE TITLE
Incorrect number of parameters when generating parameter sets

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1600]
## Describe the bug
Porter is showing the TOTAL number of parameters in the bundle, including porter specific parameters which are not included in the parameter set.

## To Reproduce
Run porter parameters generate for any bundle. Note that it shows a number one higher than the number of parameters defined in porter.yaml because it is counting PORTER_DEBUG.

## Expected behavior
It should show the number of parameters defined in porter.yaml.

## Porter Command and Output
```
$ porter parameters generate hello-llama -r getporter/hello-llama:v0.1.0
Generating new parameter set hello-llama from bundle hello-llama
==> 2 parameters declared for bundle hello-llama
```

## Version
porter v0.38.1-32-gb76f5c1c (b76f5c1c)

### How to Fix
* Create your fix based on the **v1** branch. When you submit your PR, set the destination to the **v1** branch.
* This is the incorrect line of code. We should loop over the parameters in the bundle and count only parameters that are not internal. You can use this function [IsInternal](https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/parameters/parameters.go#L55) to know if it should be counted or not.

    https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/porter/parameters.go#L132

The output from this command is hard to unit test, since it is interactive, so testing manually is fine. You can run the command in the bug report to verify the fix is working.

**Comment by adammitha** [comment]
Hi @carolynvs can I take this on?

**Comment by carolynvs** [comment]
This is fixed in the v1 prerelease
