### ISSUE TITLE
Adding More Details about mixins and plugins with supported platform in README.md 

### ISSUE THREAD

**Issue by DARK-art108** [getporter/porter#1624]
**What design is being proposed?**
In README.md we should add some details about the porter mixins and plugins, and what all platform porter supports, this will help contributors to get basic insights from the readme.md, if they want to learn more about them they should read docs.

**This can be performed by adding tables like below [Source: Meshery(Layer5)]** 

![design1](https://user-images.githubusercontent.com/53623244/120979576-5da2c380-c793-11eb-8ae1-c025b4ae14a0.PNG)
![design2](https://user-images.githubusercontent.com/53623244/120979585-5f6c8700-c793-11eb-9f25-fa470d21e9a3.PNG)

**Additional Context**

**Risks/Concerns**

**What other approaches were considered?**

**Implementation details**

# Checklist
- [ ] An announcement of this proposal has been sent to the Porter mailing list: https://porter.sh/mailing-list
- [ ] This proposal has remained open for at least one week, to allow time for community feedback.

**Comment by carolynvs** [comment]
So are you thinking something like this?

## Mixins
Mixins provide out-of-the-box support for interacting with different tools and services from inside a bundle. You can always create a mixin, or use the exec mixin and a Custom Dockerfile if a custom mixin doesn't exist yet.
| Mixin |  Supported |
|----------|------------|
| [Kubernetes](https://porter.sh/mixins/kubernetes) | stable |
| [Azure](https://porter.sh/mixins/az) | stable |
| [Amazon](https://porter.sh/mixins/aws) | beta |
|...| |

## Plugins
Plugins let you store Porter's data and retrieve secrets from an external service.
| Plugin |  Supported |
|----------|------------|
| [Kubernetes](https://porter.sh/plugins/kubernetes) | beta |
| [Azure](https://porter.sh/mixins/az) | stable |
|...| |

**Comment by DARK-art108** [comment]
Yes, exactly that what I am referring to! @carolynvs
