### ISSUE TITLE
Adding up some more FAQ in Porter FAQ

### ISSUE THREAD

**Issue by DARK-art108** [getporter/porter#1648]
**What design is being proposed?**
We can add some more FAQs to Porter so that beginners can resolve most of the queries and doubts from their only! As I see our Porter FAQ is well maintained, But some beginners question can be added! I have scrapped some of my questions and their possible answer is given in slack.

Google Doc : https://docs.google.com/document/d/1SC59GRtcFgyy-23ZpnQcWqATOIR5dq6bPH7gY-LkxVQ/edit?usp=sharing

**Additional Context**

**Risks/Concerns**

**What other approaches were considered?**

**Implementation details**

# Checklist
- [ ] An announcement of this proposal has been sent to the Porter mailing list: https://porter.sh/mailing-list
- [ ] This proposal has remained open for at least one week, to allow time for community feedback.

**Comment by carolynvs** [comment]
@DARK-art108 Would you like to add the new questions from your document to the official FAQ on the website? https://github.com/getporter/porter/blob/main/docs/content/faq.md

**Comment by DARK-art108** [comment]
Yes, I will add it soon!

**Comment by sonukushwaha403** [comment]
Can I get assigned for this issue  , i would like to work on it.

**Comment by DARK-art108** [comment]
Yes go ahead @sonukushwaha403

**Comment by sonukushwaha403** [comment]
@DARK-art108  can you please ,provide me location wherei need to append , do i need to append in the  [google doc](https://docs.google.com/document/d/1SC59GRtcFgyy-23ZpnQcWqATOIR5dq6bPH7gY-LkxVQ/edit?usp=sharing) or some other location?

**Comment by sonukushwaha403** [comment]
Is this the [location](https://github.com/getporter/porter/blob/main/docs/content/faq.md) , issue #1648  reffers to. @DARK-art108

**Comment by DARK-art108** [comment]
Yes, @sonukushwaha403 is the correct location we need the above faq to be placed in that place make sure to clean the text and apply in the proper format!

**Comment by DARK-art108** [comment]
Any update on it @sonukushwaha403 or any help needed?

**Comment by sonukushwaha403** [comment]
> Any update on it @sonukushwaha403 or any help needed?
@DARK-art108  yep, i have updated the doc , and need help in the last Q in the doc

**Comment by DARK-art108** [comment]
@sonukushwaha403 start adding the FAQ from the beginning of the Doc, those are scraped from the slack channel!

**Comment by sonukushwaha403** [comment]
@DARK-art108  I did not get , Do i need to add all the faq in the [doc](https://docs.google.com/document/d/1SC59GRtcFgyy-23ZpnQcWqATOIR5dq6bPH7gY-LkxVQ/edit)

**Comment by carolynvs** [comment]
All of the FAQ in the linked doc are in the FAQ now.
