### ISSUE TITLE
loading a second env group in an app overrides the first env group

### ISSUE THREAD

**Issue by joegilley** [getporter/porter#1650]
## Describe the bug
Loading a second env group in an app overrides the first env group.

## To Reproduce

1. Have two or more env groups setup, and 1 application.
2. Load 1 env group on an application
3. Immediately load a different env group.

## Expected behavior
Expected environment variables from both groups to be added to the application.

## Version
website.

**Comment by carolynvs** [comment]
Hey Joe, can you provide more detail on what you are doing, and what you have tried? I am unsure what you mean by environment group, or loading an environment group on an application. 

Are you having trouble specifying multiple parameter sets with `porter install -p myEnvVars1 -p myEnvVars2`?

**Comment by joegilley** [comment]
> Are you having trouble specifying multiple parameter sets with porter install -p myEnvVars1 -p myEnvVars2?

nope, this is an issue using porter dashboard.  

> I am unsure what you mean by environment group, or loading an environment group on an application.

an "environment group" is a porter concept: https://dashboard.getporter.dev/env-groups: 
![image](https://user-images.githubusercontent.com/1476969/123863740-d0a8e100-d8de-11eb-9b89-d4fc99c8d37d.png).

And porter lets you load an env group from the application settings using the button:
![image](https://user-images.githubusercontent.com/1476969/123863850-ecac8280-d8de-11eb-88e1-a4d1ace9e4be.png)

in the Environment tab.

cc @sunguroku

**Comment by joegilley** [comment]
ah. 🤦 .  this is not https://github.com/porter-dev/porter

**Comment by carolynvs** [comment]
Phew! I was super confused for a minute. 👍
