### ISSUE TITLE
Specify the full docker registry name

### ISSUE THREAD

**Issue by jaudiger** [getporter/porter#1662]
**What is your question?**
Is there a possibility to fully provide the docker registry name by just writing it inside the porter.yaml file? Today the full registry name is composed of {REGISTRY}/{NAME}-installer. But it seems that there is no way to not use `-installer`. I understand that this is the default behavior and help to understand the purpose of the docker registry hosting the Porter bundle. But I was looking at a way to fully override the default behavior to specify my own registry name without `-installer`.

Well, this is not a blocking issue, more just a question ^^' about if this is at least possible.

**Where have you looked already to figure this out?**
I looked at: https://porter.sh/distribute-bundles/#bundle-publish

**Was the existing documentation unclear or had gaps?**
I found it useful, but it was unclear the first time I read it that the generated image is pushed to {REGISTRY}/{NAME}-installer

**Comment by vdice** [comment]
Thanks for your question.  While there is a way to specify the full bundle reference (via [reference](https://porter.sh/author-bundles/#bundle-metadata)), the installer/invocation image name will always be derived from the bundle reference.  To differentiate the installer image name from the bundle name, the `-installer` suffix is added.  At this time, there isn't a way to define a custom installer image name.

**Comment by jaudiger** [comment]
One way to do it could be to have two tags: one for the bundle and the other for the installer. This way we would need only one repository. Let's say we have the tag `v1.0.0` for the bundle application and the tag `v1.0.0-installer` for the installer.

Anyway, I got it thanks, at least I better understand why we need two repositories (with your other comment here: https://github.com/getporter/porter/issues/1666#issuecomment-874843465)

**Comment by carolynvs** [comment]
@jaudiger That is an interesting suggestion to keep a bundle in a single repository. 👍 

It isn't a high priority for our roadmap, but I would be open to a PR that changes Porter in v1 to do this if someone is willing to put in the work to understand how to make the change and are very thorough about fixing _everything_ related to the change. It would be a very large, complex change and need to update the docs as well.

**Comment by carolynvs** [comment]
This is now fixed in the v1 prerelease of Porter and we always push the invocation image directly to the same repository as the bundle now.
