### ISSUE TITLE
Python version upgrade in docker-compose mixin

### ISSUE THREAD

**Issue by jaudiger** [getporter/porter#1663]
**What is your question?**
When I try to use the docker-compose mixin, this log is produced:

```log
Docker Compose up
/usr/local/lib/python3.5/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.backends import default_backend
```

According to this PEP (https://www.python.org/dev/peps/pep-0478/), Python 3.5 has reached its end of life since September 2020. Regarding a production deployment, I found the warning problematic talking about security issues since the script is using a Python version that is no more maintained.

My question is just: is there a planned release update of the Python version?

**Where have you looked already to figure this out?**

The same log is produced according to the blog post: https://porter.sh/blog/migrate-from-docker-app/

**Comment by vdice** [comment]
@jaudiger Thank you for bringing this up.  The installation steps for the docker-compose mixin hadn't been revisited in while.  I took this opportunity to update and simplify per Docker's latest installation documentation: https://github.com/getporter/docker-compose-mixin/pull/18.  This update also eliminates the warning/log mentioned above.

**Comment by jaudiger** [comment]
Thanks, @vdice to have brought up a PR! Let me know when it is merged, I'll try it ASAP once the mixin is updated.

I was also wondering if the Docker Version could be updated to the latest version available (https://docs.docker.com/compose/release-notes/). What do you think?

**Comment by vdice** [comment]
> I was also wondering if the Docker Version could be updated to the latest version available (https://docs.docker.com/compose/release-notes/). What do you think?

Good idea.  It could be done in tandem with https://github.com/getporter/docker-compose-mixin/issues/5 -- I'll add a note to that issue.

**Comment by vdice** [comment]
@jaudiger are you interested in working on https://github.com/getporter/docker-compose-mixin/issues/5 ?  Otherwise, I should have some cycles to implement in the next few days as well.

**Comment by jaudiger** [comment]
> @jaudiger are you interested in working on getporter/docker-compose-mixin#5 ?

I'll give it a try, no problem. I think before tomorrow, I should have enough free time to work on it.
