### ISSUE TITLE
Failed to publish to AWS ECR

### ISSUE THREAD

**Issue by jaudiger** [getporter/porter#1666]
## Describe the bug
I was trying to do `porter publish` command, but I encountered an issue just after the publish. I got the following logs:

```logs
porter publish <

Pushing CNAB invocation image...
The push refers to repository [ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/application-installer]
1f4b811508dd: Preparing
81a68682ab54: Preparing
e57c98137487: Preparing
122111cff5b7: Preparing
ed90a75665ed: Preparing
28c38f4ad298: Preparing
a769284ca525: Preparing
a769284ca525: Waiting
28c38f4ad298: Waiting
ed90a75665ed: Layer already exists
28c38f4ad298: Layer already exists
a769284ca525: Layer already exists
81a68682ab54: Pushed
e57c98137487: Pushed
122111cff5b7: Pushed
1f4b811508dd: Pushed
v0.1.0: digest: sha256:87ae86655ec4b11a37aca6e1af408b09803909a00d07db142baec9cc368c6fca size: 1792

Rewriting CNAB bundle.json...
Starting to copy image ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/application-installer:v0.1.0...
Failed to copy image ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com/application-installer:v0.1.0: unexpected response: 404 Not Found
Error: error preparing the bundle with cnab-to-oci before pushing: unexpected response: 404 Not Found
The terminal process "bash '-c', 'porter publish'" terminated with exit code: 1.
```

Even if I see this error, when I go inside the ECR repository, I'm able to see an image pushed.

## To Reproduce
1. Run `porter build`
2. Run `porter publish`

## Version

porter v0.38.1 (3018b91c)

**Comment by vdice** [comment]
Hi @jaudiger, would you be able to try again after pre-creating repos for the `application-installer` installer image and `application` bundle in the ECR account?  I noticed the following footnote around ECR support in [Porter's list of compatible registries](https://porter.sh/compatible-registries/): 

`Amazon Elastic Container Registry (ECR) requires that you create the repository for the installer and the bundle before publishing.`

I can't seem to locate the origin issue or context around why this is needed at the moment, but perhaps we can first see if further progress can be made.

**Comment by jaudiger** [comment]
Thanks for your response, you were right after the creation of the second repository, I got it working. I didn't pay attention to this point in the documentation. Thanks.

Anyway just after doing the command porter publish, I got the following artifacts inside `application` repository:

![image](https://user-images.githubusercontent.com/31616285/124619895-509fef80-de79-11eb-820f-001555c05447.png)

And in the `application-installer` repository:

![image](https://user-images.githubusercontent.com/31616285/124619998-61e8fc00-de79-11eb-9f6c-bab79518dcdc.png)

Why is there two artifacts untagged inside the `application` repository? And do you know why we need both repositories? I think my last question is in correlation with an other issue I opened here: https://github.com/getporter/porter/issues/1662

**Comment by vdice** [comment]
> Why is there two artifacts untagged inside the application repository?

Interesting, I'm not quite sure why those are present there.  When I look at a bundle that I've pushed to my [ghcr.io registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry), I don't see untagged artifacts.  Could they be from the previous, failed publish actions?  Would it be possible to delete them and see if they are repopulated on a subsequent publish?

 > And do you know why we need both repositories?

Indeed, the `application` repository is the bundle repo itself, containing the bundle.json (the main bundle manifest that Porter produces after being given a `porter.yaml` to build/publish from) and metadata, including references to the second repository, the `application-installer` repository.  This `application-installer` repo is a 'classic' Docker/OCI image in the vein of other Docker images and represents the installer/agent used to execute the bundle at runtime, with any/all application assets shipped inside.  (To check out both artifacts locally after the bundle has been built via `porter build ...`, see `.cnab/bundle.json` and `.cnab/Dockerfile`.  These represent the bundle and the installer image, respectively.)

**Comment by jaudiger** [comment]
> Interesting, I'm not quite sure why those are present there. When I look at a bundle that I've pushed to my ghcr.io registry, I don't see untagged artifacts. Could they be from the previous, failed publish actions? Would it be possible to delete them and see if they are repopulated on a subsequent publish?

I flushed both repositories and tried again. I got the exact same thing.

`application` repository:

![image](https://user-images.githubusercontent.com/31616285/124714800-85a45480-df02-11eb-87b6-0fa884e989a2.png)

`application-installer` repository:

![image](https://user-images.githubusercontent.com/31616285/124714855-95bc3400-df02-11eb-973c-98f36a7a35fb.png)

You can even see that the images have been pushed at the same time. I don't understand why there is an image with 0.00 MB size. One more thing, you can even see that the image untagged in `application` at  `Jul 07, 2021 09:03:37 AM` as the same digest as the one in `application-installer`.

And, thanks for your clarification about the two repositories. With that in mind, I have another question: why the image inside the `application` repository is almost the same size as the one inside the `application-installer`? If I understand correctly one image should contain the OCI image (and thus be the larger one) and the other image should only contain the script (bundle, metadata, etc).

**Comment by vdice** [comment]
Curious.  I don't know why the artifacts are presented in this manner in ECR.  I checked bundle/installer repos under my DockerHub account as well and don't see similar behavior.  We'd have to do more research into the registry implementation and/or display of registry info that ECR uses...

You're definitely correct that the bundle repo should be minimal in size while the installer repo would be larger.  Here's what I see for a sample bundle I have hosted in ghcr.io:

bundle:
```
{
  "digest": "sha256:180cf591dedd973636ace153d48f68021b8ee5e1091e1d4b9480142475bf12f9",
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "size": 750,
  "config": {
    "digest": "",
    "mediaType": "",
    "size": 0
  },
  "layers": [

  ]
}
```

installer:

```
{
  "digest": "sha256:c229803ebf42aedb2d87cae62637907c0cbdcf80d7ddef4cce6107989b2263cf",
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "size": 2842,
  "config": {
    "digest": "sha256:c2ff45691435ed747a76db3366a4d07c89defa2e8ade3e3dc64d14d02343d412",
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 4229
  },
  "layers": [
    {
      "digest": "sha256:aed007321795cdc03a0ba9b238567ffa299459e9b0322a3d835a04d06afc2500",
      "mediaType": "application/octet-stream",
      "size": 22528174
    },
    {
      "digest": "sha256:da56f5cf862083fe5b13eb4b493feee02087400757906ff43edf78b065b0218a",
      "mediaType": "application/x-gzip",
      "size": 13784142
    },
    {
      "digest": "sha256:1e19326bd61e1bb1095d2f9cc9658071e46593a30110002442c3255e81e94865",
      "mediaType": "application/x-gzip",
      "size": 15281726
    },
    {
      "digest": "sha256:8757840a715d9015f815b8a980da3588ced7fbc0063bbb3cc14047311366576e",
      "mediaType": "application/x-gzip",
      "size": 5685780
    },
    {
      "digest": "sha256:82a8259902ff84821d3832c268e9008722ea67249031ad6df298a52b3c6d292c",
      "mediaType": "application/x-gzip",
      "size": 13631756
    },
    {
      "digest": "sha256:1ee0e7edb98188ec80cf4965e9157e9143d1e49b8773cd657d827021abe8ea3d",
      "mediaType": "application/x-gzip",
      "size": 13781312
    },
    {
      "digest": "sha256:73b61d28e7ab128f4cecc6a13a0d71af7d1b274420ab0b0fc687e05aaf3fa700",
      "mediaType": "application/x-gzip",
      "size": 154
    },
    {
      "digest": "sha256:79d96bde412bc87a30aacdc055bf809ec14209ec940230000cc9139a5c0ebcdb",
      "mediaType": "application/x-gzip",
      "size": 146
    },
    {
      "digest": "sha256:9f927225f6e937763d9c9ce38c4e5c1e1ca8a5e139ba7676c729984d46aefe3d",
      "mediaType": "application/x-gzip",
      "size": 5601
    },
    {
      "digest": "sha256:051ea0bdb20a06ce684e415be6c526c531f252b9ee77577d44810efbf11fda77",
      "mediaType": "application/x-gzip",
      "size": 5864
    },
    {
      "digest": "sha256:d11468edfb3526e224520877232d66bbc949956c7cd06136fb0bd6b71fc00129",
      "mediaType": "application/x-gzip",
      "size": 35601191
    },
    {
      "digest": "sha256:68873ff1a88de9b0249d3b5ab0f3baffea772dcbeabe47bd59d5a0c3e966f476",
      "mediaType": "application/x-gzip",
      "size": 35600930
    },
    {
      "digest": "sha256:c2ff45691435ed747a76db3366a4d07c89defa2e8ade3e3dc64d14d02343d412",
      "mediaType": "text/plain; charset=utf-8",
      "size": 4229
    }
  ]
}
```

**Comment by jaudiger** [comment]
This issue is not really critical for me, but as you pointed it seems there is a possibility for something to be wrong with the ECR integration.

At least, this flow of Porter is working as expected -> build / publish / archive / install from archive.

If I can provide any help, just let me know.
________________________________

**Comment by carolynvs** [comment]
I think this is a discrepancy between how GHCR/DockerHub/ACR display untagged artifacts and ECR. Porter (specifically cnab-to-oci) _does_ push multiple artifacts into the bundle repository, one for the installer image, and also for any referenced images.

When you publish a bundle we do the following:
* push the installer image, e.g. docker.io/mybundle-installer:v1.0.0. This copy isn't actually used by the bundle, we push it just to calculate the repo digest
* push the installer image and referenced images to the destination repository UNTAGGED, e.g. docker.io/mybundle:sha256:abc123
* rewrite the bundle to reference repository digests for the pushed images (repo digests cannot be calculated client side)
* create a relocation mapping that maps from the original image locations to the new location inside the bundle repository, e.g. docker.io/mybundle-installer:v1.0.0 -> docker.io/mybundle:sha256:abc123
* push the bundle manifest to the destination repository, e.g. docker.io/mybundle:v1.0.0

This ensures that when you work with a bundle, as long as you have access to the bundle repository you also have access to every single docker image used by the bundle.

Here's the documentation for what cnab-to-oci is doing https://porter.sh/distribute-bundles/#image-references-after-publishing

Based on that, I believe the untagged artifacts you see are the relocated images inside the bundle repository.

**Comment by jaudiger** [comment]
It seems that it's the case since I can't delete both untagged images in the bundle repository. I think I can't delete relocated images without deleting the tagged ones.

Thanks, @carolynvs for the clarification. I'll close this issue!
