### ISSUE TITLE
Design: preflight as a custom action

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#167]
Before installing a bundle, it's often helpful to evaluate the bundle first against the destination environment and identify problems before the bundle is executed. That way it's not half installed when you get an error that could have been identified up front.

Porter could support a custom action `preflight` that is run before `install` (or maybe it needs to be explicit? we need to figure that out). Any mixins that support preflight would do their best to identify problems and report them back. Mixins that do not support that custom action would be skipped.

**Comment by carolynvs** [comment]
This is now in the cnab spec as a recommended custom action `io.cnab.dry-run`.

https://github.com/deislabs/cnab-spec/blob/master/805-well-known-custom-actions.md

**Comment by carolynvs** [comment]
I take that back, dry-run is for showing what would happen if the bundle was executed. It's not the same as performing checks before install.

**Comment by RichiCoder1** [comment]
If I'm understanding this, this would be great to allow support for things like `terraform plan` and `helm --dry-run` to do what-ifs in CI (if that makes sense?)

**Comment by carolynvs** [comment]
I left out a bit of context in the OP so let me fill in a bit. 😀 I don't believe anything is stopping someone from making a [custom action](https://porter.sh/author-bundles/#custom-actions) right now that does these things. They could then execute it like this `porter invoke --action dry-run`. If you run into trouble doing that, let us know.

This issue was based on feedback from people that perhaps mixins could help do some checks before install executes to avoid things either stalling out halfwaythrough, or erroring with weird messages when we can check up-front for things and give better information on if the target env is OK to have install run. Mixins that supported this well-defined custom action would be automatically called by porter, without the bundle author needing to do extra work, and the mixin would check various conditions to make sure that install is OK to run. Then if that passed, porter would continue on to install.

For example, the helm mixin could verify that it has connectivity with the cluster.

We haven't moved forward with it mostly because it is very specific to people's own pre-conditions and having people manually invoke a custom action seems to work well. We've kept this open to collect feedback but perhaps this should be closed since there is a suitable way to achieve this and we haven't gotten any scenarios that would require this functionality.
