### ISSUE TITLE
Main content scrolls with menu items

### ISSUE THREAD

**Issue by thisisommore** [getporter/porter#1682]
## Describe the bug
Main content scrolls with menu items which makes up bad user experience for browsing documentation

## To Reproduce
1. Visit https://porter.sh/ on mobile device
2. Click on any item like quick start
3. Click menu and scroll
4. See scrolling issue

## Expected behavior
Only menu should scroll

## Porter Command and Output
https://user-images.githubusercontent.com/51229945/126891669-275f151e-4eb6-490d-a835-9b51cc47feb9.mp4

**Comment by DARK-art108** [comment]
Thanks for bringing in our concern would you like to work on this fix @thisisommore, would love to see the end results!

**Comment by thisisommore** [comment]
> Thanks for bringing in our concern would you like to work on this fix @thisisommore, would love to see the end results!

Yes, I would like to work on this.

**Comment by carolynvs** [comment]
Agreed! This has always bothered me and I'd love to see it fixed. 👍
