### ISSUE TITLE
Don't print commands in install script

### ISSUE THREAD

**Issue by thisisommore** [getporter/porter#1687]
Its been while since x option was added to print logs in install script.
https://github.com/getporter/porter/blob/05332860d3ad92a05d30f740165e7609106c6c4e/scripts/install/install-linux.sh#L2
Added in https://github.com/getporter/porter/commit/6aed4097d815105f6662e692c8cc01cd6604720b
The option really helps for logging in development but IMO it isn't ideal in production.
For e.g. when normal user tries to install it,
![image](https://user-images.githubusercontent.com/51229945/126929614-74249694-4426-4859-99a3-271eb8dc4649.png)

By removing -x it all looks clean
![image](https://user-images.githubusercontent.com/51229945/126929494-b2d6adc6-5eae-4d71-9173-d6826bfd3787.png)

**Comment by carolynvs** [comment]
Agreed! I added that when we were having trouble with our CDN and now that things have settled down, it isn't necessary anymore.
