### ISSUE TITLE
Introduce copy button for docs

### ISSUE THREAD

**Issue by thisisommore** [getporter/porter#1688]
**Is your feature request related to a problem? Please describe.**
Users need to manually select and copy the commands on docs

**Describe the solution you'd like**
It will be great if they have copy button near commands, for e.g. what github does
``` python3
 print("Hover to see copy button at right")
```
**Describe alternatives you've considered**
We could also copy the command on single click, reference this [codepen](https://codepen.io/ommroe/full/MWmrEvR)

**Comment by DARK-art108** [comment]
Yes, this will be helpful to everyone having a copy button will be helpful if have this in our docs at the right side of the end of each command!

**Comment by thisisommore** [comment]
Can I take this one 😀

**Comment by carolynvs** [comment]
@thisisommore Sure!
