### ISSUE TITLE
Add --all-namespaces flag

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1709]
On v1, you can specify --namespace="*" and that indicates that porter should list across all namespaces. Since bash treats * funny (you have to wrap it in quotes), this is awkward for people who are not used to this. Plus it's not as discoverable as a dedicated flag. I like keeping the * support around because it makes scripting more straightforward though.

This should be changed on v1, but can be shipped after v1.

**Comment by thisisommore** [comment]
Yes, that new flag will be useful.
