### ISSUE TITLE
Add completion command

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1757]
The CLI framework that we use, github.com/spf13/cobra, has great support for command completion. This allows the user to do things like type `porter shTAB` and their shell will complete the command to `porter show`. It can even autocomplete names of installations, credentials, etc.

Here's is a tutorial that explains how to add completion:
https://jmtirado.net/shell-completion-with-cobra-and-go/

and here is the completion documentation:
https://github.com/spf13/cobra/blob/master/shell_completions.md

It would be great if we can add completion, not just for our command but also for the names of installations, credentials, parameters, and even for flags so when you type in `porter install -c TAB` it can fill in the name of the credential set being specified.

If someone wants to just implement the first part, standard cobra completion without querying porter for additional completion values, that would be great. Doing it in two parts would probably be a good first step anyway.

The command should look like this, and be defined in main.go as a "meta" command. See the schema command for an example.

```
porter completion [bash|zsh|powershell|etc]
```

For the test, we just need to call the command and ensure that it completes without error. It doesn't require extensive testing since it's just exposing functionality from cobra.

**Comment by nathan-415** [comment]
I would like to work on this. Thanks.

**Comment by carolynvs** [comment]
I can't assign it to you (quirk of GitHub) but yes, it's all yours! 👍

**Comment by mikebarkas** [comment]
I am moving this ticket forward.

I created the completion command, test, and documentation for the website.

I implemented the standard Cobra completion for the Porter commands. Dynamic completions can be done in a future ticket.
