### ISSUE TITLE
Rename Dockerfile.tmpl to template.Dockerfile

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1771]
The generated dockerfile template, Dockerfile.tmpl, doesn't get syntax highlighting in any IDE because they all go off of the file extension, which is expected to be `Dockerfile`. We should change the template generated by `porter create` to use that as the extension by changing the generated file to `template.Dockerfile` or something along those lines.

* Change the template used by porter create
  * https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/templates/templates/create/Dockerfile.tmpl  
  * https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/templates/templates.go#L49
  * https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/porter/create.go#L30
  * https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/templates/templates/create/porter.yaml#L14
* Fix existing tests
* Update the documentation for the custom dockerfile
  * https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/docs/content/custom-dockerfile.md
  * https://github.com/getporter/porter/blob/784d61cf283bbd5b9c05a42ea718d3d042803305/pkg/templates/templates/create/README.md

Do not change any existing bundles inside the porter repository that already use Dockerfile.tmpl, they can stay as-is. We just want new bundles going forward to use a different name.

This change should be made on the release/v1 branch.

**Comment by astroparam** [comment]
@carolynvs I want to work on this.
Should we finalize filename to `template.Dockerfile`.

**Comment by carolynvs** [comment]
Great! Yes, I think template.Dockerfile will be recognized by editors and give people syntax highlighting.

**Comment by astroparam** [comment]
I forgot to link this issue in pull request. This issue should be closed now.
