### ISSUE TITLE
Possible to bump the x/sys dependency?

### ISSUE THREAD

**Issue by vdice** [getporter/porter#1820]
Can the [x/sys](https://github.com/getporter/porter/blob/main/go.mod#L25) dependency be bumped and/or its version override removed?

On my machine (MacOS/darwin x86_64) running Go 1.17.3, when I attempt to build porter from the `main` branch, I appear to encounter the issue described in https://github.com/golang/go/issues/46763.

Sample output:

```
$ make build
GO111MODULE=on go mod tidy
GO111MODULE=on go generate ./...
go run mage.go -v BuildAll get.porter.sh/porter porter bin
Running target: BuildAll
exec: /usr/bin/git git describe --tags --match=v*
exec: /usr/bin/git git rev-parse --short HEAD
exec: /usr/bin/git git describe --tags --match=v* --exact
exec: /usr/bin/git git for-each-ref --contains HEAD --format=%(refname)
Tagged Release: false
Permalink: canary
Version: v0.38.7-8-g9087eb3f
Commit: 9087eb3f
exec: /usr/local/go/bin/go go build -ldflags -w -X get.porter.sh/porter/pkg.Version=v0.38.7-8-g9087eb3f -X get.porter.sh/porter/pkg.Commit=9087eb3f -o bin/runtimes/porter-runtime ./cmd/porter
exec: /usr/local/go/bin/go go build -ldflags -w -X get.porter.sh/porter/pkg.Version=v0.38.7-8-g9087eb3f -X get.porter.sh/porter/pkg.Commit=9087eb3f -o bin/porter ./cmd/porter
GO111MODULE=on go run --tags=docs ./cmd/porter docs
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20375c9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20375c9e
stack: frame={sp:0x7ffeefbff1a8, fp:0x7ffeefbff1f8} stack=[0x7ffeefb80248,0x7ffeefbff2b0)
0x00007ffeefbff0a8:  0x01007ffeefbff0c8  0x0000000000000004
0x00007ffeefbff0b8:  0x000000000000001f  0x00007fff20375c9e
0x00007ffeefbff0c8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff0d8:  0x0000000004035591 <runtime.throw+0x0000000000000071>  0x00007ffeefbff178
0x00007ffeefbff0e8:  0x000000000569eea0  0x00007ffeefbff130
0x00007ffeefbff0f8:  0x0000000004035848 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000067c6fe0
0x00007ffeefbff108:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff118:  0x00007ffeefbff178  0x0000000004035591 <runtime.throw+0x0000000000000071>
<continues>
```

When I upgrade the dependency to a recent version, or remove the pinned version override, building succeeds.  However, I imagine the version was pinned for a reason.  Wondering if it would be feasible to revisit this?

**Comment by carolynvs** [comment]
Hey we both ran into the same problem yesterday! Check out #1821 which also has a new pin for x/sys

**Comment by carolynvs** [comment]
Oh drat, the version of moby that we are using isn't compatible with newer versions of x/sys on Windows that are compatible with go 1.17. I've backed my go.mod change out of that PR and will open a new one that attempts to bump our docker dep to something from this century.

**Comment by vdice** [comment]
Thank you @carolynvs !

**Comment by carolynvs** [comment]
We can't support go 1.17 for main without making a custom branch with some cherry-picked changes. Otherwise we would introduce changes from the latest cnab-go (which supports go 1.17) into main that don't belong.

I'm going to close this and we will just need to continue to rely on tricks like `brew unlink go && brew link go@1.16` to workaround the gap.
