### ISSUE TITLE
Template variable bundle.invocationImage is incorrect

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1824]
## Describe the bug
The bundle.invocationImage template value that is injected into the bundle at runtime is incorrect. It should reflect the final resolved invocation image, but it is the value built into the bundle at build time.

So if you publish it to a different location, it isn't the right value. Other problems:

* it doesn't take into account relocation mapping files. For example, really for any published bundle the invocation image is an artifact _inside_ the bundle repository. It's always getporter/mybundle:sha256:abc123, and never `getporter/mybundle-installer:v0.1.1`.
* It should use a digest instead of a tag.

## To Reproduce
1. Create a bundle
2. Echo `{{ bundle.invocationImage}}` from the porter.yaml during install
3. Build the bundle and publish it to a local registry.
4. Run the bundle from the published location.

## Expected behavior
The same image that is being executed by porter should be printed. Instead it prints the value built into the bundle at buildtime.

## Version
v0.38.7 and v1.0.0-alpha.5

**Comment by carolynvs** [comment]
I guess the question is do we want to deprecate this template variable (like it's documented), or do we want to actually provide the right value?

**Comment by bherw** [comment]
The impression I got from reading various sources (sorry if I'm misremembering; I can't find them now) was that the reason for this deprecation was twofold:
- the invocationImage name should no longer be set in the porter.yaml, but rather should be automatically determined
- the name "installer" is now preferred as it's clearer than "invocationImage"

If getting the installer image is useful for some reason and the invocationImage is deprecated as planned (I would currently like to reuse it; albeit for a workaround), then maybe a new template variable `bundle.installerImage` could be introduced, which uses the correct relocated image.

**Comment by carolynvs** [comment]
Thanks that's a great suggestion. 

Here's how I think we can do this in a way that works with the CNAB spec. The porter runtime (RuntimeManifest) will read in the bundle.json and get the invocationImage. Then look up the relocated invocation image from the relocation mapping file, and add that as a template variable `bundle.installerImage`.

Doing it this way would be compatible with the CNAB spec and not require changes to our cnab provider.
