### ISSUE TITLE
invalid media type for bundle manifest - Docker Hub

### ISSUE THREAD

**Issue by christianrowlands** [getporter/porter#1827]
I am trying to execute a porter bundle container from (and into) an Azure Container Instance, and am running into the following error:

```
2021/11/12 15:20:05 /usr/local/bin/porter install aks -d azure --tag chesapeaketechnology/porter-data-science-installer:v0.1.0 --cred /tmp/cnabarmdriver494119253/aks-creds.yaml --param-file /tmp/cnabarmdriver345722544/aks-params.txt
Error: unable to pull bundle before installation: unable to pull bundle chesapeaketechnology/porter-data-science-installer:v0.1.0: unable to pull remote bundle: invalid media type "application/vnd.docker.distribution.manifest.v2+json" for bundle manifest
2021/11/12 15:20:06 porter command failed with exit status 1
```

In searching for the error message, I found this [GitHub issue](https://github.com/getporter/porter/issues/1332). The end result of that issue was that GCR was no longer supported. However, I am trying to use Docker Hub and [this page](https://porter.sh/compatible-registries/) indicates it is supported. Has anyone else seen this issue? Is there a problem with the way I am building the container?

[This is the porter container](https://hub.docker.com/r/chesapeaketechnology/porter-data-science-installer) I am trying to execute.

In addition to executing it via the cnabarmdriver, I tried to execute the container locally and ran into the same error.

**Comment by carolynvs** [comment]
Sorry for the poor error message. You accidenally passed the wrong bundle reference to Porter's --tag flag. It should be the bundle reference, and not the installer docker image (they are two different things).

To fix the command, remove the "-installer" suffix from the value passed to the tag flag:
```
porter install --tag chesapeaketechnology/porter-data-science:v0.1.0
```

**Comment by christianrowlands** [comment]
Thank you for the quick response!

I tried changing the --tag flag to the one you specified (dropped the `-installer` portion) and I get a new error indicating the image could not be found...

```porter install aks --tag chesapeaketechnology/porter-data-science:v0.1.0                                
Flag --tag has been deprecated, use --reference to declare a full bundle reference
Error: unable to pull bundle before installation: unable to pull bundle chesapeaketechnology/porter-data-science:v0.1.0: unable to pull remote bundle: docker.io/chesapeaketechnology/porter-data-science:v0.1.0: not found```

When I switch to using the --reference flag as specified in the deprecated message I get the same results.

The image I published to Docker Hub is [this one](https://hub.docker.com/r/chesapeaketechnology/porter-data-science-installer). Did I name it wrong or maybe package it wrong (I just used the `porter build` command).

Thank you for the help!

**Comment by carolynvs** [comment]
I just checked Docker Hub for the bundle you mentioned and it looks like there may have been an error when you published the bundle? https://hub.docker.com/r/chesapeaketechnology/porter-data-science returns a 404

Can you try to publish your bundle again with the `porter publish` command, and then check that page to see if it made it okay?

**Comment by christianrowlands** [comment]
Oh wow, that was my problem 🤦 . I used `docker push` instead of `porter publish`.

I really appreciate your help! I was banging my head against a wall trying to figure this out.
