### ISSUE TITLE
Heading links in the docs are missing

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1845]
## Describe the bug
The website used to display a link symbol next to documentation headings with an anchor link to the current heading. They aren't displaying anymore though, so people can't easily link to a heading within a page.

## To Reproduce
Go to https://porter.sh/install, hover over a heading. Notice that an icon doesn't pop up next to it.

## Expected behavior
A link (🔗) icon should pop up next to the heading and when you click on it, change the URL to jump directly to that heading.

**Comment by mikebarkas** [comment]
I looked into this issue and found:

The Javascript is adding `<i class="fa fa-link">` properly (this is needed for `::before` CSS to show the link icon)
The issue appears to be there is no CSS to capture the `h1` hover.

I added the `h1:hover` to the CSS and the anchor link now functions, **but** the heading (h1 and h2) are hidden under the top menu bar.
![header-hidden](https://user-images.githubusercontent.com/6330126/148144892-cb5830e0-ea88-43c0-85a2-a7732b812126.png)

I added the `scroll-margin-top` CSS property to the H1 and H2
Now the anchor destination links display properly.

### H1 example
![h1-displayed](https://user-images.githubusercontent.com/6330126/148145288-520aa9e2-c170-413e-a10f-d88aad27c120.png)


### H2 example
![h2-displayed](https://user-images.githubusercontent.com/6330126/148145305-bdd56061-33c0-46d1-b12f-8c5cf966a16f.png)
