### ISSUE TITLE
Improve display of uninstalled installations

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1853]
The listing of installations right now is really "claims" centric. We display the information that was originally available when Porter was first implemented with just claims. It's hard to see what is currently installed though.

```console
$ porter list
NAMESPACE   NAME             CREATED         MODIFIED        LAST ACTION   LAST STATUS
dev         desired-state1   7 seconds ago   7 seconds ago
dev         desired-state    4 minutes ago   4 minutes ago   uninstall     succeeded
dev         porter-hello     3 hours ago     3 hours ago     uninstall     succeeded
```

Here is a suggestion for how we can use all the new status data we store on the installation documents to improve the clarity of this command's output.

```console
NAMESPACE   NAME             VERSION    STATE           STATUS      MODIFIED
dev         something        1.2.3      installed       failed      7 seconds ago
dev         wordpress        1.2.0      defined         installing  4 minutes ago
dev         porter-hello     0.1.1      uninstalled     success     3 hours ago
```

States
* defined but not installed yet
* installed, porter is managing it
* uninstalled, porter is done with it

Status
* success
* failed
* installing
* upgrading
* running (a custom action)
* uninstalling

**Comment by carolynvs** [comment]
Eventually it will be useful to filter the results based on the state/status of the installation too:

* Show installed bundles
* Show failed bundles
* Show bundles currently executing

**Comment by squillace** [comment]
Removing/uninstalling is missing in status.

**Comment by carolynvs** [comment]
Thanks, I've added uninstalling to the OP.

**Comment by carolynvs** [comment]
Along the same lines, how can we show an installation in the `porter installation show` output to make it clear it's uninstalled?

Here's the current output regardless of if it's been uninstalled or not.
```
Name: mywordpress
Namespace: dev
Created: 2020-04-18
Modified: 2020-04-18

Bundle:
  Repository: getporter/wordpress
  Version: 0.1.0

Labels:
  io.cnab/app: wordpress
  io.cnab/appVersion: v1.2.3

Parameters:
---------------------------------
  Name      Type     Value       
---------------------------------
  logLevel  integer  3           
  token     unknown  top-secret  

Parameter Sets:
  - dev-env

Status:
  Reference: getporter/wordpress:v0.1.0
  Version: 0.1.0
  Last Action: upgrade
  Status: succeeded
  Digest: sha256:88d68ef0bdb9cedc6da3a8e341a33e5d2f8bb19d0cf7ec3f1060d3f9eb73cae9
```

As part of #1851, the installation document will have an uninstalled flag that indicates if the installation shouldn't be installed anymore. We will also have the installed and uninstalled timestamps on status available.

What show should return immediately after someone flips uninstalled = true, before it's been processed.
```
Name: mywordpress
Namespace: dev
Created: 2020-04-18
Modified: 2020-04-18
Uninstalled: Pending
```

After it's been uninstalled we can provide a timestamp
```
Name: mywordpress
Namespace: dev
Created: 2020-04-18
Modified: 2020-04-18
Uninstalled: 2022-01-23
```

**Comment by joshuabezaleel** [comment]
Will this be against `v1.0.0` or since there's no v1 tag on this issue means that the base branch to merge should stay at main?

**Comment by carolynvs** [comment]
Good question! All new features (and complex bug fixes) should be done against the release/v1 branch. The main branch is only getting some bug fixes so that we can keep it stable.

**Comment by carolynvs** [comment]
I am not sure we have settled on the design for this one yet. Let's hold off on starting on it until we are sure we have the output correct. I wouldn't want anyone to waste time if we are still tweaking it!

**Comment by carolynvs** [comment]
@joshuabezaleel Okay! The design from the original post has been approved so if you are interested in doing this issue, go for it! 👍

**Comment by joshuabezaleel** [comment]
@carolynvs this seems exciting to work on, would love to, if I may! 😄

**Comment by carolynvs** [comment]
Excellent! I was hoping that you would be interested. If you need help figuring out where we can get the data for a particular column, just let me know!

**Comment by joshuabezaleel** [comment]
Hi @carolynvs , I want to make sure whether I get the assumption of how should I get the data of states and status right before I am going to implement it which I presume I can refer from the data of [`InstallationStatus` struct](https://github.com/getporter/porter/blob/release/v1/pkg/storage/installation.go#L177-L213) and these various constants defining available action and status on [aliases.go](https://github.com/getporter/porter/blob/release/v1/pkg/cnab/aliases.go#L12-L26) and in which I will make another function and put it inside the [`NewDisplayInstallation`](https://github.com/getporter/porter/blob/release/v1/pkg/porter/list.go#L109-L127) function to organize the installation data. 

**STATES**
- defined but not installed yet: `InstallationStatus.Installed == nil` and `InstallationStatus.Uninstalled == nil`
- installed, porter is managing it: `InstallationStatus.Installed != nil`
- uninstalled, porter is done with it: [`Installation.Uninstalled == true`](https://github.com/getporter/porter/blob/release/v1/pkg/storage/installation.go#L35) and `InstallationStatus.Uninstalled != nil`

**STATUS**
- success: `InstallationStatus.ResultStatus == StatusSucceeded`
- failed: `InstallationStatus.ResultStatus == StatusFailed`
- installing: `InstallationStatus.ResultStatus == StatusRunning` and `InstallationStatus.Action == ActionInstall`
- upgrading: `InstallationStatus.ResultStatus == StatusRunning` and `InstallationStatus.Action == `ActionUpgrade`
- running {custom action name}: `InstallationStatus.ResultStatus == StatusRunning` and the name of the custom `InstallationStatus.Action`
- uninstalling: `InstallationStatus.ResultStatus == StatusRunning` and `InstallationStatus.Action == `ActionUninstall`

**VERSION**
`InstallationStatus.BundleVersion`

Some remaining followups are:
- Are the [`StatusCanceled`](https://github.com/getporter/porter/blob/release/v1/pkg/cnab/aliases.go#L19) and [`StatusPending`](https://github.com/getporter/porter/blob/release/v1/pkg/cnab/aliases.go#L22) intentionally being left out? 
- Will it be okay if I make a separate issue and separate PR for this particular issue of showing uninstalled timestamp on show command? https://github.com/getporter/porter/issues/1853#issuecomment-1020474700

Looking forward to hearing from you and thank you lots in advance! 😄

**Comment by joshuabezaleel** [comment]
@carolynvs I was trying to get the `Uninstalled` property for the `show` command when I realized that after uninstalling a bundle, the `Uninstalled` boolean flag that you mentioned here has a value of `false` even though that the `Uninstalled` timestamp on the `InstallationStatus` already has a timestamp value/not null, which makes the `installation.IsUninstalled` to return `true` since it only checks the `Uninstalled` timestamp.
https://github.com/getporter/porter/issues/1853#issuecomment-1020474700
![image](https://user-images.githubusercontent.com/7043511/175469713-c4ae5606-bcd7-435f-8715-9be6fe138fcf.png)

I tried to access the `Uninstalled` boolean flag since I want to get the `Uninstalled: Pending` state on the `installation show`. Is this expected? Since I assume this might be a little bit confusing for people where they found that `Uninstalled` can be `true` but has a not-nil timestamp value at the same time. Haven't dig deeper into this yet since I want to confirm first 😄 
![image](https://user-images.githubusercontent.com/7043511/175469545-73683452-3a49-41b0-9e40-95e95b71bd40.png)

**Comment by carolynvs** [comment]
The Installation struct has a field `Uninstalled` that does **not** indicate whether or not it has been uninstalled, but that the user has requested that it be uninstalled. It supports soft deletes in the Porter Operator so that people can uninstall a bundle without having the installation CRD be deleted as well.

I didn't see you using that field in this PR though, so I'm not sure if an explanation is enough or there is broken code that should stop using that field?
