### ISSUE TITLE
create should validate the build driver

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1867]
## Describe the bug
I accidentally put in a bad build driver into the config file and `porter create` just used it without validating it.

## To Reproduce
1. Edit ~/.porter/config.toml and set your build driver to something invalid
    ```toml
    build-driver = "oops"
    ```
1. Run `porter create` to make a new bundle

## Expected behavior
It should fail with a reasonable message about the build driver being invalid. Instead it tried to use the value to lookup the dockerfile template and fails there with messages that won't be helpful for fixing the problem.

## Porter Command and Output
```console
$ porter create
creating porter configuration in the current directory
Error: open templates/create/template.oops.Dockerfile: file does not exist
open templates/create/template.oops.Dockerfile: file does not exist
```

## Version
v1.0.0-alpha.7

**Comment by kichristensen** [comment]
Cannot be reproduced in v1.0.17
