### ISSUE TITLE
How we push invocation images is confusing

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1869]
Right now when we publish a bundle, it creates two copies of the invocation image:

* getporter/porter-hello-installer:v0.1.1
* getporter/porter-hello@sha256:somedigest

The first one should not be used, only the second one embedded in the bundle repository is the correct image. The first is an awkward side effect that confuses people and causes extra security configuration on some registries like Amazon's because they have to allow for access to two different repositories.

Seems like the OCI distribution spec supports [deleting tags](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#deleting-tags). What if we pushed the invocation image directly to a tag in the bundle repository (such as getporter/porter-hello:installer-IMAGEID), retrieved the digest, and then after we publish the bundle, remove the tag.

That way we don't get dangling images or tags that people inevitably ask questions about.

@vdice What do you think?

**Comment by vdice** [comment]
👍 I'm in favor of the simplification (unification into one repository, helping the AWS case and perhaps others) and the ability to clean up during publishing.

**Comment by jasmdk** [comment]
Then what about when you publish a bundle from an archive, then you get even more very confusing repositories which are just temporary, but never removed. They may even conflict as different bundles risk publish to the same tag if they contain images with the same alias.
```
porter archive whalegap.tgz --reference getporter/whalegap:v0.1.1
porter publish --archive whalegap.tgz --reference <myregistry>/library/whalegap:v0.1.1
```
This produces 3 different repositories:
- library/whalegap
- library/whalegap-installer
- library/**whalesayd**

**Comment by carolynvs** [comment]
@jasmdk Thanks for bringing that up as well. The plan would be to not "litter" extra images for the invocation image and referenced images as well. So in the whalegap example, porter would push whalegap-installer and whalesayd into the target bundle registry under a temporary tag as well.

**Comment by carolynvs** [comment]
@vdice I'll look into how much trouble it would be to make this happen with changes in porter and cnab-to-oci. Right now I'm not sure if this is an ugly big effort or some naming changes and a cleanup after we publish.

**Comment by VinozzZ** [comment]
After some investigation, I found that the tag deletion spec is still pretty new. Not many registry client has this new feature implemented. For now, I implemented the randomized tag for invocation image. Maybe we can wait to implement the deletion until registry client libraries to catch up with the spec
