### ISSUE TITLE
Explain command doesn't work for non-porter bundles

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1892]
The explain command should work for all valid CNAB bundles, not just those made by porter. We should detect if it's not a porter bundle and then print a more limited set of data that doesn't include mixins and other porter specific information.

```console
$ porter explain -r getporter/porter.mixins.exec:v1.0.0-alpha.1
Name: exec
Description: Run arbitrary commands and scripts
Version: 1.0.0-alpha.1

Parameters:
------------------------------------------------------------------------------------------------------
  Name                        Description                     Type    Default  Required  Applies To
------------------------------------------------------------------------------------------------------
  porter-mixin-configuration  Global mixin configuration      object  <nil>    false     All Actions
                              snippet from porter.yaml.
                              Porter internal parameter that
                              should not be set manually.

Actions:
--------------------------------------------------------------------------------------
  Name              Description                     Modifies Installation  Stateless
--------------------------------------------------------------------------------------
  sh.porter.invoke  Handles the porter invoke       true                   true
                    command

This bundle uses the following tools: .

To install this bundle run the following command, passing --param KEY=VALUE for any parameters you want to customize:
porter install --reference getporter/porter.mixins.exec:v1.0.0-alpha.1
```

The example above is the explain output for a non-porter bundle. We shouldn't list the mixins since that's porter specific. Since len(mixins) is 0, it should be skipped.

```
This bundle uses the following tools: .
```

**Comment by joshuabezaleel** [comment]
Permission to confirm. Does this mean that this issue specifically addressing (1) mixins as the only porter specific or do we have any other properties other than mixins as the porter specific information in terms of a bundle and (2) does this only applies to the `this bundle uses the following tools` information on the `porter explain` output or are we considering other information on the `porter explain` output as well? 

Thank you!

**Comment by carolynvs** [comment]
I think it's just the list of mixins that are porter-specific and are not a feature in CNAB. So once we change explain to not try to print a list of mixins for a bundle that doesn't have any defined, the command should work with any bundle, even if Porter didn't make it.

So for this bundle that I made (without porter so it doens't have mixins), should have explain output that looks like this:

```console
$ porter explain -r getporter/porter.mixins.exec:v1.0.0-alpha.1
Name: exec
Description: Run arbitrary commands and scripts
Version: 1.0.0-alpha.1

Parameters:
------------------------------------------------------------------------------------------------------
  Name                        Description                     Type    Default  Required  Applies To
------------------------------------------------------------------------------------------------------
  porter-mixin-configuration  Global mixin configuration      object  <nil>    false     All Actions
                              snippet from porter.yaml.
                              Porter internal parameter that
                              should not be set manually.

Actions:
--------------------------------------------------------------------------------------
  Name              Description                     Modifies Installation  Stateless
--------------------------------------------------------------------------------------
  sh.porter.invoke  Handles the porter invoke       true                   true
                    command

To install this bundle run the following command, passing --param KEY=VALUE for any parameters you want to customize:
porter install --reference getporter/porter.mixins.exec:v1.0.0-alpha.1
```

**Comment by joshuabezaleel** [comment]
I am trying to identify what differs non-Porter bundle from a Porter specific bundle by trying to print the `bundleRef.Definition` on this particular line. https://github.com/getporter/porter/blob/release/v1/pkg/porter/explain.go#L163

Will it be safe to deduce that a Porter bundle is one that got `porter-state` defined in it? The bundle that I am printing is the `porter-hello` from the `porter bundle create` command and the print result is as follows. I am thinking of retrieving it from either the `Parameters` or `Definitions` map.

> bundleRef= {Bundle:{SchemaVersion:v1.0.0 Name:porter-hello Version:0.1.0 Description:An example Porter configuration Keywords:[] Maintainers:[] InvocationImages:[{BaseImage:{ImageType:docker Image:localhost:5000/porter-hello:37da5464f8517662657529ad34851db9 Digest: Size:0 Labels:map[] MediaType:}}] Images:map[] Actions:map[] Parameters:map[porter-debug:{Definition:porter-debug-parameter ApplyTo:[] Description:Print debug information from Porter when executing the bundle Destination:0xc000510400 Required:false} porter-state:{Definition:porter-state ApplyTo:[] Description:Supports persisting state for bundles. Porter internal parameter that should not be set manually. Destination:0xc000510420 Required:false}] Credentials:map[] Outputs:map[porter-state:{Definition:porter-state ApplyTo:[] Description:Supports persisting state for bundles. Porter internal parameter that should not be set manually. Path:/cnab/app/outputs/porter-state}] Definitions:map[porter-debug-parameter:0xc00049bb00 porter-state:0xc00049bd40] License: RequiredExtensions:[sh.porter.file-parameters io.cnab.parameter-sources] Labels:map[] Custom:map[io.cnab.parameter-sources:map[porter-state:map[priority:[output] sources:map[output:map[name:porter-state]]]] sh.porter:map[commit:4f1036b2 manifest:IyBUaGlzIGlzIHRoZSBjb25maWd1cmF0aW9uIGZvciBQb3J0ZXIKIyBZb3UgbXVzdCBkZWZpbmUgc3RlcHMgZm9yIGVhY2ggYWN0aW9uLCBidXQgdGhlIHJlc3QgaXMgb3B0aW9uYWwKIyBTZWUgaHR0cHM6Ly9wb3J0ZXIuc2gvYXV0aG9yLWJ1bmRsZXMgZm9yIGRvY3VtZW50YXRpb24gb24gaG93IHRvIGNvbmZpZ3VyZSB5b3VyIGJ1bmRsZQojIFVuY29tbWVudCBvdXQgdGhlIHNlY3Rpb25zIGJlbG93IHRvIHRha2UgZnVsbCBhZHZhbnRhZ2Ugb2Ygd2hhdCBQb3J0ZXIgY2FuIGRvIQoKbmFtZTogcG9ydGVyLWhlbGxvCnZlcnNpb246IDAuMS4wCmRlc2NyaXB0aW9uOiAiQW4gZXhhbXBsZSBQb3J0ZXIgY29uZmlndXJhdGlvbiIKIyByZWdpc3RyeSB3aGVyZSB0aGUgYnVuZGxlIGlzIHB1Ymxpc2hlZCB0byBieSBkZWZhdWx0CnJlZ2lzdHJ5OiAibG9jYWxob3N0OjUwMDAiCgojIElmIHlvdSB3YW50IHRvIGN1c3RvbWl6ZSB0aGUgRG9ja2VyZmlsZSBpbiB1c2UsIHVuY29tbWVudCB0aGUgbGluZSBiZWxvdyBhbmQgdXBkYXRlIHRoZSByZWZlcmVuY2VkIGZpbGUuIAojIFNlZSBodHRwczovL3BvcnRlci5zaC9jdXN0b20tZG9ja2VyZmlsZS8KI2RvY2tlcmZpbGU6IHRlbXBsYXRlLkRvY2tlcmZpbGUKCm1peGluczoKICAtIGV4ZWMKCmluc3RhbGw6CiAgLSBleGVjOgogICAgICBkZXNjcmlwdGlvbjogIkluc3RhbGwgSGVsbG8gV29ybGQiCiAgICAgIGNvbW1hbmQ6IC4vaGVscGVycy5zaAogICAgICBhcmd1bWVudHM6CiAgICAgICAgLSBpbnN0YWxsCgp1cGdyYWRlOgogIC0gZXhlYzoKICAgICAgZGVzY3JpcHRpb246ICJXb3JsZCAyLjAiCiAgICAgIGNvbW1hbmQ6IC4vaGVscGVycy5zaAogICAgICBhcmd1bWVudHM6CiAgICAgICAgLSB1cGdyYWRlCgp1bmluc3RhbGw6CiAgLSBleGVjOgogICAgICBkZXNjcmlwdGlvbjogIlVuaW5zdGFsbCBIZWxsbyBXb3JsZCIKICAgICAgY29tbWFuZDogLi9oZWxwZXJzLnNoCiAgICAgIGFyZ3VtZW50czoKICAgICAgICAtIHVuaW5zdGFsbAoKIyBCZWxvdyBpcyBhbiBleGFtcGxlIG9mIGhvdyB0byBkZWZpbmUgY3JlZGVudGlhbHMKIyBTZWUgaHR0cHM6Ly9wb3J0ZXIuc2gvYXV0aG9yLWJ1bmRsZXMvI2NyZWRlbnRpYWxzCiNjcmVkZW50aWFsczoKIyAgLSBuYW1lOiBrdWJlY29uZmlnCiMgICAgcGF0aDogL3Jvb3QvLmt1YmUvY29uZmlnCiMgIC0gbmFtZTogdXNlcm5hbWUKIyAgICBlbnY6IFVTRVJOQU1FCgojIEJlbG93IGlzIGFuIGV4YW1wbGUgb2YgaG93IHRvIGRlZmluZSBwYXJhbWV0ZXJzCiMgU2VlIGh0dHBzOi8vcG9ydGVyLnNoL2F1dGhvci1idW5kbGVzLyNwYXJhbWV0ZXJzCiNwYXJhbWV0ZXJzOgojICAtIG5hbWU6IG15c3FsX3VzZXIKIyAgICB0eXBlOiBzdHJpbmcKIyAgICBkZWZhdWx0OiB3b3JkcHJlc3MKCiMgQmVsb3cgaXMgYW4gZXhhbXBsZSBvZiBob3cgdG8gZGVmaW5lIHN0YXRlIHZhcmlhYmxlcwojIGZvciB0aGUgdGVycmFmb3JtIG1peGluLiBUaGlzIGFsbG93cyB5b3UgdG8gdHJhY2sKIyB0ZXJyYWZvcm0gc3RhdGUgdXNpbmcgdGhlIGJ1bmRsZSBpbnN0ZWFkIG9mIGNvbmZpZ3VyaW5nCiMgYSByZW1vdGUgYmFja2VuZC4KIyBTZWUgaHR0cHM6Ly9wb3J0ZXIuc2gvYXV0aG9yLWJ1bmRsZXMvI3N0YXRlCiNzdGF0ZToKIyAgLSBuYW1lOiB0ZnN0YXRlCiMgICAgcGF0aDogdGVycmFmb3JtL3RlcnJhZm9ybS50ZnN0YXRlCiMgIC0gbmFtZTogdGZ2YXJzCiMgICAgcGF0aDogdGVycmFmb3JtL3RlcnJhZm9ybS50ZnZhcnMuanNvbgo= manifestDigest:002e7b428a5920c910e8042ec919ffb895ab7e5a1e4f811de1747f725d719184 mixins:map[exec:map[]] version:v1.0.0-alpha.8-47-g4f1036b2] sh.porter.file-parameters:map[]]}}

While this one is from the `getporter/porter.mixins.exec:v1.0.0-alpha.1`.

> bundleRef= {Bundle:{SchemaVersion: Name:exec Version:1.0.0-alpha.1 Description:Run arbitrary commands and scripts Keywords:[] Maintainers:[{Name:The Porter Authors Email: URL:}] InvocationImages:[{BaseImage:{ImageType:docker Image:getporter/porter.mixins.exec-mixin:v1.0.0-alpha.1@sha256:f9d3a21249bea9e05bebcd104c79fdfa12afa77e9252768be2583cc910027c5a Digest:sha256:f9d3a21249bea9e05bebcd104c79fdfa12afa77e9252768be2583cc910027c5a Size:1571 Labels:map[] MediaType:application/vnd.docker.distribution.manifest.v2+json}}] Images:map[] Actions:map[sh.porter.invoke:{Modifies:true Stateless:true Description:Handles the porter invoke command}] Parameters:map[porter-mixin-configuration:{Definition:porter-mixin-configuration-parameter ApplyTo:[] Description:Global mixin configuration snippet from porter.yaml. Porter internal parameter that should not be set manually. Destination:0xc0006828c0 Required:false}] Credentials:map[] Outputs:map[] Definitions:map[porter-mixin-configuration-parameter:0xc000305d40] License: RequiredExtensions:[] Labels:map[] Custom:map[sh.porter:map[customActions:map[sh.porter.invoke:map[actions:[*]]] labels:map[porter.sh/appName:bash] mixin:exec tags:[bash command script]]]}}

**Comment by carolynvs** [comment]
We have a helper function on pkg/cnab.ExtendedBundle, called IsPorterBundle that identifies if the bundle was made by porter. Under the hood, it is checking the custom section of the bundle.json for an entry named "sh.porter".

**Comment by joshuabezaleel** [comment]
@carolynvs If the solution was by using `pkg/cnab.ExtendedBundle`'s `IsPorterBundle` that checks custom section of the bundle.json of `sh.porter`, I think that particular function will still returns a value of `true` for the bundle `getporter/porter.mixins.exec:v1.0.0-alpha.1` (the one that you use for the issue's description) because it still satisfies the requirement of having `sh.porter` on the custom section (which was also shown on the second snippet of my comment [here](https://github.com/getporter/porter/issues/1892#issuecomment-1048567507)), so it will still try to print the list of mixins specifically the sentence of `This bundle uses the following tools: ...`.

![image](https://user-images.githubusercontent.com/7043511/166938683-fc73cd13-1732-4b72-920c-1e2193e20a3f.png)
![image](https://user-images.githubusercontent.com/7043511/166938786-8cf59105-4378-4f84-9662-f4ab0413e51c.png)

**Comment by carolynvs** [comment]
Good point! 🤦‍♀️ That bundle I published was an experiment (distributing mixins as bundles) and isn't a true "non-porter bundle". I using an existing porter bundle to make it which is why it has the custom section still.

Since it's really the listing of the mixins that is problemmatic here, how about we check if there are any mixins defined, and if there are none, don't print that sentence? So a non-porter bundle without a custom porter.sh section wouldn't print it and a weird new bundle that represents a mixin itself (still in the design phase) would have that section but still won't have a "mixins" subdocument.
