### ISSUE TITLE
external plugins Connect interface not called for 1.0.0-alpha.9

### ISSUE THREAD

**Issue by bdegeeter** [getporter/porter#1913]
## Describe the bug

In the process of updating the kubernetes-plugin for 1.0.0 `Connect` is required for meeting plugin interface requirements.  However, it's not being called via the pluggable interface.

## To Reproduce
The integration tests for kubernetest-plugin 1.0.0 update only pass if `Connect` is called explicitly in the `Resolve` function for the secret store.  (still a WIP)

https://github.com/bdegeeter/kubernetes-plugins/blob/61ad89acde321f8d21d8ab569c0242d7f018d0fd/pkg/kubernetes/secrets/store.go#L67

## Expected behavior

porter should run `Connect` and `Close` for the external plugin

## Version

v1.0.0-alpha.9

**Comment by carolynvs** [comment]
I'm sorry! There is a bug in the documentation https://release-v1.porter.sh/plugins/types/#secrets and for secrets you aren't supposed to implement the entire secrets.Store interface, just the protocol which is https://github.com/getporter/porter/blob/release/v1/pkg/secrets/plugins/secrets_protocol.go.

So your secret plugin would only implement a single function `Resolve` and if you need to execute initialization logic, it would be up to the plugin to keep track of if it has been initialized yet.

I'll get the documentation updated with the right interface. Sorry that sent you down the wrong path!
