### ISSUE TITLE
Document that GitLab is not supported

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1932]
On our [compatible registries](https://github.com/getporter/porter/blob/main/docs/content/compatible-registries.md) page, we should add an entry for GitLab now that we have verified that they are not supported. A PR for this should target the **main** branch.

The CONTRIBUTING.md file has an explanation for how to preview your changes to the website, or you can submit a pull request and use the Netlify deploy preview check to see what it looks like.

See our [Contributing Tutorial](https://porter.sh/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/main/CONTRIBUTING.md) for help getting started contributing to Porter.

**Comment by hrittikhere** [comment]
Hey @carolynvs 
Something like this would work? Do we need something extra? Please let me know/assign if that's the case and I can help with this 😄
![image](https://user-images.githubusercontent.com/67012359/169945423-39e32b1c-35fd-45ba-86e8-51e79695d7c6.png)

**Comment by carolynvs** [comment]
Yup, that's what it should look like!
