### ISSUE TITLE
`Porter explain` yield error on release/v1 branch

### ISSUE THREAD

**Issue by joshuabezaleel** [getporter/porter#1945]
## Describe the bug
`Porter explain` ran with a build from release/v1 yield error while it works with the v0.38 (`porter v0.38.7 (43a2b2ae)`) with the same bundle `getporter/porter-hello:v0.1.0`.

## To Reproduce
1. Clone the latest version from `release/v1` branch.
2. Run `make build`.
3. Use the binary to run `porter explain --reference getporter/porter-hello:v0.1.0`.

## Expected behavior
Output of the explain command will be shown like the `porter v0.38.7` does.

## Porter Command and Output
![image](https://user-images.githubusercontent.com/7043511/155849099-ee7636ad-d58e-4fb3-a872-06781ec932d9.png)
![image](https://user-images.githubusercontent.com/7043511/155849105-1c81e62b-8e14-468c-9dc8-029c3831badc.png)

## Version
porter v1.0.0-alpha.8-67-gecedc49b (ecedc49b)

**Comment by carolynvs** [comment]
@joshuabezaleel Can you try this with the most [recent tag](https://hub.docker.com/r/getporter/porter-hello/tags) for that bundle?  v0.1.1 supports porter v1, the original was written for the older version.

**Comment by joshuabezaleel** [comment]
Ah yes it works, now that explains. Would this be addressed in the future with this particular issue of #1566 for a better error message?

I will be closing the issue. Thank you lots Carolyn 🙂

**Comment by carolynvs** [comment]
I've been working on #1566 for a bit, and just opened a draft PR so people can see how far along the work is. I'll update that issue with a requirement that all commands that pull a bundle should check the schema version before trying to parse the manifest to avoid problems like this.

**Comment by joshuabezaleel** [comment]
That would be lovely. Thank you lots, Carolyn!
