### ISSUE TITLE
Use docsy for our docs theme

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1961]
Our current docs theme is a tweaked version of the helm2 doc website that I did my best to make work. It isn't great and there are existing themes out there that make some things a lot easier, like search and menus.

The docsy hugo theme just added support for hugo modules, so that it's easier to use. https://github.com/google/docsy/pull/871

It would be great to look into changing the theme over to this. I don't have a lot of guidance if someone wants to pick this up. We need the entire site (landing pages and docs) to look great and have at least the same functionality as today.

**Comment by kichristensen** [comment]
We currently use the theme Hextra
