### ISSUE TITLE
`porter installation apply` failed with array parameters

### ISSUE THREAD

**Issue by joshuabezaleel** [getporter/porter#1962]
## Describe the bug
`porter installation apply` command fails with array for `parameters` section. I use the [`whalesay` bundle](https://github.com/getporter/porter/tree/main/examples/docker) for this.

## To Reproduce
1. Copy the content of this `whalesay` bundle from this example repository to a `porter.yaml` file.
2. Run `porter installation apply`.
3. See error below.
```
Error: unable to parse porter.yaml as an installation document: yaml: unmarshal errors:
  line 10: cannot unmarshal !!seq into map[string]interface {}
unable to parse porter.yaml as an installation document: yaml: unmarshal errors:
  line 10: cannot unmarshal !!seq into map[string]interface {}
```

## Expected behavior
`porter installation apply` works like the usual `porter install` flow. 

## Porter Command and Output
`porter installation apply porter.yaml`

![image](https://user-images.githubusercontent.com/7043511/157654037-e93a6a7c-eb90-4315-94db-3d7a4daa29cc.png)

## Version
Copy the output of `porter version` below:

`porter v1.0.0-alpha.8-12-gb7debe30 (b7debe30)`

[e.g. porter v0.14.1-beta.2 (72dd5df)]

**Comment by carolynvs** [comment]
That's because the [file format for an installation document](https://release-v1.porter.sh/reference/file-formats/#installation ) uses a map for parameters.

```yaml
parameters:
  log-level: 11
```
