### ISSUE TITLE
Incomplete sentence on Tasks/End Users/Manage Installations v1.0.0 doc site

### ISSUE THREAD

**Issue by joshuabezaleel** [getporter/porter#2027]
## Describe the bug
Incomplete sentence on Tasks/End Users/Manage Installations v1.0.0 doc site: ([link](https://github.com/getporter/porter/blob/release/v1/docs/content/end-users/installations.md)) 
```
[Install a bundle using imperative commands with the](https://github.com/getporter/porter/blob/release/v1/quickstart)
```

![image](https://user-images.githubusercontent.com/7043511/164484414-8139abe1-da8d-4b19-9b74-71596ff825dc.png)

## To Reproduce
Go to https://release-v1.porter.sh/end-users/installations/ and go to `Next Steps` at the bottom of the page.

## Expected behavior
Complete sentence.

## Version
Doc site `v1.0.0`

**Comment by carolynvs** [comment]
That works just fine! 👍
