### ISSUE TITLE
Define an intermediate representation of a porter manifest

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#207]
Currently porter only consumes a yaml file, then converts that to a go struct, loads the dependencies, starts executing the bundles and then keeps an in-memory representation of the bundle as it executes.

Having the input representation tied so closely to the in-memory/live representation of the bundle makes it hard to make changes to the porter behavior going forward. It also limits the languages and extensibility of porter (see #173).

If we had an intermediate format that others could provide to porter, not necessarily the current yaml structure, then that would allow stuff like [moopo](https://github.com/jdolitsky/porter-moon-demo), or [lupo](https://github.com/jdolitsky/porter-moon-demo), or viper provided markup languages like toml, hcl, etc.

**Comment by carolynvs** [comment]
cc @jdolitsky

**Comment by jdolitsky** [comment]
wow so fast!

**Comment by carolynvs** [comment]
Your demo inspired me. 😍

**Comment by carolynvs** [comment]
Suggestion from @simongdavies

> Make sure that the templating (such as mustache/handlebars) doesn't get embedded into the runtime representation so that other tools can generate the intermediate form without having to muck(?) with the templating language too

**Comment by jdolitsky** [comment]
How might jsonschema help us with this?

**Comment by carolynvs** [comment]
> How might jsonschema help us with this?

I'm not sure if it would? Honestly I don't have a design yet in my head about what this would need to look like as a technical solution. What I do have are requirements coming in from a few sides:

* Feelings from myself and @jeremyrickard that working with our current representation which is just a single Go struct that yaml tags that we use both to load in the porter.yaml, and then keep a live representation of the manifest as we work through the bundle at runtime is getting awkward.
* Comments from @simongdavies about how the Azure ARM team has run into trouble with how they represented their data structures, and trying to convey lessons learned about having multiple representations of the manifest so that it's not all glommed into a single data structure.
* Your feedback on wanting to use something other than yaml to feed into into Porter, potentially talking to porter programmatically instead through the mechanisms made for the cli.

**Comment by carolynvs** [comment]
Decided to finally take this on as part of dependency evaluation. 💪

**Comment by carolynvs** [comment]
Closing since using a language other than YAML is no longer on our roadmap.
