### ISSUE TITLE
Add quote about EY's solution with Porter on our homepage

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2102]
> For one instance, it used to take 50 hours, let's say one and a half day, to provision one client instance. It required around like two or three people to work on the same job, and the process really complicated and requires a lot of knowledge, a deep knowledge about all the components and all the processes which are involved in this, and right now it's reduced up to three hours per one instance. Previously, we were able to do once in a time and right now we are able to provision multiple clients at the same time. 

Wojciech Laskowski
EY SharePoint/DevOps Engineering Lead

7:45 @ https://mybuild.microsoft.com/en-US/sessions/f32a7a49-badc-4596-8347-ca6608fbcb58

**Comment by joshuabezaleel** [comment]
Does this mean that we can add EY to [this ADOPTERS list](https://github.com/getporter/porter/blob/main/ADOPTERS.md)?
- https://github.com/getporter/porter/issues/1596
- https://github.com/getporter/porter/issues/1951

Will have to watch the recording today, that sounds exciting!

**Comment by carolynvs** [comment]
We can't proactively add companies to the list. I've asked someone at EY if they are willing to add to their name though.

**Comment by joshuabezaleel** [comment]
Ah so it should've been the representative of the company who adds the name to the list? Got it.

**Comment by carolynvs** [comment]
Ideally they add it themselves but otherwise I need to get permission that the company is okay with being on the list.
