### ISSUE TITLE
Archiving a bundle and then publish from archive should produce the same as the initial build+publish

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2122]
**Is your feature request related to a problem? Please describe.**
We are trying to strengthen our approach to Software Supply Chain Security and ultimately it would be nice to sign the bundles in the registry and keep the signatures when archiving the bundles and moving them to an airgapped registry, but at least we would like to be able to:

1. archive a bundle
2. generate a signature using cosign (https://www.sigstore.dev/)
3. deliver this signature to end users to allow them to pull the bundle from our registry and verify that the bundle matches the published signature
4. be able to restore the bundle in our registry from a backup using the archive in step one without compromising the verify step for end users.

I have tried to use `porter copy` to copy from one registry to another, and then `porter archive` from both registries - these produces identical archives so the signature is not broken.

If I instead do `porter archive <my-archive>  --reference <>` and then `porter publish -a <my-archive> --reference <>` before I once again will do the `porter archive`, then the first and second archived bundle are different and the signature is broken.
Some investigations show that two things differ in the archives:

bundle.json has the "images" section where the image reference in the initially published bundle refers to the original image where as the re-published bundle has been rewritten to refer to the bundled image. This may also be the reason why the "publish to archive" command can not be done without having access to the original registries.
Example from bundle.json
![image](https://user-images.githubusercontent.com/8821406/171348960-71cc036d-68b0-4354-ada9-cd198af2521c.png)

Another difference that I have noticed between the two archives is that the "artifacts/layout/index.json" file does not sort the entries in a deterministic way or maybe it does but it is also impacted by the image reference rewrite that only happens on the "publish from archive"

**Describe the solution you'd like**
Ensure that the image reference rewrite that occurs on "publish from archive" also happens on the initial "publish" so that both bundle.json and "artifacts/layout/index.json" will reference the bundled image instead of the originally referenced image.

**Describe alternatives you've considered**
No alternative identified.

**Additional context**
This behaviour seems to exist both in porter 0.38.10 and 1.0.-alpha.20 and is probably only relevant when you bundle images in the porter bundle to support airgapped mode and reproducible behavior by not relying on external registries.

**Comment by carolynvs** [comment]
Yeah we have a couple open issues to get this issue straightened out:

* #1819 
* #2050 

As part of the [CNAB Security Spec](https://github.com/cnabio/cnab-spec/blob/main/300-CNAB-security.md) (which isn't finalized but seems mostly settled), we have been working on a solution for signing bundles in the [signy](https://github.com/cnabio/signy) repository. I would love to get that work back on track but we don't have the people right now to work on it until later in the year.

I wasn't involved much with signy and it came about before cosign. It would be interesting when we start back up on getting bundle signing built into porter to understand our options around cosign, signy and other tools.

**Comment by carolynvs** [comment]
@jasmdk Both issues have been fixed in the latest version of porter if you'd like to give it another try and let us know if this is resolved.

**Comment by jasmdk** [comment]
> @jasmdk Both issues have been fixed in the latest version of porter if you'd like to give it another try and let us know if this is resolved.

I assume that you mean latest version of porter 1.* - I can confirm that it is fixed. Any idea of when a non-beta version is available @carolynvs ?

**Comment by carolynvs** [comment]
@jasmdk Here's a bit more context into the versioning scheme:

* Both v0.38.* and v1.0.0-beta.1 are pre-release versions. We've been calling v0.38 "stable" because we aren't modifying it anymore (other than critical security fixes).
* v0.38.* will continue to get security patches for 3 months after we ship 1.0
* Porter v1.0.0-beta.1 supports migrating existing installation data (if desired, some people don't care about this) from v0.38.* to v1.0.0-beta.1+. While we have no further database schema changes planned, if anything would change, porter will supporting migrating that too.
* We are actively working on a 1.0 final release this summer. Here's the list of issues still remaining: https://github.com/getporter/porter/milestone/16

So now would be a great time to try out beta.1 and plan for migrating to 1.0 when you are ready. 👍

**Comment by kichristensen** [comment]
This have been issue solved in v1.x
