### ISSUE TITLE
Help command is still running unneccessary config logic

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2133]
When running with the debug log level I noticed that we are still doing some extra config/context setup that we should be skipping for certain commands (skipConfig set on the cobra command).

## Steps to Reproduce
Edit your porter config file and set log-level to debug so you can see what's happening

```yaml
# ~/.porter/config.yaml

log:
  log-to-file: true
  log-level: debug
```

```
$ porter --help
Writing logs to /Users/carolynvs/.porter/logs/01G4N960EJQ98ZK2FTQZT1BC18.json
Writing logs to /Users/carolynvs/.porter/logs/01G4N960EJQ98ZK2FTQZT1BC18.json
HELP TEXT
```

## Expected Behavior
The help text should be printed and we should not be doing the additional context initialization (which is writing the log file in the first two debug lines) for any cobra commands with skipConfig set on its metadata.
```

## Desired Solution

I don't have an exact fix but here's the code that is causing those lines to be output:

https://github.com/getporter/porter/blob/a1d5172446784203e4c3092b98348d5103eeabf3/pkg/portercontext/context.go#L113

It is being called in a constructor which is hard to avoid! Let's see if we can not call that function in the constructor and wait for Porter to explicitly configure logging later. Play around and see what's the best solution we can find.

**Comment by kichristensen** [comment]
This is no longer an issue
