### ISSUE TITLE
porter storage fix-permissions can reset permissions on the current folder

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2143]
## Describe the bug
During upgrade from porter 0.38.3 to 0.38.10 we should fix permissions on the porter files, however as we do not have a [config file](https://porter.sh/configuration/#config-file) in our setup, the [first step](https://github.com/getporter/porter/blob/v0.38.10/pkg/porter/storage.go#L76) will resolve to an empty string and therefore the path will be the current working directory.
In our case the current working directory was the home folder of the user and as it was stripped of its permissions (0600), the user was no longer able to log in!

## To Reproduce
1. Make sure you do not have a "config.*" file in your porter home
2. Create a directory `mkdir mytest` and change directory `cd mytest`
3. Run `porter storage fix-permissions`
4. Verify that the directory permissions is now changed to "drw-------" with `ls -l ..`

## Expected behavior
If the file to fix permissions on does not exist, it should skip the file instead of setting permissions anyway

## Porter Command and Output
```
$ porter storage fix-permissions
Resetting file permissions in /root/.porter...
```

## Version
Copy the output of `porter version` below

porter v0.38.10 (55d92c0f)

**Comment by carolynvs** [comment]
Thanks for the bug report and I apologize that the command messed up that badly... I was able to reproduce and am working on a patch now.

**Comment by carolynvs** [comment]
@jasmdk I have a fix for this issue in the latest stable release: https://github.com/getporter/porter/releases/tag/v0.38.12. Let me know if you run into any further trouble!

**Comment by jasmdk** [comment]
Great, will do. Btw. we did re-establish access to our test environment - just glad we found this issue before using it in various scenarios. Our workaround was to "touch" the config file first to ensure it existed.
