### ISSUE TITLE
porter archive does not include relocation-mapping.json in the archive

### ISSUE THREAD

**Issue by VinozzZ** [getporter/porter#2152]
## Describe the bug

When archiving a bundle, porter only includes `bundle.json` and artifacts into the archive file.  The archived bundle should contain all the necessary information for a bundle that allows users to move bundles across airgapped environment. Without the relocation-mapping.json, porter can not preserve content digests and can't maintain signature verification throughout the process.

## Expected behavior
The archived bundle should contain relocation-mapping.json

## Potential Solution
When we write bundle info to the archive file in this part of the code https://github.com/getporter/porter/blob/26b4ba0edbf7e2f5b39504ad83d3d56f0f43caed/pkg/porter/archive.go#L100, we should also include relocation-mapping.json

## Questions

At the moment I don't know if we should just include everything in [cnab.BundleReference](https://github.com/getporter/porter/blob/f6a9e64d5b2aff927f6f8afc3134ca540dbdc7a6/pkg/cnab/bundle.go#L14) into the archived bundle
```go
type BundleReference struct {
	Reference     OCIReference
	Digest        digest.Digest
	Definition    ExtendedBundle
	RelocationMap relocation.ImageRelocationMap
}
```

## Version
1.0.0-alpha.20

## Related issues
#1819

**Comment by VinozzZ** [comment]
Currently, I'm thinking to get the relocation map from porter bundle cache and then write it to the archive file the same way as we currently do for bundle.json https://github.com/getporter/porter/blob/26b4ba0edbf7e2f5b39504ad83d3d56f0f43caed/pkg/porter/archive.go#L117

**Comment by carolynvs** [comment]
Yeah if we can follow/reuse anything from cached bundles I think that would be a good way to go.

**Comment by VinozzZ** [comment]
> Yeah if we can follow/reuse anything from cached bundles I think that would be a good way to go.

Awesome! I will go ahead with that.
Just wanted to double check just in case you didn't see it, in terms of the Question section in the issue description, do you have any recommendations on that?

**Comment by carolynvs** [comment]
The tgz file should just have a relocation mapping file added to it. The other information is all calculated based on the contents of the archived bundle.

**Comment by VinozzZ** [comment]
> The tgz file should just have a relocation mapping file added to it. The other information is all calculated based on the contents of the archived bundle.

Sounds good! Thanks for the guidance!
