### ISSUE TITLE
Compiling from source with a M1 MacBook Pro while following the documentation fails

### ISSUE THREAD

**Issue by epsxy** [getporter/porter#2172]
## Question

👋🏻 I have been trying to get started with Porter using the **Contributing Tutorial** [here](https://porter.sh/contribute/tutorial/). My question is:

> Can this project can be built from an M1 MacBook Pro, as described in the documentation page above?

I think I have followed exactly the steps mentionned and I'm stuck at the `make build` step. The builder is trying to fetch canary amd64 programs which cannot be found, cf the following error messages:

```
> make build
[...]
go run mage.go GetMixins
Error: helm3 @ v0.1.14 did not publish a download for darwin/arm64
Error: kubernetes @ canary did not publish a download for darwin/arm64
Error: docker @ canary did not publish a download for darwin/arm64
Error: arm @ canary did not publish a download for darwin/arm64
Error: docker-compose @ canary did not publish a download for darwin/arm64
Error: terraform @ canary did not publish a download for darwin/arm64
Error: running "bin/porter mixin install helm3 --version v0.1.14 --feed-url https://mchorfa.github.io/porter-helm3/atom.xml" failed with exit code 1
exit status 1
make: *** [get-mixins] Error 1
```

**I'm sorry if this question has been already asked**, I couldn't find any existing issue or any documentation regarding this problem.

## System info

Afaik, all the dependencies needed in this tutorial were either already installed or installed during the tutorial. I think I have followed the steps carefully, and restarted the process another time from scratch just to be sure. I am using a 2021 M1 MacBook Pro, with OSX 12.4

```
> git version
git version 2.32.1 (Apple Git-133)
> porter version
porter v0.38.12 (26b4ba0e)
> docker --version
Docker version 20.10.16, build aa7e414
> make --version
GNU Make 3.81
This program built for i386-apple-darwin11.3.0
>  mage --version
Mage Build Tool v1.13.0-8-g26cdb5c
Build Date: 2022-06-18T21:55:47+02:00
Commit: 26cdb5c
built with: go1.18.3
> go version
go version go1.18.3 darwin/arm64
```

Thanks a lot!

**Comment by carolynvs** [comment]
Sorry our documentation is not clear. We are currently working on a 1.0 release, and the release/v1 branch is the branch to work from for new development. The main branch has been frozen for a while and we aren't making many changes against it unless it's a security fix. 

We have a separate tutorial for the v1 branch that has updated information, can you give that a try? https://release-v1.porter.sh/contribute/tutorial

**Comment by epsxy** [comment]
Thanks a lot, it's building successfully now 😸! Sorry about that and thanks for your time, I'm going to close this issue.

**Comment by carolynvs** [comment]
Don't apologize, you brought up a very valid concern with our docs that I just opened a PR to correct. Thank you for letting us know that our docs had gotten out of date and I'm relieved to hear that you are back up and running now. 💖
