### ISSUE TITLE
Include sensitive flag in yaml/json output of porter explain for outputs and parameters

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2228]
This issue started off as a discussion at https://github.com/getporter/porter/discussions/2193. When someone is automating retrieving values to run a bundle from porter explain, it is helpful to know if a parameter or output is sensitive. For example, they would know that sensitive values always should be retrieved from a secret store.

I don't want to add more information to the human readable display for the explain command, as we want to limit the info displayed to actionable data and I think this case is really about automation.

So lets add the sensitive flag (boolean) to both the json and yaml parameters and outputs sections in the output of `porter explain`.

For example, here is a bundle that has sensitive parameters and outputs:

```console
$ porter explain -r ghcr.io/getporter/examples/sensitive-data:v0.1.0 -o yaml
name: examples/sensitive-data
description: An example bundle that generates sensitive data
version: 0.1.0
porterVersion: v1.0.0-alpha.19
parameters:
  - name: password
    type: string
    default: null
    applyTo: All Actions
    description: ""
    required: true
outputs:
  - name: name
    type: string
    applyTo: All Actions
    description: ""
mixins:
  - exec
```

After the change, the output should include the sensitive field:

```console
$ porter explain -r ghcr.io/getporter/examples/sensitive-data:v0.1.0 -o yaml
name: examples/sensitive-data
description: An example bundle that generates sensitive data
version: 0.1.0
porterVersion: v1.0.0-alpha.19
parameters:
  - name: password
    type: string
    sensitive: true
    default: null
    applyTo: All Actions
    description: ""
    required: true
outputs:
  - name: name
    type: string
    sensitive: true
    applyTo: All Actions
    description: ""
mixins:
  - exec
```

The change should be made in the following file: https://github.com/getporter/porter/blob/release/v1/pkg/porter/explain.go and the testdata used in the associated test file updated to match the new expected output. You can either update the testdata files by hand, or you can call `mage UpdateTestfiles` after changing the code, and that will update the testdata files to match the new output.

See our [Contributing Tutorial](https://getporter.org/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/release/v1/CONTRIBUTING.md) for help getting started contributing to Porter.

**Comment by MadhuMPandurangi** [comment]
Hi @carolynvs, I'm interested to contribute to this issue. I request you to assign me the same. I had requested to issue #2324 too. I'm fine with any issue.

**Comment by VinozzZ** [comment]
Hi @MadhuMPandurangi , thank you for taking on this issue! If you have any questions, feel free to reach out to us! 
If you haven't read through our contributing guide, here's the link to it: https://porter.sh/contribute/,

**Comment by carolynvs** [comment]
@MadhuMPandurangi We encourage contributors to only work on a single issue at a time, so that issues stay "available" for others to pick up until someone is actively working on them. How about you test out Porter with Artifactory first, and then when that's complete, then start on this one.

**Comment by MadhuMPandurangi** [comment]
Thank you @carolynvs @VinozzZ I'm going through the project and I'm happy to be on your team.

**Comment by MadhuMPandurangi** [comment]
Built a sample bundle that prints the name is done. I looked at the file [https://github.com/getporter/porter/blob/release/v1/pkg/porter/explain.go]() but I didn't get how to make changes or what to edit in this file. Can anyone please help?

**Comment by carolynvs** [comment]
Hi @MadhuMPandurangi,

You need to add the sensitive flag to PrintableParameter, in https://github.com/getporter/porter/blob/f72fc6e2adc3a16038823de967417b9f5ba3f29a/pkg/porter/explain.go#L85-L93

Then populate that field using the result of `bun.IsSensitiveParameter(p)` when we create a display representation of the bundle for the explain command:

https://github.com/getporter/porter/blob/f72fc6e2adc3a16038823de967417b9f5ba3f29a/pkg/porter/explain.go#L247-L253

The yaml/json output of the explain command will automatically pick up your change so you don't need to do anything to get the new sensitive field to print out. Since we are not updating the human readable output of the explain command, there are no associated documentation changes to make this time.

When you run the unit tests with `mage testunit`, you should see tests fail after your change is completed because the output of the explain command now has the sensitive field included. Run `mage updateTestFiles` to synchronize the test files with the new output.

**Comment by MadhuMPandurangi** [comment]
![Screenshot from 2022-10-27 08-24-03](https://user-images.githubusercontent.com/27917751/198180074-e4f3ca88-bcae-4319-a941-e3f78ab23f8d.png)
Can see the output before build and after the build.
Added sensitive flag and successfully displayed.

**Comment by MadhuMPandurangi** [comment]
Do I proceed with PR?
Any document to look at before rising PR for this?

**Comment by carolynvs** [comment]
Looks good! Yes please create a pull request. We have a template that you will be prompted to fill out when you open it that explains the information we are looking for. 👍

**Comment by MadhuMPandurangi** [comment]
Hi @carolynvs @VinozzZ, please review the PR.

Thank You
