### ISSUE TITLE
Show success message when porter lint cannot find an error

### ISSUE THREAD

**Issue by Simpcyclassy** [getporter/porter#2237]
## Description

Currently, there is no output for the linter when there are no errors on run. We found this confusing as it just outputs a blank line.

Typically when the javascript linter, [eslint](https://www.npmjs.com/package/eslint) is run it usually ends with

```
✨  Done in 20.95s
``` 
even when there is no error or warning to report.

For the python linter [black](https://pypi.org/project/black/) it would typically end with something like this

```
All done! ✨ 🍰 ✨
24 files left unchanged.
```

## Proposed Solution

We think we can add a message that reads something like, "Everything looks good" after a successful run and no errors have been detected.

## Alternative Solution

If it is not desired to return a specific message, we could remove the blank line (ie return nothing) which would match some other popular linters

## Additional Context

We thought about this after looking at #1226

**Comment by carolynvs** [comment]
That's a good idea. 👍 How about we print "Bundle validation was successful!"

**Comment by Simpcyclassy** [comment]
Yeah, I think this sounds more descriptive.

**Comment by ThorstenHans** [comment]
I'll take this one
