### ISSUE TITLE
Any reason why porter images are not published for v1 since alpha.15?

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2262]
**What is your question?**
In our continuous integration setup, we use a docker image with porter and the mixins of our choice. Normally we use the getporter/porter as a base image, but while migrating to porter v1 I am missing a v1.0.0-beta.1 tag and it seems like also the latest alpha tags are missing (not that I need them).
As an alternative, do you have a Dockerfile which I could simply use as a starting point instead of extending the one you normally publish?

**What have you tried already?**
I tried explicitly pulling the image even though docker.io does not show it - it is not found.

**Where have you looked already to figure this out?**
https://hub.docker.com/r/getporter/porter/tags?page=1&name=v1.0.0

**Was the existing documentation unclear or had gaps?**
No

**Comment by jasmdk** [comment]
Ah, I found it at ghcr.io - the docs concerning porter client should probably be updated as it still references hub.docker.com
https://getporter.org/docker-images/client/

**Comment by carolynvs** [comment]
Thanks we'll get the docs updated, sorry that we missed that when we made the switch (due to rate limiting, etc Hub doesn't work well for us anymore).

**Comment by carolynvs** [comment]
I wanted to give you a heads up that while we do publish these images, we don't actually ever run Porter that way ourselves or recommend running Porter like that. I've submitted a PR to fix the location of the images but I wanted you to know that long term we may stop publishing that porter client image.

https://github.com/getporter/porter/issues/2265

If you have feedback on possibly removing that image, or how the docs for the image can be updated to support 1.0, please share it on that issue!

**Comment by jasmdk** [comment]
Good to know that it may not be there in the future - I will create my own image with just the porter binaries and the tools we need rather than copying those from the client image.
