### ISSUE TITLE
porter parameters/credentials apply ignores the schemaType

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2269]
## Describe the bug
It is possible to create a ParameterSet as a YAML file and apply it as a CredentialSet and the other way around. I would expect porter to complain as the schemaType does not match. 

## To Reproduce
1. Run `porter parameters create myparams.yaml`
2. See `creating porter parameter set in the current directory`
3. Run `porter credentials apply myparams.yaml`
4. See error: `Applied NAMESPACE/NAME credential set`
5. Or run `porter credentials create mycreds.yaml`
6. See `creating porter credential set in the current directory`
7. Run `porter parameters apply mycreds.yaml`
8. See error: `Applied NAMESPACE/NAME parameter set`

## Expected behavior
Porter should abort, stating that a CredentialSet can not be applied as a ParameterSet and the other way around.

## Porter Command and Output
See above

## Version
porter v1.0.0-beta.1 (eaf8d0d4)

**Comment by carolynvs** [comment]
That field was originally intended just to help us out later when implementing support for VS Code autocomplete, but yeah we can totally check for if the schemaType is set (it's optional) and then validate it.
