### ISSUE TITLE
porter create template .dockerignore contains old name

### ISSUE THREAD

**Issue by Jemgoss** [getporter/porter#2275]
` porter create` generates `template.Dockerfile` and `.dockerignore` but the contents of the latter references the old template name `Dockerfile.tmpl`. Fixing this will reduce confusion and even the size of the invocation image by ~1000 bytes!

This is seen in version `porter v1.0.0-beta.2-5-g07947b99 (07947b99)`.

Although it was an omission in commit `7b98f5062e1c1756ecd9698051b52785af2cf568` and easily fixed, a more thorough global find and replace on `Dockerfile.tmpl` => `template.Dockerfile` touches *many* files in doc.

I'll create a PR with at least the single fix and we can determine whether to proceed with the global replace.

**Comment by ThorstenHans** [comment]
I'll take this one
