### ISSUE TITLE
Airgapped images are broken in v1.0.0-beta.2

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2280]
## Describe the bug
Referencing images to be bundled for airgapped scenario only works if the image is available in the local docker cache.

## To Reproduce
1. Add an image to "images" property in porter.yaml and make sure to reference an image that has not already been pulled locally
2. Run `porter build`
3. See error

## Expected behavior
The image must be pulled from the listed registry.

## Porter Command and Output
```
$ porter build
failed to find image istio/pilot:1.13.4 in docker cache: Error: No such image: istio/pilot:1.13.4
failed to find image istio/pilot:1.13.4 in docker cache: Error: No such image: istio/pilot:1.13.4
unable to generate manifest: failed to find image istio/pilot:1.13.4 in docker cache: Error: No such image: istio/pilot:1.13.4
```

## Version
porter v1.0.0-beta.2 (b2f23785)

**Comment by carolynvs** [comment]
@VinozzZ Can you take a look at this? I assume it's a regression caused by #2198

**Comment by VinozzZ** [comment]
Hi @jasmdk , we just cut a new release that contains a fix for this issue. Feel free to try it out and let us know how it works for you!
