### ISSUE TITLE
Underline on website title doesn't always align up with the word together

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2305]
## Describe the bug
The title of the homepage has an underline on the word "together". But depending on the window size, it doesn't always line up.

## To Reproduce
1. Go to getporter.org and slowly make the screen wider until the line moves out of place.

## Expected behavior
Either we don't use the underline, or it should always be under the word "together". Either way is 100% fine with me. If I were fixing it, I'd probably just remove the underline since it is tricky to get right.

![Screen Shot 2022-08-17 at 11 34 51 AM](https://user-images.githubusercontent.com/1368985/185195013-f2716d3f-db9f-4986-aa80-63a7e085bdb2.png)

**Comment by AGMETEOR** [comment]
Hey @carolynvs . I can help with this one. Wondering where the files for the website live?

**Comment by carolynvs** [comment]
@AGMETEOR Great! The website files are in this repository in the [/docs directory](https://github.com/getporter/porter/tree/release/v1/docs). We use Hugo to render the site. You can test out your changes locally with Docker, https://github.com/getporter/porter/blob/release/v1/CONTRIBUTING.md#preview-documentation. Or if you want to use hugo directly, make sure to install Hugo extended version 0.78.1.
