### ISSUE TITLE
Quick way to uninstall Porter v0.38 and reinstall Porter v1?

### ISSUE THREAD

**Issue by qpetraroia** [getporter/porter#2311]
**What is your question?**
I am wondering if there is a quick way to uninstall Porter v0.38 and remove it from my machine so I can reinstall Porter v1. I don't care that much about migrating my data over, and I would actually prefer to just do a clean wipe.

**What have you tried already?**
I have tried following the instructions in the docs to migrate to v1 but I seem to still get this message 

```
Your database schema is:

storage.Schema{ID:"schema", Installations:"1.0.0", Credentials:"1.0.1", Parameters:"1.0.1"}

Refer to https://getporter.org/storage-migrate for more information and instructions to back up your data. 
Once your data has been backed up, run the following command to perform the migration:

    porter storage migrate

```

I believe it will be easier to just remove v0.38 entirely and do a fresh install of v1.

Thanks!

**Comment by carolynvs** [comment]
You can run the following commands to remove the previously created Porter database that is stored automatically when you run Porter with a database configured:

```
docker rm -f porter-mongodb-docker-plugin
docker volume rm porter-mongodb-docker-plugin-data
```

**Comment by carolynvs** [comment]
I'm leaving this open since the doc page for the upgrade should explain how to remove the old database in cases like this.

**Comment by qpetraroia** [comment]
Hey, this worked! Thanks @carolynvs  :)
