### ISSUE TITLE
porter installation state does not support re-installing

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2313]
## Describe the bug
`porter installation list` can show the state of the installation and can be used to determine if a bundle is already installed where an upgrade action is then needed rather than another install. However if you uninstall the bundle (state will be shown as "uninstalled") and then install the bundle again, the state will keep claiming that the bundle is uninstalled.

The error is related to the calculated status which probably just states that it is uninstalled if the uninstalled timestamp is present, however the timestamp should either be removed when it has been installed again, or it should compare the timestamps for "installed" and "uninstalled" to see which is the latest one.

## To Reproduce
1. Run `porter install` for any bundle
2. Run `porter installation list`
3. See the state being "installed"
4. Run `porter uninstall`
5. Run `porter installation list`
6. See the state being "uninstalled"
7. Run `porter install`
8. Run `porter installation list`
9. See the state still being "uninstalled"

## Expected behavior
If a bundle has been uninstalled and then afterwards installed again, the state should express that it is "installed"

## Porter Command and Output
```
$ porter list -n test -o yaml
- schemaType: Installation
  schemaVersion: 1.0.2
  id: 01GBQ0VPY1WE2JQ19P9S1EVWMN
  name: porter-hello
  namespace: test
  bundle: {}
  status:
    runId: 01GBQ0VZNVEVG2E8Q9F9GME511
    action: install
    resultId: 01GBQ0W0TPFJTP0T77N936KJN3
    resultStatus: succeeded
    created: 2022-08-30T11:21:01.889051+02:00
    modified: 2022-08-30T11:21:01.889051+02:00
    installed: 2022-08-30T11:21:12.0220218+02:00
    uninstalled: 2022-08-30T11:21:08.4135897+02:00
    bundleReference: ""
    bundleVersion: 0.1.0
    bundleDigest: ""
  _calculated:
    resolvedParameters: []
    displayInstallationState: uninstalled
    displayInstallationStatus: succeeded
```

## Version
Copy the output of `porter version` below

porter v1.0.0-beta.3 (f7aa99dc)

**Comment by carolynvs** [comment]
Thanks for reporting this!

**Comment by kichristensen** [comment]
@schristoff According to my tests this is no longer an issue in the v1.0.16

**Comment by schristoff** [comment]
I'm not able to reproduce in v1.0.15, it looks like #2353 fixed this in v1~ 
If this issue is persisting or occurs again, please open up a new issue and we'll dig into it! :)
