### ISSUE TITLE
Docs state that bundle.installerImage is a valid template reference but it is not

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2316]
## Describe the bug
According to https://getporter.org/authors/templates/#bundle it is possible to get a reference to the current invocation image using `${bundle.installerImage}` however this template fails.

## To Reproduce
1. Add `${bundle.installerImage}` as an extra argument to exec mixin with the intention of printing this value to the console
2. Run `porter build`
3. Run `porter install`

## Expected behavior
Our setup makes use of the installer image in order to run some tasks as a Kubernetes job within the cluster rather than a plain docker container on another server and before Porter v1 we picked the invocationImage from /cnab/bundle.json, but this file is no longer modified during publish and will point to the original invocation image, which may not be accessible from the target environment.
We have currently implemented a workaround where we still pick the original invocation image from bundle.json, and then look up the value in relocation-mapping.json - however it would be nice to just pass it using ${bundle.installerImage}:
```
originalImage=$(jq -r ".invocationImages[0].image" /cnab/bundle.json)
image=$(jq -r ".\"${originalImage}\"" relocation-mapping.json)
```

## Porter Command and Output
```
$ porter install
executing install action from porter-hello (installation: synergy/porter-hello)
unable to render step template {{=${ }=}}
exec:
    description: "Install Hello World"
    command: ./helpers.sh
    arguments:
        - install
        - "${bundle.installerImage}"
: Missing variable "installerImage"
1 error occurred:
        * unable to resolve step: unable to render step template {{=${ }=}}
exec:
    description: "Install Hello World"
    command: ./helpers.sh
    arguments:
        - install
        - "${bundle.installerImage}"
: Missing variable "installerImage"


1 error occurred:
        * unable to resolve step: unable to render step template {{=${ }=}}
exec:
    description: "Install Hello World"
    command: ./helpers.sh
    arguments:
        - install
        - "${bundle.installerImage}"
        #- exec:
        #    description: "Print JSON output value"
        #    command: ./helpers.sh
        #    arguments:
        #      - print-value
        #      - |
        #          my:
        #            value:
        #              is: true
: Missing variable "installerImage"


1 error occurred:
        * container exit code: 1, message: <nil>
```

## Version
Copy the output of `porter version` below

porter v1.0.0-beta.3 (f7aa99dc)

**Comment by carolynvs** [comment]
Sorry there's a bit of lag between when the doc goes live (as soon as a PR is merged) and when it is available in a release.

I'll cut a new release today which will include #2283

**Comment by carolynvs** [comment]
Ok v1.0.0-beta.4 is out and includes the feature that was out-of-sync with our website.
