### ISSUE TITLE
Porter archive is not deterministic across architectures

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2318]
## Describe the bug
Archiving the same bundle using the Windows binary and the Linux binary yields different results, which prevents proper signing and verification of airgapped bundles.

I'm not sure it can be consistently reproduced as the problematic file (artifacts/layout/index.json) has a list of manifests where the order is different. I can not tell if the order is random or what it is sorted by. It seems like the bottom entry is the invocation image in both scenarios, but the list of bundled images are listed in different order.

## To Reproduce
1. Create a porter bundle which includes at least two bundled images like
```
images:
  pilot:
    imageType: docker
    repository: istio/pilot
    tag: 1.14.3
  proxyv2:
    imageType: docker
    repository: istio/proxyv2
    tag: 1.14.3
```
2. Run `porter publish`
3. Run `porter archive` on a Windows machine and on a Linux machine
4. See that the binary size differs
5. Extract and compare `artifacts/layout/index.json` from both archives and see that the order of manifests differ (except the invocation image which is the very last entry)

## Expected behavior
Previous fixes (https://github.com/getporter/porter/issues/2122) has ensured that when archiving a bundle multiple times, will produce the exact same binary which is critical for us to ensure that we can produce a signature of the archived bundle and verify it later, but it appears that if the signature was generated on a bundle archived on a Linux machine, then it can not be verified against a bundle archived on a windows machine.

## Porter Command and Output
Comparison of artifacts/layout/index.json
![image](https://user-images.githubusercontent.com/8821406/187621267-bfc40309-4a08-4455-aae6-b8f3572ec294.png)

## Version
Copy the output of `porter version` below

porter v1.0.0-beta.3 (f7aa99dc)

**Comment by carolynvs** [comment]
My guess is that when we iterate over the referenced images and add them to the manifest, we aren't sorting them but this will need further investigation.

**Comment by jasmdk** [comment]
That means it is not a problem across architectures, but in generall we can not trust that a signature calculated on the archived bundle will validate as we can not guarantee that the order is consistent. 
I hope this one will be prioritized.

**Comment by jasmdk** [comment]
I do not yet have a setup where I can build and test code changes, but I believe I have identified the problem and the fix.
Here is a loop of the bundle images which is stored as a map: https://github.com/getporter/porter/blob/release/v1/pkg/porter/archive.go#L197
However, maps do not have a specified order and can not be guaranteed to be the same for two different iterations - See section "Iteration order" in https://go.dev/blog/maps for an explanation and an example of sorting the keys and looping using the sorted keys.

**Comment by jasmdk** [comment]
@carolynvs any chance this could be included in a new beta any time soon?

**Comment by carolynvs** [comment]
Thanks for creating the other issue to better track where we are still missing the mark!
