### ISSUE TITLE
Intermitent unexpected size error when publishing

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2320]
## Describe the bug
I only see this in CI. When running a test, it will fail with the error `error preparing the bundle with cnab-to-oci before pushing: failed commit on ref "layer-sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4": unexpected size 64, expected 32`.

This started happening pretty recently, and the only related change that I can think of is that we are now always forcing the platform (see #2286) . The only remotely related bug I've found that has the same error is in buildx (which uses a lot of the same underlying deps as us), https://github.com/docker/buildx/issues/235.

If you repeat the test, it will pass. I don't think it's a test flake since the test is just running the Porter CLI.

## To Reproduce
Watch our CI and note how the smoke tests randomly fail with this error.

## Porter Command and Output
```
=== RUN   TestDesiredState
2022/08/31 16:24:53 exec: /usr/bin/docker docker inspect localhost:5000/mydb-installer:v0.1.0
    helpers.go:45: porter build
2022/08/31 16:24:53 exec: /tmp/porter3563245149/porter porter build
    helpers.go:49: porter publish --reference localhost:5000/mydb:v0.1.0
2022/08/31 16:25:07 exec: /tmp/porter3563245149/porter porter publish --reference localhost:5000/mydb:v0.1.0
2022/08/31 16:25:22 exec: /usr/bin/docker docker inspect localhost:5000/mybuns-installer:v0.1.2
    helpers.go:45: porter build
2022/08/31 16:25:22 exec: /tmp/porter3563245149/porter porter build
    helpers.go:49: porter publish --reference localhost:5000/mybuns:v0.1.2
2022/08/31 16:25:33 exec: /tmp/porter3563245149/porter porter publish --reference localhost:5000/mybuns:v0.1.2
    helpers.go:49: failed to run porter publish --reference localhost:5000/mybuns:v0.1.2
    helpers.go:49: Pushing bundle image...
        The push refers to repository [localhost:5000/mybuns]
        5f70bf18a086: Preparing
        ce12f87df86f: Preparing
        99560abc61f6: Preparing
        941d5ae47c31: Preparing
        98405677cc6a: Preparing
        903d7113edc0: Preparing
        ac3796653aaa: Preparing
        794e5ccdf2f3: Preparing
        42db8a050ed4: Preparing
        992f38e1a81c: Preparing
        903d7113edc0: Waiting
        	            	Pushing bundle localhost:5000/mybuns:v0.1.2
        	            	error preparing the bundle with cnab-to-oci before pushing: failed commit on ref "layer-sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4": unexpected size 64, expected 32
        	            	error preparing the bundle with cnab-to-oci before pushing: failed commit on ref "layer-sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4": unexpected size 64, expected 32
        	            	: running "porter publish --reference localhost:5000/mybuns:v0.1.2" failed with exit code 1

```

## Version
v1.0.0-beta.4

**Comment by jasmdk** [comment]
I believe we have seen something similar, which was related to publishing images where two layers had the same checksum because the layer did not do anything. The problematic image had a dockerfile where one layer was a `RUN chmod +x something` which did not produce any changes probably because the execute bit was already set. Publishing again went through because publishing only pushes layers that is not already there.
Hope this was helpful.

**Comment by carolynvs** [comment]
Thanks! It does seem to just be happening with a particular image. I'll take a look. 👍

**Comment by carolynvs** [comment]
I have created https://github.com/cnabio/cnab-to-oci/issues/128 to track the race condition when copying the same layer multiple times.
