### ISSUE TITLE
Porter archive produces inconsistent hash across platforms/users

### ISSUE THREAD

**Issue by jarnfast** [getporter/porter#2334]
## Describe the bug

Archiving the same bundle using the Windows binary and the Linux binary yields different results, which prevents proper signing and verification of air-gapped bundles. Even archiving on different Linux's yields different results.

#2318 fixed the initial issue with the inconsistent generation of `layouts.json` - but that turned out to be only one of the (many) problems.

Looking at the produced tar files we observe some differences.

Linux:
```
drwxrwx--- azureuser/azureuser 0 1970-01-01 00:00 ./
drwxr-xr-x azureuser/azureuser 0 1970-01-01 00:00 ./artifacts/
drwxr-xr-x azureuser/azureuser 0 1970-01-01 00:00 ./artifacts/layout/
drwxrwxr-x azureuser/azureuser 0 1970-01-01 00:00 ./artifacts/layout/blobs/
drwxrwxr-x azureuser/azureuser 0 1970-01-01 00:00 ./artifacts/layout/blobs/sha256/
-rw-rw-r-- azureuser/azureuser 61901531 1970-01-01 00:00 ./artifacts/layout/blobs/sha256/054fd5e3c10430f56736672ad3d92eddcadad7db7f67608184619076713cd1b2
-rw-rw-r-- azureuser/azureuser    24458 1970-01-01 00:00 ./artifacts/layout/blobs/sha256/0d0b8f067d68592647f879fc8f504513d2f381c0b1395f3a75a2ede1b77b4297
..
```

Windows:
```
drwxr-xr-x 0/0               0 1970-01-01 01:00 ./
drwxr-xr-x 0/0               0 1970-01-01 01:00 ./artifacts/
drwxr-xr-x 0/0               0 1970-01-01 01:00 ./artifacts/layout/
drwxr-xr-x 0/0               0 1970-01-01 01:00 ./artifacts/layout/blobs/
drwxr-xr-x 0/0               0 1970-01-01 01:00 ./artifacts/layout/blobs/sha256/
-rwxr-xr-x 0/0        61901531 1970-01-01 01:00 ./artifacts/layout/blobs/sha256/054fd5e3c10430f56736672ad3d92eddcadad7db7f67608184619076713cd1b2
-rwxr-xr-x 0/0           24458 1970-01-01 01:00 ./artifacts/layout/blobs/sha256/0d0b8f067d68592647f879fc8f504513d2f381c0b1395f3a75a2ede1b77b4297
..
```

The obvious issues are:

1. User and group does not match between Linux and Windows
2. User and group uses current user information on Linux
3. File modes does not match

Regular tar supports overriding the owner/group and filemode information but the library used by porter does not support this.

The archive library used by porter does support setting `ChownOpts` in the `TarOptions` which sounded like half of the solution:

```go
    chownOpts := &idtools.Identity{
		UID: 8,
		GID: 8,
	}
	tarOptions := &archive.TarOptions{
		Compression:      archive.Gzip,
		IncludeFiles:     []string{"."},
		IncludeSourceDir: true,
		ChownOpts:        chownOpts,
	}
	rc, err := archive.TarWithOptions(archiveDir, tarOptions)
```

Buuuut digging deeper in to the raw tar file header it is obvious that the owner/group information in the `USTAR` formatted header still contains some unwanted data.

The `azureuser` has uid/gid 1000 (1750 in octal below).

Vanilla Linux header:
```
00000000: 2e2f 0000 0000 0000 0000 0000 0000 0000  ./..............
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 3030 3430 3737 3000 3030 3031  ....0040770.0001
00000070: 3735 3000 3030 3031 3735 3000 3030 3030  750.0001750.0000
00000080: 3030 3030 3030 3000 3030 3030 3030 3030  0000000.00000000
00000090: 3030 3000 3031 3333 3131 0020 3500 0000  000.013311. 5...
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000100: 0075 7374 6172 0030 3061 7a75 7265 7573  .ustar.00azureus
00000110: 6572 0000 0000 0000 0000 0000 0000 0000  er..............
00000120: 0000 0000 0000 0000 0061 7a75 7265 7573  .........azureus
00000130: 6572 0000 0000 0000 0000 0000 0000 0000  er..............
00000140: 0000 0000 0000 0000 0030 3030 3030 3030  .........0000000
00000150: 0030 3030 3030 3030 0000 0000 0000 0000  .0000000........
00000160: 0000 0000 0000 0000 0000 0000 0000 0000  ................
..
```

ChownOpted Linux header.
```
00000000: 2e2f 0000 0000 0000 0000 0000 0000 0000  ./..............
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 3030 3430 3737 3000 3030 3030  ....0040770.0000
00000070: 3031 3000 3030 3030 3031 3000 3030 3030  010.0000010.0000
00000080: 3030 3030 3030 3000 3030 3030 3030 3030  0000000.00000000
00000090: 3030 3000 3031 3332 3631 0020 3500 0000  000.013261. 5...
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000100: 0075 7374 6172 0030 3061 7a75 7265 7573  .ustar.00azureus
00000110: 6572 0000 0000 0000 0000 0000 0000 0000  er..............
00000120: 0000 0000 0000 0000 0061 7a75 7265 7573  .........azureus
00000130: 6572 0000 0000 0000 0000 0000 0000 0000  er..............
00000140: 0000 0000 0000 0000 0030 3030 3030 3030  .........0000000
00000150: 0030 3030 3030 3030 0000 0000 0000 0000  .0000000........
00000160: 0000 0000 0000 0000 0000 0000 0000 0000  ................
..
```

The file mode could _probably_ be fixed by changing that locally before invoking `TarWithOptions` - the same way timestamps are set to unix epoch. But the `USTAR` header produced by the used library is a lot trickier to circumvent.

Could it be a solution to replace the current tar-archiver with another library that contains the needed options for overriding user/group/filemode and other headers?

## To Reproduce
1. Create a porter bundle
2. Run `porter publish --reference <some registry>`
3. Run `porter archive <archive> --reference <some registry>` on a Windows machine
4. Run `porter archive <archive> --reference <some registry>` on a Linux machine
5. Run `tar tzvf <archive>` on both machines
6. Observe differences
7. Run `sha256sum <archive>` on both machines
8. Should be equal .. but they probably won't be.

## Expected behavior

The `tgz` files produced by `porter archive` should be identical (e.g. sha256sum) irregardless of which user performed the action 

## Porter Command and Output

Note: SHAs are just for illustrations purposes - the main thing is that they differ.

On any os:
```
$ porter create
$ porter build
$ porter publish --reference <registry>
.. <snipped>
```
On Windows:
```
$ porter archive foo.tgz --reference <registry>
$ sha256sum foo.tgz
9607dfd26edc60ed72559eecbcc993257c4c915ffa93f049624cbbe48ecebaf2 *foo.tgz
```
On Linux:
```
$ porter archive foo.tgz --reference <registry>
$ sha256sum foo.tgz
8e324ef82743b4b0a13055a73b77d3e348afabda3f2c7af810af84e0a940e67a  foo.tgz
```

## Version
Copy the output of `porter version` below

porter v1.0.0-beta.4 (d815218e)

**Comment by jarnfast** [comment]
Applying `chmod` à la `chtimes` won't fix anything in windows due to [the windows specific implementation of `chmodTarEntry`](https://github.com/moby/moby/blob/20.10/pkg/archive/archive_windows.go#L33)

**Comment by carolynvs** [comment]
If you have suggestions for a better tar library that does what you can do with the command line of the real tar cli, I am VERY open to changing what we use. This obviously isn't the first time we have struggled with getting the library to do what we need.

**Comment by carolynvs** [comment]
Switching this from bug to gap since it hasn't ever been a guarantee made by either CNAB or porter that building the same bundle on different OS's (and users, etc)  will yield the same bundle byte for byte. I'm all for being able to make that claim at some point though!

**Comment by jarnfast** [comment]
Gap works for me ;)

Are you aware of any situations where porter archive uses any of the SymLink/HardLink/Device/WhatNot handling the `docker/archive/archive.go` implements? Or can we assume that we're always packaging a bunch of regular files?

Assuming the regular file scenario the tar file creation could look something like this:

1. Consistently traverse the temporary directory (some sort of sort order must be ensured)
2. For each file/directory, add to tar with the following overrides:
    1. Set `Uid/Gid` to `0/0`
    2. Set mode to `0644` for files, `0755` for directories
    3. Set `mtime/atime/ctime` to unix epoch
    4. Blank `Uname/Gname` and other unnecessary fields
    
This also means that the the current `chtimes` traverse would be redundant as that OS/disk information won't be used when creating archive.

**Comment by carolynvs** [comment]
> Are you aware of any situations where porter archive uses any of the SymLink/HardLink/Device/WhatNot handling the docker/archive/archive.go implements? Or can we assume that we're always packaging a bunch of regular files?

It's just a bunch of normal files, no symlinks or anything like that.
