### ISSUE TITLE
Define process for reporting and handling security issues

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2341]
In order to apply to CNCF Incubation stage, we need to "Clearly documented security processes explaining how to report security issues to the project, and describing how the project provides updated releases or patches to resolve security vulnerabilities".

We can find templates for reporting and embargo processes in the [CNCF recommended templates](https://contribute.cncf.io/maintainers/github/templates/):

* security contacts
* embargo policy
* embargo notification
* incident response

**Comment by carolynvs** [comment]
Now that github supports this, https://github.blog/changelog/2022-11-09-privately-report-vulnerabilities-to-repository-maintainers/, we can use it instead of maintaining a separate mailing list.

**Comment by kichristensen** [comment]
Implemented in #3047
