### ISSUE TITLE
Incorrect installation state after migration to v1

### ISSUE THREAD

**Issue by jarnfast** [getporter/porter#2353]
## Describe the bug

We're seeing some issues with the migration from v0.38.12 to v1 - some installations are ending up in a `uninstalled` or `defined` state.

I'm haven't been able to reproduce it (_yet_) but it fails consistently on our test server. So this issue just contains the output I've encountered so far - but I thought it relevant to bring it to your attention now.

My guess is that it is related to claims not being migrated in a sorted order - an assumption loosely based on me finding the following bit of https://github.com/getporter/porter/blob/release/v1/pkg/storage/migrations/migration.go#L224-L226

Perhaps this sorting should be done prior to iterating the claims?
https://github.com/getporter/porter/blob/release/v1/pkg/storage/migrations/migration.go#L218-L219

## To Reproduce

TBD

1. Run `...`
2. Use this porter.yaml from this repository or gist
3. Run this porter command `...`

## Expected behavior

Installations should end up with the correct state after migration

## Porter Command and Output

```
[root@testserver old-porter-home]# PORTER_HOME=. ./porter list
NAME                           CREATED      MODIFIED     LAST ACTION    LAST STATUS
test-bundle1                   2022-06-22   2022-06-22   upgrade        succeeded
test-bundle3                   2022-09-02   2022-09-02   upgrade        succeeded
test-bundle2                   2022-06-22   2022-06-22   upgrade        succeeded


[root@testserver old-porter-home]# PORTER_HOME=. ./porter show test-bundle1
Name: test-bundle1
Created: 2021-11-15
Modified: 2022-06-22

Outputs:
--------------------------------------------------------------------------------
  Name                                 Type    Value
--------------------------------------------------------------------------------
  io.cnab.outputs.invocationImageLogs  string  executing upgrade action from
                                               test-bundle1 (installati...

History:
--------------------------------------------------------------------------
  Run ID                      Action     Timestamp   Status     Has Logs
--------------------------------------------------------------------------
  01FMHGM6BSH4CKVKE0G0T7S4CY  install    2021-11-15  succeeded  true
  01FPA38KVF5MJSGHAZETCQ792V  upgrade    2021-12-07  succeeded  true
  01FPW0K1A066WGW4P1MMA10ZMQ  upgrade    2021-12-14  failed     true
  01FPW0N9FAMPX7R4KQK4NZPC0M  upgrade    2021-12-14  failed     true
  01FPW0XFKEM2K8PWH0XJ2Q5M98  uninstall  2021-12-14  succeeded  true
  01FPW0Y3EJQ1CJNW5E58502Y5N  install    2021-12-14  succeeded  true
  01FPZ67EVWPMXZGRNX1069TNKZ  upgrade    2021-12-15  succeeded  true
  01FXZ0KMEV92B8GSYHN1E2RW9D  upgrade    2022-03-12  succeeded  true
  01G563RFRHZQ6TS3GYM2P6SJXT  upgrade    2022-06-10  succeeded  true
  01G65TF7DN1RY4V2RQA10XQCRT  upgrade    2022-06-22  succeeded  true

.. insert migration here ..

[root@testserver ~]# porter -n test list
----------------------------------------------------------------------------------------
  NAMESPACE  NAME                          VERSION  STATE        STATUS     MODIFIED
----------------------------------------------------------------------------------------
  test       test-bundle1                  1.0.0    uninstalled  succeeded  2022-06-22
  test       test-bundle2                  0.1.1    defined      succeeded  2022-06-22
  test       test-bundle3                  3.0.0    installed    succeeded  2022-09-02

[root@testserver ~]# porter -n test show test-bundle1 -o yaml
schemaType: Installation
schemaVersion: 1.0.2
id: 01FMHGM6BSH4CKVKE0G0T7S4CY
name: test-bundle1
namespace: test
bundle: {}
status:
  runId: 01G65TF7DN1RY4V2RQA10XQCRT
  action: upgrade
  resultId: 01G65TG6GJ211ZNE00GSM250WV
  resultStatus: succeeded
  created: 2021-11-15T11:00:04.217318663+01:00
  modified: 2022-06-22T15:43:46.869040797+02:00
  installed: 2021-12-14T09:30:11.768736182+01:00
  uninstalled: 2021-12-14T09:28:40.520278737+01:00
..
```

## Version
Copy the output of `porter version` below

porter v1.0.0-rc.1 (8e005d5c)

**Comment by jarnfast** [comment]
Just tried the migrate with a custom build with the sorting done before the iteration of claims - not changes to the result. 😭

**Comment by VinozzZ** [comment]
Hi @jarnfast , thank you for opening the issue and dig into it. It seems like you have found some leads. Do you want to give your above findings a try and let me know if that fixes the issue?

**Comment by jarnfast** [comment]
@VinozzZ perhaps, if I could get a pointer towards the correct solution.

In the uninstalled vs. installed case could the solution be that the `isInstalled()` method compares the timestamp if `i.Status.Uninstalled != i.Status.Installed != nil` ?

The bundle with the `defined` state has the following claims:

```
History:
------------------------------------------------------------------------
  Run ID                      Action   Timestamp   Status     Has Logs
------------------------------------------------------------------------
  01G5GYNJH6KAB06KVAX5YQ87VH  install  2022-06-14  failed     true
  01G5H2JBTWCXE9P46W46YFMR9H  upgrade  2022-06-14  failed     true
  01G5H5VFZ9RXJHADK7MESWJ0SY  upgrade  2022-06-14  failed     true
  01G5H64H75JAF7ZXRSP0RR024X  upgrade  2022-06-14  succeeded  true
  01G604SV74YAFP2Y7JR58ER58T  upgrade  2022-06-20  succeeded  true
  01G65VKNG0BFY48SQQ38JZNB19  upgrade  2022-06-22  succeeded  true
```
Ie. initial install failed, upgrade failed a few times and then succeded - is `defined` the desired state for that migration?

**Comment by VinozzZ** [comment]
> 

From my understanding, I think you are on the right track here. The `IsInstalled()` method should check if the Installed timestamp is after the uninstall if they both exist. Feel free to submit a PR since you pretty much figured it out! Then we can get other people to also chime in during the PR review. How does that sound?

**Comment by jarnfast** [comment]
I can give a try, any thoughts on the issue with bundle ending up in `defined` state?

**Comment by jarnfast** [comment]
Just a thought, another approach to solving the issue would be to let `ApplyStatus` reset the timestamp, e.g. when it processes a successful install it could also set the `Uninstalled` timestamp to nil (and vice versa).

What's the design? Is it intentional that a the state can have both `Installed` and `Uninstalled` set?

**Comment by VinozzZ** [comment]
I believe we have a gap here since we didn't imagine users would uninstall a bundle and then re-install it again.
As for the `defined` state, it looks like a bug in v0.38. If an installation never succeeded, porter should not allow an upgrade action to be performed. That maybe the reason why the bundle ended up in defined state. 
Is below series of action executed by v0.38? Or did you executed with porter v1?
```
History:
------------------------------------------------------------------------
  Run ID                      Action   Timestamp   Status     Has Logs
------------------------------------------------------------------------
  01G5GYNJH6KAB06KVAX5YQ87VH  install  2022-06-14  failed     true
  01G5H2JBTWCXE9P46W46YFMR9H  upgrade  2022-06-14  failed     true
  01G5H5VFZ9RXJHADK7MESWJ0SY  upgrade  2022-06-14  failed     true
  01G5H64H75JAF7ZXRSP0RR024X  upgrade  2022-06-14  succeeded  true
  01G604SV74YAFP2Y7JR58ER58T  upgrade  2022-06-20  succeeded  true
  01G65VKNG0BFY48SQQ38JZNB19  upgrade  2022-06-22  succeeded  true
```

**Comment by jarnfast** [comment]
> Is below series of action executed by v0.38? Or did you executed with porter v1?

That's the actions executed by v0.38. (I haven't found the history in v1 yet ;))

**Comment by joshuabezaleel** [comment]
From the discussion, I guess the PR would also tackle this issue as well then (?)
https://github.com/getporter/porter/issues/2313

**Comment by jarnfast** [comment]
> From the discussion, I guess the PR would also tackle this issue as well then (?) #2313

Yes, the fix proposed in PR #2354 would resolve #2313 as well.

**Comment by jarnfast** [comment]
> If an installation never succeeded, porter should not allow an upgrade action to be performed. 

The same behavior is present in v1:

1. Run `porter create`
2. modify helpers.sh to `exit 1` in `install` function
3. Run `porter build`
4. Run `porter install` - it will fail
6. Run `porter list`  - it will show installation as `defined`
7. Run `porter upgrade` - it will pass
8. Run `porter list`  - it will show installation as `defined`

```
$ porter -n test install
executing install action from porter-hello (installation: test/porter-hello)
Install Hello World
Hello World
Error: error running command /cnab/app ./helpers.sh install: exit status 1
exit status 1
1 error occurred:
        * mixin execution failed: exit status 1


1 error occurred:
        * mixin execution failed: exit status 1


1 error occurred:
        * container exit code: 1, message: <nil>


$ porter -n test list
------------------------------------------------------------------------------
  NAMESPACE  NAME             VERSION  STATE        STATUS     MODIFIED
------------------------------------------------------------------------------
  test       porter-hello     0.1.0    defined      failed     9 seconds ago
 
$ porter -n test upgrade
executing upgrade action from porter-hello (installation: test/porter-hello)
World 2.0
World 2.0
execution completed successfully!

$ porter -n test list
------------------------------------------------------------------------------
  NAMESPACE  NAME             VERSION  STATE        STATUS     MODIFIED
------------------------------------------------------------------------------
  test       porter-hello     0.1.0    defined      succeeded  4 seconds ago
```

**Comment by carolynvs** [comment]
"defined" is the state when porter has been asked to create an installation but it has not been installed. It is meant to cover the gap between someone requesting an installation be created in a specific state, such as `porter installation apply myinst.yaml` and when it's finally installed. As it's installing, if you run porter list you'll see it show up as "defined".

Showing up as defined after a run has failed is a bug in the list output logic.

**Comment by jasmdk** [comment]
Would it be possible to cut a new release candidate any time soon? Preferably before Tuesday next week?

**Comment by schristoff** [comment]
This seems to be resolved so I am closing for now :)
