### ISSUE TITLE
Handle re-install an uninstalled bundle

### ISSUE THREAD

**Issue by VinozzZ** [getporter/porter#2356]
**What is your question?**

Currently, Porter assumes an uninstalled bundle is never going to be re-installed. This assumption needs to be re-evaluated since we have users reporting this usage pattern.

**What have you tried already?**

We have found the installation state during `porter installations list`  is not properly handled with above usage pattern. #2353 

**Where have you looked already to figure this out?**

#2354 fixes the display issue.
We should also validate other parts of the code to see if Porter has the desired behavior in this use case.

**Was the existing documentation unclear or had gaps?**

During the investigation, it seems like the meaning of `defined` state is not very clear to users. It maybe helpful to add documentation for different installation state in our documentation

**Comment by carolynvs** [comment]
@VinozzZ Is this a migration issue that needs to be fixed prior to v1? Or is it a display issue only?

**Comment by VinozzZ** [comment]
> @VinozzZ Is this a migration issue that needs to be fixed prior to v1? Or is it a display issue only?

I don't think this is a migration issue. From my perspective, the migration is behaving as expected since both Porter v0.38 and Porter v1 don't handle the use case for reinstalling an uninstalled bundle. The display issue is discovered by through the migration issue. However, it can be reproduced without doing a migration.
This issue is opened to track whether we want to support this use case and validate if the current code already handles this use case correctly. The display issue is only a part of it. 
For example, I'm not sure what other state information is not being updated when reinstall an uninstalled bundle. I would like to validate that before we say it's ok to reinstall an uninstalled bundle

**Comment by carolynvs** [comment]
Let's update the docs to include that this isn't currently supported.

**Comment by schristoff** [comment]
After it is uninstalled that we keep the data if people want to see it. But Porter should follow popular tools and be idempotent and reinstall the bundle, overwriting all previous values. (open to feedback but just my vibes)

**Comment by kichristensen** [comment]
@schristoff I might be missing something, but with Porter 1.0.16 I don't have any problems re-installing an uninstalled bundle

**Comment by kichristensen** [comment]
Closing the issue as it no longer seems to be a problem. Please reopen if that is not the case
