### ISSUE TITLE
Parameter set associated with an installation isn't used unless explicitly specified on the command?

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2364]
## Describe the bug
I have an installation that has a parameter set associate with it (because it was used when the bundle was installed). When I later try to upgrade or uninstall without specifying the parameter set again, the parameter set isn't used and porter complains about required parameters that are not specified.

When I save the installation to a file with a parameter set specified and then run `porter installation apply`, that works just fine. It's only when I run a command like install/upgrade/uninstall.

## To Reproduce
1. Create a bundle with a required parameter.
2. Generate a parameter set with that parameter defined.
3. Install the bundle and specify `-p myparams`.
4. Upgrade the bundle and do not re-specify the parameter set, e.g. `porter upgrade  mybuns` without a `-p myparams`. Note that porter says that you haven't specified a required parameter.
5. Try the upgrade command again, and specify `-p myparams`. This time it works.

## Expected behavior
When a parameter set is associated with an installation, it should be used without having to be specified explicitly.

## Porter Command and Output
```
$ porter install gcloud-test -c gcloud-test -p gcloud-test
BUNDLE OUTPUT TRUNCATED

$ porter uninstall gcloud-test
resolving parameters for installation quickstart/gcloud-test
Resolving parameter sources...
Resolving parameter source porter-state
Injected installation quickstart/gcloud-test output porter-state as parameter porter-state
parameter "project" is required
parameter "project" is required
received EOF, stopping recv loop
plugin process exited
plugin exited

$ porter installation show gcloud-test -o yaml
schemaType: Installation
schemaVersion: 1.0.2
id: 01GDDNB6YMPJGB1NBK99W0KPQY
name: gcloud-test
namespace: quickstart
bundle: {}
credentialSets:
  - gcloud-test
parameterSets:
  - gcloud-test

OUTPUT TRUNCATED
```

## Version
1.0.0-rc.1

**Comment by joshuabezaleel** [comment]
I think I am interested in this but might need some more time to understand the context before I can say that I am able to work on this. 

> When I save the installation to a file with a parameter set specified, that works just fine.
@carolynvs I want to ask for an elaboration on this one but perhaps this is just me that is missing or forgetting something. How do we "save installation to a file with a parameter set specified"?

**Comment by joshuabezaleel** [comment]
Been trying out this one and I'll try to send out a PR in following days.

**Comment by carolynvs** [comment]
@joshuabezaleel I just refactored all of parameter resolution in #2476 which should help a lot. You should wait until that merges first and then it should be much more straightforward to implement.  👍

**Comment by carolynvs** [comment]
This doesn't reproduce after #2476. Closing
