### ISSUE TITLE
Porter ignores credential set parameter for already installed bundles

### ISSUE THREAD

**Issue by jasmdk** [getporter/porter#2372]
## Describe the bug
Once the bundle has been installed using a named credential set, this name is stored in the installation state and used when upgrading or invoking actions on the bundle regardles of which credential set is referenced on the command line. Porter will fail if you reference a non-existing credential-set, but it will still go ahead and use the original one if it is there.

## To Reproduce
1. Create two credential sets (cred1 and cred2) which each point to seperate copies of your kubeconfig file
2. Run `porter install -c cred1`
3. Run `porter upgrade -c cred3` - it fails as cred3 does not exist `not load credentials: cred3 not found`
4. Run `porter upgrade -c cred2` - it succeeds, even though it actually used cred1
5. Remove or rename the kubeconfig that cred1 points to
6. Run `porter upgrade -c cred2`
7. See error:
```
rpc error: code = Unknown desc = open temporary.kubeconfig: The system cannot find the file specified.
not load credentials: 1 error occurred:
        * unable to resolve credential cred1.kubeconfig from path temporary.kubeconfig: rpc error: code = Unknown desc = open temporary.kubeconfig: The system cannot find the file specified.
```
8. Run `porter credential delete cred1`
9. Run `porter upgrade -c cred2`
10. See another error: `not load credentials: cred1 not found`

## Expected behavior
If a credential set is provided from command line, it should be used instead of expecting to find a credential set with the same name as in the original installation.

## Porter Command and Output
See steps to reproduce above with errors printed as they occur.

## Version
Copy the output of `porter version` below

porter v1.0.0-rc.1 (8e005d5c)

**Comment by carolynvs** [comment]
Here is how I'd like to see this work:

1. porter install mybun -c mycreds # use mycreds to install the bundle
2. porter upgrade mybun # use the saved mycreds to upgrade the bundle
3. porter upgrade mybun -c othercreds # replace mycreds with othercreds
4. porter upgrade mybun # use the saved othercreds to upgrade the bundle

i.e. when credentials are specified, they should replace the credentials associated to the installation (not be added to like it is today).

Let me know if that aligns with your expectations or if that would still be a problem. I'd like to get this fixed early next week so that we can include it in a 1.0.0. The fact that we are passing creds to a bundle that the user didn't intend is a big enough problem that I don't want to wait to fix it.

**Comment by jasmdk** [comment]
> Here is how I'd like to see this work:
> 
> 1. porter install mybun -c mycreds # use mycreds to install the bundle
> 2. porter upgrade mybun # use the saved mycreds to upgrade the bundle
> 3. porter upgrade mybun -c othercreds # replace mycreds with othercreds
> 4. porter upgrade mybun # use the saved othercreds to upgrade the bundle
> 
> i.e. when credentials are specified, they should replace the credentials associated to the installation (not be added to like it is today).
> 
> Let me know if that aligns with your expectations or if that would still be a problem. I'd like to get this fixed early next week so that we can include it in a 1.0.0. The fact that we are passing creds to a bundle that the user didn't intend is a big enough problem that I don't want to wait to fix it.
> 
> EDIT: The same logic would also apply when specifying a parameter set. If you specify a credential or parameter set, it replaces the saved ones on the installation.

I agree that your described behavior is aligned with how I would expect it to work. I was not aware of the behaviour about not having to specify the credential set for an already installed bundle, but at least when I provide a credential set I would expect them to be used.

**Comment by carolynvs** [comment]
Agreed. This was never the intended behavior.

**Comment by carolynvs** [comment]
@jasmdk The new behavior is now in [1.0.0-rc.3](https://github.com/getporter/porter/releases/tag/v1.0.0-rc.3).
