### ISSUE TITLE
Kubeconfig file is not being ingested by porter despite being included in credential set

### ISSUE THREAD

**Issue by dlmiller322** [getporter/porter#2458]
## Describe the bug
Kubeconfig file is not being ingested by porter despite being included in credential set. This is happening after upgrading to schemaVersion 1.0.0, whereas there was no issue prior to the upgrade.

## To Reproduce
1. Include kubeconfig in a valid location (such as ./kubeconfig, or /home/vsts/.kube/config) in your credentials JSON file, and create a credential-set with that value.
2. Run porter install on your bundle (porter install <bundle-name> --reference <your container reference> --credential-set <credential set name> --param <for each of your params--we have a lot>.
3. When the porter install starts running and helm upgrade commands start getting called, for each of those we see the following error many times. Example:
Helm Command: "helm upgrade -i namespaces-secrets "./charts/namespaces-secrets-chart" `--set createimagepullcreds="<imagepullcreds here>"
Immediate series of errors:
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Write-Error: 💥 Error running kubectl command
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Write-Error: 💥 Error running kubectl command

## Expected behavior
The helm upgrade commands in the porter install script would be able to connect to the cluster and continue on normally with the bundle install.

## Porter Command and Output
```
porter install <bundle name> --reference <reference here> --credential-set <cred-set-name> --param <key=value> ....

Result:
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
Error: Kubernetes cluster unreachable: Get "[http://localhost:8080/version"](http://localhost:8080/version%22): dial tcp 127.0.0.1:8080: connect: connection refused
False
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Write-Error: 💥 Error running kubectl command
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Write-Error: 💥 Error running kubectl command
```

## Version
latest

**Comment by carolynvs** [comment]
@dlmiller322 The destination location of the kubeconfig file changed from v0 to v1, because the bundle no longer runs as root. Check your credential definitions in porter.yaml, look for `path: /root/kubeconfig` and replace it with `path: /home/nonroot/.kube/config`.

Here's an example bundle that shows what will work going forward with v1

https://github.com/getporter/examples/blob/e6d61617d9c4ae425d8e45f83c83b78321cd08fd/kubernetes/porter.yaml#L11-L13

**Comment by dlmiller322** [comment]
@carolynvs Thanks for the explanation. I have tried replacing the path in the credentials with both `/home/nonroot/.kube/config` and `/home/vsts/.kube/config`, since we are running this through an Azure pipeline and I believe vsts is what porter is running as (please do correct me if I'm wrong on this--I'll include a list of the directories that exist under /home below).

In the case of the former attempt, vsts did not have permissions to create a `/home/nonroot` directory, so the mkdir command failed.

In the case of the latter attempt, our pipeline was able to create the needed directories and copy the kubeconfig, once it was generated, over to `/home/vsts/.kube/config`, but then later on when attempting to connect to the cluster as described above, we got the same errors as before.

Here are the directories that currently exist under /home:
```
drwxr-xr-x+  5 root             root             4096 Nov 11 15:27 .
drwxr-xr-x  21 root             root             4096 Nov 15 13:39 ..
drwxr-xr-x+  9 VssAdministrator VssAdministrator 4096 Nov 11 15:27 VssAdministrator
drwxr-xr-x+  3 vsts             docker           4096 Oct 27 22:37 linuxbrew
drwxr-xr-x  16 vsts             docker           4096 Nov 15 13:53 vsts
```

Is there a user in that list that we should be using instead of `nonroot`, or is there something else I might be missing here?

Thanks again for your assistance!

**Comment by carolynvs** [comment]
When a bundle is run with `porter install`, it executes a docker container that was created during porter build. New bundles built with porter v1, are all configured with a nonroot user and a /home/nonroot directory _inside the docker image filesystem_.

So vsts and the files on your CI agent are not involved at all.

Your porter.yaml should have an entry for a kubeconfig credential, and that is the only place that should use the /home/nonroot/.kube/config filepath. Nothing on the actual host (a vsts agent) should try to use that path.

```yaml
# porter.yaml
# This defines where the kubeconfig file is put when injected into the bundle's docker container when it runs
credentials:
- name: kubeconfig
  path: /home/nonroot/.kube/config
```

The other path you need to think about is the path where the kubeconfig is retrieve by Porter before injecting it into the bundle's docker container. That is the credential set.

In the example below, my credential set is telling porter to find `$HOME/.kube/config` on the local host, and then inject that file into the bundle when it's run with `porter install --credential-set mycluster`

```
$ porter credentials show mycluster -o yaml
schemaVersion: 1.0.2
name: mycluster
created: 2022-10-27T08:46:25.206516-05:00
modified: 2022-10-27T08:46:25.206516-05:00
credentials:
  - name: kubeconfig
    source:
      path: $HOME/.kube/config
```

If you continue to run into problems, please include your porter.yaml, your credentials file, and the porter command that you are using to run the bundle so we can troubleshoot.

**Comment by dlmiller322** [comment]
Thank you so much @carolynvs, that is VERY helpful! I'll try what you said and update if I have any more questions.

Thanks again!

**Comment by dlmiller322** [comment]
That resolved the issue! Now on to further troubleshooting, but no more kubeconfig-related errors.

Thanks again Carolyn, I really appreciate your help. Have a great day!

**Comment by carolynvs** [comment]
Yay 🎉  I'm glad it's working.
