### ISSUE TITLE
Lint warnings are not printed

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2525]
When I run `porter lint` and there is a lint warning (not an error), the warning isn't printed to the console. Both errors and warnings should be printed.

This is hard to reproduce because I noticed this while testing a pull request that was generating a warning. Once #2434 is merged, you can reproduce this by editing [pkg/linter/linter.go](https://github.com/getporter/porter/blob/6df27907b5a40482ceb8c036fede2fa56a518c16/pkg/linter/linter.go#L155) and change the the level of porter-100 from an error to a warning. Then rebuild and run porter against a bundle that has a parameter named "porter_test". You should see a warning printed out for porter-100 (but currently it doesn't).

3. porter create
4. Edit porter.yaml and define a parameter named "porter_test"
5. Run porter lint

The problem is in https://github.com/getporter/porter/blob/6df27907b5a40482ceb8c036fede2fa56a518c16/pkg/porter/lint.go#L74-L77

We are checking if there are any errors and then exiting the function without printing any results. We should move that check to _after_ printing out the results.

This is hard to unit test because we don't have anything that prints a warning at this time, so you can skip adding a test. Make sure to test manually.

See our [Contributing Tutorial](https://getporter.org/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/release/v1/CONTRIBUTING.md) for help getting started contributing to Porter.

**Comment by jmhbnz** [comment]
This looks like a pretty straightforward fix for a new contributor so I've picked this up. Will have a pull request open later today.
