### ISSUE TITLE
Use common SetupDCO mage target in all repos

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2535]
All repositories should have a mage.go/magefile.go with at least the SetupDCO target that uses the git.SetupDCO helper function from get.porter.sh/magefiles@v0.4.0

The CONTRIBUTING.md for each repository should include a section that explains the magefile targets and calls out that commits should be signed and how to use the SetupDCO target.

Here are examples from some of our repos that already use it:

* https://github.com/getporter/porter/blob/main/CONTRIBUTING.md#signing-your-commits
* https://github.com/getporter/vscode-extension/blob/main/CONTRIBUTING.md is a great example of what should be in the CONTRIBUTING.md for a project that isn't a normal porter/go repo. Note how it still explains how to get started with the project, has custom setup instructions that are reasonable for the current repo (not just reusing porter's usual contribute tutorial), etc.

See our [Contributing Tutorial](https://getporter.org/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/main/CONTRIBUTING.md) for help getting started contributing to Porter.

**Comment by schristoff** [comment]
Most of our repos outside of this one could benefit from this, that includes [operator](https://github.com/getporter/operator), [examples](https://github.com/getporter/examples), [magefiles](https://github.com/getporter/magefiles), [kubernetes plugin](https://github.com/getporter/kubernetes-plugins)

**Comment by jaydee029** [comment]
Hi , @carolynvs I would like to work on this.
