### ISSUE TITLE
nav on mobile website

### ISSUE THREAD

**Issue by Arhell** [getporter/porter#2558]
![Screenshot_1](https://user-images.githubusercontent.com/26163841/217533255-bab96737-622b-455c-92b0-37f48116dd69.png)

**Comment by carolynvs** [comment]
Thanks for reporting this! If you are interested in improving the website, we would really appreciate the help.

**Comment by Arhell** [comment]
> Thanks for reporting this! If you are interested in improving the website, we would really appreciate the help.

Of course I just want to do this.
