### ISSUE TITLE
Regression: go-containerregistry changed archive/hash behavior

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2703]
The other day we got a dependabot PR bumping go-containerregistry #2664. Unfortunately the integration tests in Azure Pipelines did not kick off at all AND we didn't have our branch protection rule set to require `porter-integration` as a status check so it looked like the PR was safe to merge.

Narrator: It was not.

Bumping go-containerregistry has a breaking change that caused our archive files to change their hash. This is causing TestArchive_StableDigest to fail because the expected hash is different.

For now we need to revert that change, and then evaluate what changed in go-containerregistry and how that impacts our archives, and if there's a way to not have the hash of our archives change. Otherwise we'll need to communicate to people that it's changing and when, since I anticipate that some users are checking the tgz hash when moving across an airgap.

**Comment by carolynvs** [comment]
I have fixed our branch protection rules to include both porter AND porter-integration.

**Comment by kichristensen** [comment]
@schristoff What do we want to do here? The dependency have been updated multiple times since v1.1.5, we are now using v1.1.12. The time for avoiding the change is gone, as we have released two versions of Porter with the the updated dependency.

**Comment by schristoff** [comment]
Haha, whoops. 
Well, it seems like no one has commented so maybe not a breaking change? 🙃🙃
