### ISSUE TITLE
content goes beyond block boundaries on mobile

### ISSUE THREAD

**Issue by Arhell** [getporter/porter#2717]
## Describe the bug
https://getporter.org/blog/porter-collaboration/
![Screenshot_1](https://user-images.githubusercontent.com/26163841/231139820-fb751955-e895-4551-88c6-798071e5599b.png)

**Comment by carolynvs** [comment]
Oh this has bothered me for a long time. The blog page with those tags and author blurb often don't render right, even on larger screens. It would be great to have that fixed 🎉

**Comment by Arhell** [comment]
Of course, if there is something that I don't notice or don’t find, please create a new issue and ping me
