### ISSUE TITLE
install-linux.sh 'latest' is producing a 404 error

### ISSUE THREAD

**Issue by samjohnsonCF** [getporter/porter#2723]
## Describe the bug
When grabbing the 'latest' version of porter from https://cdn.porter.sh/latest/install-linux.sh it is trying to pull v1.0.13. Which is producing a 404 error as it does not seem to exist. v1.0.11 I know works as is stated to be 'latest' right now.

## To Reproduce
curl -L -f https://cdn.porter.sh/latest/install-linux.sh -O
less install-linux.sh

## Expected behavior
Expected to install porter and not get a 404 error

## Porter Command and Output

Installing porter@v1.0.13 to /Users/sjohnson/.porter from https://cdn.porter.sh
curl: (22) The requested URL returned error: 404

## Version
v1.0.13

**Comment by samjohnsonCF** [comment]
Literally as I typed this up, it got updated to v1.0.13. I think we are too quick apparently. 
Just a thought/update for the future. Is it possible to the official version updated before the install script is updated? I saw a 5 to 10 min gap before that script worked.

**Comment by carolynvs** [comment]
Yeah when we make the release, we shouldn't let it be flagged as latest. Then after all assets have been uploaded, then mark it as latest. I'm pretty sure that's what went wrong, there is this limbo period between when the gh cli creates the release and when all the assets are available.

**Comment by samjohnsonCF** [comment]
@carolynvs That totally makes sense! Our pipelines are just too fast for ya'll then :-p.
I'll go ahead and close this out though as its no longer a bug.

**Comment by carolynvs** [comment]
Let's leave this open since I didn't realize the lag was that bad. I think the fix is pretty straightforward and will try to sneak it in before our next release
