### ISSUE TITLE
In QucikStart: Bundles should v0.1.0 be changed to v0.2.0?

### ISSUE THREAD

**Issue by Exar04** [getporter/porter#2769]
**What is your question?**
In QucikStart: Bundles we are installing v0.2.0 but below its written " *installing v0.1.0* "

<img width="941" alt="Screenshot 2023-05-29 at 5 27 19 PM" src="https://github.com/getporter/porter/assets/109629956/e3890681-63db-418b-9e8e-be2f03170617">
 
The name of the bundle i installed is named *examples/porter-hello* but in docs its written *HELLO*

what i got -
<img width="629" alt="Screenshot 2023-05-29 at 5 25 54 PM" src="https://github.com/getporter/porter/assets/109629956/bf6de864-e80f-4837-80a3-4c9f1a408703">
What is in the documentation -
<img width="713" alt="Screenshot 2023-05-29 at 5 38 49 PM" 
src="https://github.com/getporter/porter/assets/109629956/9bbbe21b-56d1-4b05-897e-600b18138aeb">

**What have you tried already?**

**Where have you looked already to figure this out?**

**Was the existing documentation unclear or had gaps?**

**Comment by schristoff** [comment]
I can reproduce successfully:
```
porter explain ghcr.io/getporter/examples/porter-hello:v0.2.0

Name: examples/porter-hello
Description: An example Porter configuration
Version: 0.2.0
```

Happy to take a PR to the documentation to fix this :)
