### ISSUE TITLE
porter create command should create directory with bundle files included

### ISSUE THREAD

**Issue by phillipgibson** [getporter/porter#2772]
**What design is being proposed?**
When using porter create <mybundle>, the command will create all the files associated with the bundle in the current directory where ran. For a cleaner file system organization, a directory of the bundle name should be made with the files for the bundle created in that directory. 

**Additional Context**
This functionality saves a step for the user. An example of this is how Rust uses the cargo new <program> command. 

**Risks/Concerns**
None that I'm aware of. 

**What other approaches were considered?**
None

**Implementation details**
portal create mybundle
cd mybundle
ls - porter.yaml, README.md template.Dockerfile, etc.

# Checklist
- [ ] An announcement of this proposal has been sent to the Porter mailing list: https://getporter.org/mailing-list
- [ ] This proposal has remained open for at least one week, to allow time for community feedback.

**Comment by schristoff** [comment]
This functionality is also how `helm create` works, for anyone taking a peek at this issue it may be good to pull inspiration from their implementation [here](https://github.com/helm/helm/blob/main/cmd/helm/create.go#L100)
