### ISSUE TITLE
release: update release pipeline to modify version in docs 

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2776]
## Describe the bug
[Installation documentation](https://github.com/helm/helm/blob/main/cmd/helm/create.go#L100) for Porter shows `version="v1.0.1"` - this is problematic due to `debian:stretch` being EOL'd and so anyone trying to do anything gets a ton of errors.

## Expected behavior
We should really update the release pipeline to update these versions in the documentation for us. But  - we can also just take a PR for someone to update these strings and I'll leave this issue open until we get around to updating the release pipeline. 
[Release Pipelines are here](https://github.com/getporter/porter/tree/main/build)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue
