### ISSUE TITLE
feat: Add stalebot to help with PRs/Issues

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2796]
**Is your feature request related to a problem? Please describe.**
It would be useful to have a couple more helpers around to help with day to day maintenance and monitoring of issues & PRs in Porter. Stalebot could help us keep our focus on current issues and ping us on PRs that we may have forgotten about.

**Describe the solution you'd like**
Implement Stalebot but in a sustainable way. Certain tags on PRs should be ignored (ex: pep003, or perhaps any pep tag?, docs should be ignored)
It will take some discussion and fine tuning to find exactly the best way it works in our community.

**Comment by sbdtu5498** [comment]
I will take care of it. I am currently working on something that can help solve this problem in the wider CNCF community. Those sets of GitHub actions fit the description so you can use some of those as per your requirements. Though it is not yet complete, but would be available soon.

**Comment by AGMETEOR** [comment]
@sbdtu5498 is it ok if I take this off your plate?

**Comment by sbdtu5498** [comment]
@AGMETEOR Sure you can go ahead and add something if you have. I am working on a general template anyways. So once it would be done. I can also be integrated apart. But if you want to work on it right now, please go ahead.

**Comment by AGMETEOR** [comment]
Alright. Thanks.

**Comment by AGMETEOR** [comment]
Hey @schristoff could I get assigned this issue?

**Comment by sbdtu5498** [comment]
You can start working on this one, I think it's alright even if it is not assigned.
