### ISSUE TITLE
feat: Automate changelog.md

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2797]
**Is your feature request related to a problem? Please describe.**
Having a well documented changelog is crucial for bug finding and enabling our users to be informed on our changes before they update. But keeping a changelog up to date is hard with everything else going on, and so enabling us (and our community) to be able to easily update the changelog with each change would be great. 

**Describe the solution you'd like**
Implement something like [go-changelog](https://github.com/hashicorp/go-changelog) or similar in here and the operator (at least)

**Comment by basit9958** [comment]
This can be solved by creating simple github action to must update changelog. I will add this
