### ISSUE TITLE
Docs - what-is-porter.md update

### ISSUE THREAD

**Issue by phillipgibson** [getporter/porter#2801]
Reading this sentence makes me really not like the `s/invocation images/bundle installers/` I just did - if we can come up with a better name I'm down tho

_Originally posted by @schristoff in https://github.com/getporter/porter/pull/2790#discussion_r1243116805_

**Comment by kelvinparmar** [comment]
Hey @phillipgibson I want to contribute in this project can you help me how can I?

**Comment by sbshah97** [comment]
Hi @schristoff didn't really get what you meant down here? Any chance you could help ?

**Comment by schristoff** [comment]
Hi @sbshah97  and @kelvinparmar ! This was a note I left while we were moving our documentation around for us in the future to use when revisiting our docs. I would reference this issue #2798  - and if you'd like to contribute I would encourage you to come hang out at our community meetings that are Thursday (there's one 2/8) at 9AM MST. :) Happy to answer any other questions.

**Comment by kichristensen** [comment]
Rename have been done in #3200
