### ISSUE TITLE
Failed to publish to docker registry

### ISSUE THREAD

**Issue by AGMETEOR** [getporter/porter#2834]
## Describe the bug
Failed to publish bundle to `hub.docker.com`

## To Reproduce
1. Run `porter publish --registry hub.docker.com` or `porter publish --registry hub.docker.com/r/agmeteor`
2. Use the default porter.yaml file from the porter-hello example https://getporter.org/getting-started/create-bundle/
3. See error
```log
reference not found (hub.docker.com/r/agmeteor/porter-hello:v0.1.0)
Pushing bundle image...
The push refers to repository [hub.docker.com/r/agmeteor/porter-hello]
5f70bf18a086: Preparing
d9aa768d9bdd: Preparing
c6d0867dbe69: Preparing
e5ec85adb079: Preparing
318f55ac9136: Preparing
0a3fec6d3c7d: Preparing
b85f69b0b2d2: Preparing
f9f342925acf: Preparing
a5f82b0a6298: Preparing
34f03f266053: Preparing
0a3fec6d3c7d: Waiting
b85f69b0b2d2: Waiting
f9f342925acf: Waiting
a5f82b0a6298: Waiting
34f03f266053: Waiting
failed to stream docker push stdout: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!doctype html>\n<html lang=\"en\">\n\n<head>\n ...
```

## Expected behavior
I expected to see my oci artifact on docker registry

## Version
`porter v1.0.14 (0e739d88)`

**Comment by itsaviral2609** [comment]
![Screenshot from 2023-07-23 00-23-40](https://github.com/getporter/porter/assets/96782675/6e5d2621-2295-44f7-9184-5b30e80c2705)

Tried this issue, worked fine for me!

Here is the porter.yaml file

![Screenshot from 2023-07-23 01-46-07](https://github.com/getporter/porter/assets/96782675/5577ba06-fe18-46bf-a660-49c106844e42)

**Comment by AGMETEOR** [comment]
Thanks @itsaviral2609 . You're right it works just fine using `porter publish --registry=docker.io/<my_reg_name>`. I don't know why I thought `hub.docker.com` was the name of the registry.

**Comment by AGMETEOR** [comment]
I'll close this now.

**Comment by itsaviral2609** [comment]
cool! Happy yo help @AGMETEOR :)
