### ISSUE TITLE
porter installation list advanced filtering

### ISSUE THREAD

**Issue by Lybecker** [getporter/porter#2871]
**Is your feature request related to a problem? Please describe.**
The current filtering capabilities of `[porter installation list](https://porter.sh/cli/porter_installations_list/)` is limited.

We would like to be able to:
- Filter on state e.g. installed/uninstalled (https://github.com/getporter/porter/pull/2775 tries to solve this)
- Filter on version of bundle

To be able to do more advanced queries like:
- Find bundle X with version Y across all namespaces

**Describe the solution you'd like**
I would like a solution like [kubectl field selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/).

This will enable us to query like `porter installation list --name=X --version=y --all-namespaces`

**Comment by Lybecker** [comment]
cc @squillace

**Comment by maniSbindra** [comment]
Hi @schristoff If this is not assigned to anyone, I can work on this one.

Thanks,
Mani

**Comment by ludfjig** [comment]
@maniSbindra I just started working on this last night (not finished). Would you like to take over the PR? #2880

**Comment by maniSbindra** [comment]
> @maniSbindra I just started working on this last night (not finished). Would you like to take over the PR? #2880

Hi @ludfjig sure please carry on. I will not work on this any further. I do have a solution working locally, which uses the reflect package to filter installations based on--field-selector arguments.

**Comment by ludfjig** [comment]
> > @maniSbindra I just started working on this last night (not finished). Would you like to take over the PR? #2880
> 
> Hi @ludfjig sure I can take over the PR. I started looking at this earlier today. I do have a solution working locally which uses the reflect package to filter installations list based on--field-selector arguments.

great, thanks
