### ISSUE TITLE
docs: use hugo ref/relref shortcodes for md links

### ISSUE THREAD

**Issue by ludfjig** [getporter/porter#2881]
**What design is being proposed?**
Use the hugo [ref/relref shortcodes](https://gohugo.io/content-management/shortcodes/#example-ref-and-relref-input) for [linking ](https://gohugo.io/content-management/cross-references/)between pages in our docs. This will enable us to automatically detect broken links at build time.

**Comment by Aayush987** [comment]
Hi, i would like to work on it. Can you assign it to me ?

**Comment by ludfjig** [comment]
> Hi, i would like to work on it. Can you assign it to me ?

done :)

**Comment by Aayush987** [comment]
@ludfjig hi, just for the confirmation , i have to use hugo rel and relref shortcodes for all the interlinking of the pages in the docs, right?

**Comment by ludfjig** [comment]
@Aayush987 I realize that this is a bunch of boring manual work, and I'm not even sure short codes are what we want. It's possible there are better ways to do this. 

For example, I found [this](https://github.com/marccampbell/hugo-linkcheck-action) which might be much easier. Perhaps you could investigate if there are other ways to detect broken links with Hugo, and if you find that creating a github workflow would be best, you could try adding it to our repo.

**Comment by Aayush987** [comment]
> @Aayush987 I realize that this is a bunch of boring manual work, and I'm not even sure short codes are what we want. It's possible there are better ways to do this.
> 
> For example, I found [this](https://github.com/marccampbell/hugo-linkcheck-action) which might be much easier. Perhaps you could investigate if there are other ways to detect broken links with Hugo, and if you find that creating a github workflow would be best, you could try adding it to our repo to see if it works.

OK, I will look into it .

**Comment by Aayush987** [comment]
> @Aayush987 I realize that this is a bunch of boring manual work, and I'm not even sure short codes are what we want. It's possible there are better ways to do this.
> 
> For example, I found [this](https://github.com/marccampbell/hugo-linkcheck-action) which might be much easier. Perhaps you could investigate if there are other ways to detect broken links with Hugo, and if you find that creating a github workflow would be best, you could try adding it to our repo to see if it works.

Hi, i also think this workflow is the best method . I will start creating this workflow.

**Comment by illume** [comment]
There's a blog post here on setting up link checking for hugo in a github action workflow:
https://robb.sh/posts/check-links-in-hugo-with-htmltest/
