### ISSUE TITLE
feat: Website theme change & asset creation

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2884]
Our website needs some love! 
I am not a website designer and do not have the eye for UX, but I would love to get anyone with that type of experience to give us their input. What type of content should be on the front page? What is a good call to action? What types of websites attract our target user, and which deter them? 
(In this case, should we theme the website to look like hackernews? :P ) 

[I am currently looking at switching the website theme over to](https://github.com/getporter/porter/issues/2885) [docsy](https://www.docsy.dev/) - as it has a search function in the docs section and many other CNCF projects use it.

Any help or input is welcome :)

**Comment by kumarankit999** [comment]
I Can work on this @schristoff

**Comment by schristoff** [comment]
It is done (salute)
