### ISSUE TITLE
feat: Update Hugo Template to Docsy

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2885]
I believe [Docsy](https://www.docsy.dev/) would be the easiest lift and shift that suites our needs as a product, but I am open to other solutions. I have not scoped out the work to move our website theme.

**Comment by kumarankit999** [comment]
Can I work on this issue, I would love to help this out

**Comment by schristoff** [comment]
Sure @kumarankit999 - we would love the help! 
I don't think it's going to be an easy 'lift and shift', but when you make a PR it should publish any changes to netlify so that we can all view them too. If you get stuck or need any feedback quickly, I highly suggest the #porter channel in the CNCF slack as well, as all the maintainers are sitting in there :)

**Comment by zelfroster** [comment]
> Sure @kumarankit999 - we would love the help! I don't think it's going to be an easy 'lift and shift', but when you make a PR it should publish any changes to netlify so that we can all view them too. If you get stuck or need any feedback quickly, I highly suggest the #porter channel in the CNCF slack as well, as all the maintainers are sitting in there :)

I would also love to help. I have built my site with Hugo, so I have some experience.

**Comment by zelfroster** [comment]
> I believe [Docsy](https://www.docsy.dev/) would be the easiest lift and shift that suites our needs as a product, but I am open to other solutions. I have not scoped out the work to move our website theme.

Hello @schristoff, I have been looking into some Hugo themes for documentation. And this one looks promising, https://getdoks.org/ . Please check this out.
And, Kindly tell me if we should proceed with that. One more thing, The documentation part is not dependent on porter installation and running, right?

**Comment by schristoff** [comment]
Hi @zelfroster  - posting in here (even though addressed in Slack)
Doks is totally great! I think it's a cool theme.
The documentation part is not dependent on a porter installation - that is correct :)

**Comment by schristoff** [comment]
❗  Omg, I love it. It looks very modern, sleek, what a great choice! 
Thank you so much for creating a preview as well. 
Once the port over to Hextra is done I think the next step will be to spruce up that homepage. 
I'll nitpick on the format of the homepage and such when we get a PR up and ready. I cannot overstate how jazzed I am to see this. :)

**Comment by zelfroster** [comment]
> ❗ Omg, I love it. It looks very modern, sleek, what a great choice! Thank you so much for creating a preview as well. Once the port over to Hextra is done I think the next step will be to spruce up that homepage. I'll nitpick on the format of the homepage and such when we get a PR up and ready. I cannot overstate how jazzed I am to see this. :)

Thank you so much <3 !!
I will start the work with a draft PR soon. Please assign this issue to me.
