### ISSUE TITLE
Integration Tests fail on Windows

### ISSUE THREAD

**Issue by ludfjig** [getporter/porter#2908]
## Describe the bug
The following integration tests fail on windows:
```
--- FAIL: TestExecute (0.00s)
    agent_test.go:58:
                Error Trace:    C:/Users/lliljenberg/dev/porter/pkg/agent/agent_test.go:58
                                                        C:/Users/lliljenberg/dev/porter/pkg/agent/agent_test.go:17
                Error:          Received unexpected error:
                                no such file or directory '../../bin/porter'
                Test:           TestExecute
```
TestExecute fails because it assumes the porter binary has no .exe extension AND because the repo contains unix symlinks, which cannot be resolved on windows.

```
--- FAIL: TestPorter_FixPermissions (1.47s)
--- FAIL: TestPorter_FixPermissions_NoConfigFile (1.15s)
--- FAIL: TestResolveBundleReference (0.00s)
--- FAIL: TestResolveBundleReference/reference (2.14s)
--- FAIL: TestInstall_stringParam (1.25s)
--- FAIL: TestRegistry (16.80s)
--- FAIL: TestTelemetrySetup (7.52s)
--- FAIL: TestInvokeCustomAction (3.34s)
--- FAIL: TestStepLevelAndBundleLevelOutputs (3.38s)
--- FAIL: TestPull_ContentDigestMissing (3.44s)
--- FAIL: TestInstall_fileParam (3.62s)
--- FAIL: TestInstall_relativePathPorterHome (3.71s)
--- FAIL: TestArchive_StableDigest (3.78s)
--- FAIL: TestSuppressOutput (4.31s)
--- FAIL: TestExecOutputs (2.40s)
--- FAIL: TestInstall_withDockerignore (2.69s)
--- FAIL: TestSensitiveData (2.54s)
--- FAIL: TestDependenciesLifecycle (2.72s)
```
The above tests needs investigation. I know some of them fail because Porter assumes unix file permission bits. 

Update: Many of them fail when a json which contains a windows path (instead of a unix path) with single backslash is unmarshalled. This makes sense since the json spec requires double backslash to indicate a backslash. For example
```
{
"path": "C:\Users\lliljenberg\dev\porter\build\testdata\credentials\ci.json"
}
```
is invalid json, we need to turn it into
```
{
"path": "C:\\Users\\lliljenberg\\dev\\porter\\build\\testdata\\credentials\\ci.json"
}
```

## To Reproduce
1. Run `mage testintegration` on a windows machine

## Expected behavior
All tests should pass

## Version
Copy the output of `porter version` below

porter v1.0.15-24-g513c0a03 (513c0a03)

**Comment by troy0820** [comment]
This function 
```go
func makeTestPorterHome(t *testing.T) string {
      home, err := os.MkdirTemp("", "porter-home")
      require.NoError(t, err)
      require.NoError(t, shx.Copy("../../bin/porter", home))
      return home
    }
```
is heavily reliant on the file system being this way.  We probably shouldn't be doing this at all when it comes to platform specific things if we intend to be agnostic. 

If we are making a specific directory to use "porter" it shouldn't be specific to the path of where it is being built relative to where the tests run.

**Comment by troy0820** [comment]
Also, is there a way we can do these tests in windows in github actions?

**Comment by ludfjig** [comment]
> Also, is there a way we can do these tests in windows in github actions?

@troy0820 this is something I have spent too much time on. Unfortunately we require Docker Desktop on windows so we cannot use the github hosted runners. I've been trying to create a windows OS image with Docker Desktop using Packer, but it is hard because it requires wsl2, which doesn't have a good unattended installation process :(
