### ISSUE TITLE
Kind is running 1.23.4 for integration tests 

### ISSUE THREAD

**Issue by troy0820** [getporter/porter#2909]
## Describe the bug
When running `mage tetsintegration` kind is loaded with an image of 1.23.4 

## To Reproduce
`mage testintegration`

## Expected behavior
To run integration tests with at least 1.27.1

**Comment by ludfjig** [comment]
@troy0820 I believe Porter uses whatever you have on path, and if it's missing, Porter is set to download it. Currently it's set to downlad kind version v0.12.0, and latest stable kubectl.

**Comment by troy0820** [comment]
In the pipeline it does an `EnsureKind` and the defaultKind version is v0.12.0 which creates clusters at 1.23.x.  I was hoping to get this updated to use kind v0.20.0, just need to update the magefiles dependency to use v0.6.1-0 _(which is main)_

`go get get.porter.sh/magefiles@main`
