### ISSUE TITLE
Flakey Bundle reuse test

### ISSUE THREAD

**Issue by devigned** [getporter/porter#2948]
In PR #2947 the bundle reuse test was commented out because it was causing build flakes. This is a reminder issue to determine the root cause and to fix it.

**Comment by kichristensen** [comment]
@schristoff I can not get this this to fail when running on Github Actions, in this run, https://github.com/kichristensen/porter/actions/runs/8561906733/job/23464129569, I have bumped to loop from 5 to 100 without any issues, also locally I cannot get it to fail
