### ISSUE TITLE
Docker ACI context support with CNAB Docker Driver

### ISSUE THREAD

**Issue by KurtSchenk** [getporter/porter#2951]
**Is your feature request related to a problem? Please describe.**

Docker support Azure Container Instance (ACI):
1. [Deploying Docker containers on Azure | Docker Docs](https://docs.docker.com/cloud/aci-integration/)
2. After create an acicontext, you can run a container in ACI like this "docker --context myacicontext run -p 80:80 nginx"

Is it possible to have the CNAB Docker Driver use --context?

**Describe the solution you'd like**
porter CLI passes --context to Docker to that acicontext is used

**Describe alternatives you've considered**
[deislabs/cnab-azure-driver: Azure CNAB Driver (github.com)](https://github.com/deislabs/cnab-azure-driver) currently only supports Porter v0. 

**Additional context**
N/A

**Comment by schristoff** [comment]
This should be fixed now, we'll cut a new release with this next weel :)
