### ISSUE TITLE
Release v1.0.16 does not include binaries

### ISSUE THREAD

**Issue by jarnfast** [getporter/porter#2970]
## Describe the bug
The just released `v1.0.16` of porter does not include any binaries.

It appears that the release was done manually and not by getporterbot.

## To Reproduce
1. Go to the release page https://github.com/getporter/porter/releases/tag/v1.0.16
2. Expand the assets
3. Attempt to find the binaries your favorite OS

## Expected behavior
I expect to find a bunch of binaries for a variety of OSes for both porter and mixins, see example: https://github.com/getporter/porter/releases/tag/v1.0.15

**Comment by schristoff** [comment]
I'm working on this currently, the GHA conversions mucked up some things, apologies

**Comment by schristoff** [comment]
Fixed now, thank you for your patience :)
