### ISSUE TITLE
 getporter.org is down

### ISSUE THREAD

**Issue by codebanesr** [getporter/porter#3009]
The porter website tagged on github is not functional
<img width="712" alt="Screenshot 2024-03-08 at 3 35 30 PM" src="https://github.com/getporter/porter/assets/17947802/2378838e-a498-4734-aaa9-49389cab70ef">

**Comment by schristoff** [comment]
Crap, on this right now.

**Comment by schristoff** [comment]
I switched this over to point at https://porter.sh - this may take a little bit of time to resolve in the meantime. :(

**Comment by kichristensen** [comment]
@schristoff It seems like getporter.org is now up again and redirecting to porter.sh, do you want to stop redirecting or keep the redirect?

**Comment by schristoff** [comment]
I'll update the DNS so it's an alias and not a redirect, but I'll close this issue since we are back in business :)
