### ISSUE TITLE
Mixin idea: OpenTofu

### ISSUE THREAD

**Issue by kichristensen** [getporter/porter#3038]
**Is your feature request related to a problem? Please describe.**
Currently there is a lot of stir around Terraform and HashiCorp. Having a dedicated mixin for [OpenTofu](https://opentofu.org/) or adapting the Terraform mixin to also support OpenTofu could be valuable.

**Describe the solution you'd like**
A mixin that supports OpenTofu

**Describe alternatives you've considered**
Having users manually build an invocation image supporting OpenTofu, but that would seem weird based on the fact the Porter already have a Terraform mixin, so why not also support OpenTofu?

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by dgannon991** [comment]
I know it's not slated for v1.1.0, but I'd be interested in giving this a look, I haven't done anything relating to mixins yet :)

**Comment by kichristensen** [comment]
@dgannon991 You are more than welcome to take a look at this one. It hasn't been discussed if a OpenTofu mixin is something that will be maintained in the Porter organization yet. Until that has been discussed development have to be done in a separate Github organization, most likely your own.

**Comment by kichristensen** [comment]
@dgannon991 It has been decided to try and get an OpenTofu mixin ready for the the 1.2.0 release, if you are still interested.

**Comment by dgannon991** [comment]
@kichristensen - I'd love to take a punt at it, and I was hoping to pick up something a bit larger to get my teeth sunk into! It would be good to get an initial direction on if we fork this and duplicate it so they can live separate lives, or if we try and make this single repo able to build both the mixins? (as currently they're meant to be binary compatible)
