### ISSUE TITLE
Add documentation on connecting to AKS

### ISSUE THREAD

**Issue by kichristensen** [getporter/porter#3173]
https://porter.sh/docs/integrations/aks/ currently only contains "Coming Soon". We should add a description similar to the ["Connect to GKE"](https://porter.sh/docs/integrations/gke/) describing how to connect to AKS

**Comment by dejanu** [comment]
Hej @kichristensen, recently I had to integrate with AKS, so I hope this doc is helpful.

**Comment by kichristensen** [comment]
@dejanu Thank you very much. I have added a few small comments, but it looks really good
