### ISSUE TITLE
Offline Environment Error: Unable to Pull Mongo Image in Porter v1.1.0

### ISSUE THREAD

**Issue by jmcudd** [getporter/porter#3198]
## Describe the bug
When using Porter in an offline environment, it attempts to pull the `mongo:4.0-xenial` image, resulting in an error due to the lack of internet connectivity. This prevents the successful execution of Porter commands that rely on this image.
## To Reproduce
1. Install the Porter binary in an offline environment.
2. Run the command `porter list`.
3. See the error message regarding the inability to pull the `mongo:4.0-xenial` image.
## Expected behavior
I expected the `porter list` command to execute successfully and list the installations without attempting to pull any external dependencies, as the environment is offline.
## Porter Command and Output
```
$ porter list
rpc error: code = Unknown desc = error pulling mongo:4.0-xenial: 
could not list installations: could not read storage schema document: rpc error: code = Unknown desc = error pulling mongo:4.0-xenial: 
could not list installations: could not read storage schema document: rpc error: code = Unknown desc = error pulling mongo:4.0-xenial:
```
## Version
```
porter v1.1.0
```

**Comment by kichristensen** [comment]
@sgettys I seem to remember you talking about this some time ago. What was the output of that? Can't remember

**Comment by jmcudd** [comment]
I also experience it with `porter install`. 

Looking at the [documentation](https://porter.sh/docs/configuration/configuration/#config-file) there is mention of mongo in the Porter Config File, but its not clear to me what else it can be set to. 

I also tried pulling the `mongo:4.0-xenial` image into my environment and loading it into docker and that had no effect.

**Comment by jmcudd** [comment]
I found some more useful [docs here](https://github.com/getporter/porter/blob/main/docs/content/plugins/mongodb.md ). Looks like I may be able to just run mongo and connect to it by updating my porter config.

**Comment by jmcudd** [comment]
I believe I've come up with a work-around. This obviously doesn't solve all the other offline issues like mixins, but it does appear as though the `exec` mixin works out of the box.

**Steps:**
1. Download `mongo:4.0-xenial`
2. Run Mongo in docker with the name: `porter-mongodb-docker-plugin` and port `27018`
```
docker run --name porter-mongodb-docker-plugin -d -p 27018:27017 -v mongodb_data:/data/db --restart always mongo:4.0-xenial
```

**Result:**
```
$ porter list
------------------------------------------------------------
  NAMESPACE  NAME  VERSION  STATE    STATUS  MODIFIED       
------------------------------------------------------------
```
