### ISSUE TITLE
Security Vulnerabilities Found in Porter Bundle

### ISSUE THREAD

**Issue by ujala-singh** [getporter/porter#3207]
Dear Porter Team,

Greetings!

We are writing to bring to your attention some security concerns we’ve identified in your project. We have conducted a source code perspective security analysis (SCA) and a vulnerability library association analysis on our Porter bundle using the Trivy tool. The analysis revealed that certain components with known vulnerabilities are still being used within the project.

We have documented the details of these vulnerabilities in the JSON file attached below. We kindly request you to review these findings and confirm whether these vulnerabilities are present in your current setup. Addressing these issues will significantly improve the security of the bundle.

We look forward to your response and are happy to discuss any details further if needed.
[porter-report.json](https://github.com/user-attachments/files/16625384/porter-report.json)
					
PDF with links: 
[Vulnerability Summary.pdf](https://github.com/user-attachments/files/16625445/Vulnerability.Summary.pdf)

Summary:
cnab/app/mixins/exec/exec (gobinary)

Total: 7 (UNKNOWN: 0, LOW: 1, MEDIUM: 2, HIGH: 2, CRITICAL: 2)

cnab/app/mixins/exec/runtimes/exec-runtime (gobinary)

Total: 7 (UNKNOWN: 0, LOW: 1, MEDIUM: 2, HIGH: 2, CRITICAL: 2)

cnab/app/runtimes/porter-runtime (gobinary)

Total: 7 (UNKNOWN: 0, LOW: 1, MEDIUM: 2, HIGH: 2, CRITICAL: 2)

**Comment by kichristensen** [comment]
Hi @ujala-singh,

Thank you bringing this up. For future requests related to security vulnerabilities, could you please take a look at our [security policy and reporting here](https://github.com/getporter/porter/blob/main/SECURITY.md)?

What version of Porter is these issues related to?

**Comment by ujala-singh** [comment]
Hi @kichristensen, Sure for future requests I will use [security policy and reporting here](https://github.com/getporter/porter/blob/main/SECURITY.md). 

Currently I am using latest version: porter v1.1.0 (b50c1899)
<img width="1127" alt="Screenshot 2024-08-16 at 11 13 42 AM" src="https://github.com/user-attachments/assets/f0b80639-03a9-4336-9a1e-b7e85885dc2d">

**Comment by kichristensen** [comment]
@ujala-singh I have taken a look at the reported findings and I have some follow up questions, as there is a few things that doesn't look correct.
Could you please convert to issue to a security vulnerability report as described in the document, and then we can continue the discussion there?
A lot of the findings is already addressed and will part of the next release.
For now I will close this issue.
