### ISSUE TITLE
Porter Bundle Cache

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#322]
Duffle calls this a local store but I plan on treating this a bit differently and encouraging users to think of it like a cache (to be ignored for the most part unless things go sideways or they want to micromanage stuff).

## Purpose
Cache of bundles that you have retrieved from registries as a side effect when you executed commands such as `porter install`.

### List
List all of the cached bundles
```
porter bundle cache list
```

### Show
Show the metadata for a cached bundle, in the specified output.
```
porter bundle cache show TAG [--output json|pretty|yaml]
```

### Clear
Removes all bundles from the cache.
```
porter bundle cache clear
```

### Add
Pulls a bundle by its tag from the registry, thick or thin, and unpacks it into the cache. 

```
porter bundle cache add [--tag]
```

NOTE: I am not using the term pull because it doesn't have a symmetrical verb for removing it from the cache, and you don't push from the cache either. I don't want to set up expectations that this command works like `docker pull`.

### Remove
Removes a single bundle from the cache by its tag.

```
porter bundle cache remove TAG
```

## Updated Commands
 
**This has been implemented**

### Install
Install a bundle using a definition from a registry.

```
porter install --tag TAG
```

### Upgrade
Upgrade a bundle using a definition from a registry.

```
porter upgrade --tag TAG
```

### Uninstall
Uninstall a bundle using a definition from a registry.

```
porter uninstall --tag TAG
```

### Create

Create a new bundle from an existing one, checking first that the current directory doesn't already have a bundle in it.

```
porter create --copy TAG
```

This seems useful? We need to work more on what this command should do when the source bundle isn't a porter bundle. Like just pop out the bundle.json?

---
# Deep Thoughts
* Should we always be identifying a bundle by tag? Is it ever appropriate to just operate by the bundle name (as defined in the bundle.json)?
* Duffle has more commands and flags to let you interact with the local store in more ways that outlined here. For now I want to start with just these. Mostly because these make the purpose clear: it's a cache that you don't directly use or interact with. The main mechanism for working with porter when iterating on a bundle is through the file system (i.e. in the directory of a porter bundle). The remaining time, you will use `--tag` and the cache is transparently used.

**Comment by nano2007** [comment]
Somewhat unrelated, but since this mentions thick bundles: is there a way in porter to create a "thick" bundle (we are looking specifically for helm/k8s/docker)?

**Comment by carolynvs** [comment]
@nano2007 I'm sorry I missed your question! We have a new issue open to create thick bundles. #544. It's part of a larger [milestone](https://github.com/deislabs/porter/milestone/13) to fully support them.

**Comment by carolynvs** [comment]
Closing since while this would be interesting to have, isn't necessary. If we want to add it later, that's fine we can reopen.
