### ISSUE TITLE
Credentials UX Improvements

### ISSUE THREAD

**Issue by jeremyrickard** [getporter/porter#325]
There is a WIP effort to add the ability to generate, list and otherwise manage credentials with Porter. We should take this a step further and enhance the UX even more by enhancing the install / upgrade/ delete commands to allow the Porter user to select from an existing credential if one is not specified, something along the lines of:

```
$ porter install
? Choose a set of credentials to use while installing this bundle
   jerrycar-test
> jerrycar-admin
  jerrycar-readonly
```

If no credentials exist, Porter should help you out there as well

```
$ porter install
INFO: No credentials found, let's generate one! 
For more information about credentials, see https://porter.sh/credentials
? Choose a source for "kubeconfig"  [Use arrows to move, type to filter]
  specific value
> environment variable
  file path
  shell command
```

The examples above use the existing survey text from Duffle. We can start with that and iterate to improve the messaging. 

Porter should continue to allow you to specify a credential as well:

```
$ porter install -c jerrycar-admin 
```

**Comment by carolynvs** [comment]
Here were some notes from our chat yesterday:
* When we provide a list of creds, only show ones that match the shape of the creds in the bundle
* Prompt to generate creds when there aren't any existing credentials in PORTER_HOME that match the shape of the creds in the bundle
* Don't do any prompts when they do specify a credential set and allow them to specify multiple sets to build up something that meets what the bundle needs (e.g. the azure creds come from one credential set and the kubeconfig may come from another).

**Comment by vdice** [comment]
Note that it sounds like https://github.com/deislabs/porter/issues/226 will be covered by the implementation mentioned above.

**Comment by carolynvs** [comment]
We are no longer going in the direction of more interactive commands, and this isn't on our roadmap anymore. Closing
