### ISSUE TITLE
Release v1.2.0 failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [getporter/porter#3254]
https://github.com/getporter/porter/releases/tag/v1.2.0

No asset was released.

<img width="248" alt="image" src="https://github.com/user-attachments/assets/beb194f2-df0c-45ad-a45c-ebe08d813a8b">

CI failed. https://github.com/getporter/porter/commit/c2e24f1cbb52bcc963d5cb97ddafb4deac10bb05

<img width="700" alt="image" src="https://github.com/user-attachments/assets/86784b81-4d6b-4a25-95c1-23c62e93cf4c">

https://github.com/getporter/porter/actions

<img width="1316" alt="image" src="https://github.com/user-attachments/assets/3ec34f10-98db-45e2-bcda-a12506ba7c30">

https://github.com/getporter/porter/actions/runs/11846336649
https://github.com/getporter/porter/actions/runs/11846336678
https://github.com/getporter/porter/actions/runs/11846336739

**Comment by kichristensen** [comment]
It seems to be because the linting tool didn't support Go v1.23 in the version we used. getporter/magefiles#44 updates the version of golangci-lint, which when updated in this repo, should fix the failing actions

**Comment by kichristensen** [comment]
While solving the pipelines I have changed the latest release back to v1.1.1

**Comment by kichristensen** [comment]
It has been fixed now, and the latest release have been changed to 1.2.0 again
