### ISSUE TITLE
Attempting to install v.1.2.1 from the "Install Porter" document fails

### ISSUE THREAD

**Issue by dgannon991** [getporter/porter#3299]
## Describe the bug
The install steps in the website's documentation fail. 

## To Reproduce
1. Go to https://porter.sh/docs/getting-started/install-porter/
2. Observe the install command is still 
```
export VERSION="v1.1.0"
curl -L https://cdn.porter.sh/$VERSION/install-linux.sh | bash
```
3. If you attempt to change this to `VERSION="v.1.2.1" then the script errors with the response `bash: line 1: Not: command not found`

## Expected behavior
Porter should be installed a version 1.2.1

## Version
N/A

**Comment by kichristensen** [comment]
@dgannon991 It works for me without problems. I can see in the description that the version number is incorrect, it is `v.1.2.1` instead of `v1.2.1`. Is that what you used or just a mistake in the bug report?

**Comment by dgannon991** [comment]
More embarrassing than that actually, looking back at my command history it was a typo in the bug report, but the initial cause was me misunderstanding bash variable expansion. 

Because I can do `VARIABLE=value ./script-that-uses-varaible.sh` I was under the impression I could change that command to a single liner of `VERSION=v1.2.1 curl -L https://cdn.porter.sh/$VERSION/install-linux.sh | bash`, but that is not valid! 

So I've learnt something, and feel very silly at the same time. 

Sorry guys!
