### ISSUE TITLE
Support other markup languages beyond yaml

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#37]
The porter configuration file (porter.yaml) could really be in any markup language, and should be up to the bundle author to select. There isn't anything stopping us from having everyone use a different language.

Let's switch to viper for reading in that file so that @radu-matei can use HCL.

**Comment by garethr** [comment]
+1 on HCL.

Having a stand-alone schema for that data would also help for generating client tools in other languages.

**Comment by carolynvs** [comment]
Closing since this isn't on the roadmap anymore due to difficulty templating with other markup languages.
