### ISSUE TITLE
Containerize CI targets

### ISSUE THREAD

**Issue by vdice** [getporter/porter#414]
Refactor Porter CI (see the Makefile at root) to update all applicable targets to run containerized by default -- but with clear notes on how to run natively/sans docker.

This represents a particular implementation stemming from https://github.com/deislabs/porter/issues/115.  Since this issue was created around Windows/WSL builds -- or, inability to do so --  a top criteria should be making sure users on these systems can properly run all targets. 

We should have some similar examples in other related repos, notably the recent PR to deislabs/duffle: https://github.com/deislabs/duffle/pull/766 courtesy @krancour

**Comment by carolynvs** [comment]
Please make sure when whoever tackles this that they don't alter the existing commands/compiler flags to compile the porter or mixin binaries.

**Comment by carolynvs** [comment]
Closing because we are making our build scripts cross-platform by moving to Mage.
