### ISSUE TITLE
[Feature] WSL2 DinD requirements

### ISSUE THREAD

**Issue by nunix** [getporter/porter#442]
Hi team,

I would like to know if it would be possible to have one of the 2 options below considered:

1. Allow docker `privileged` option with Porter install/update
1. Allow `/var/run/docker.sock` to be a credential

My use case/challenge is that for the K3d+Helm+Brigade demo, it requires to access the local `dockerd`.
It works fine on WSL1 as it binds to docker for windows and Docker in Docker just works.
However on WSL2, it can't access the local daemon.

Any thoughts are more than welcome 😄 

Thanks a lot
Nunix

**Comment by scotty-c** [comment]
@nunix This should work with the new Docker WSL2 context on Docker for Windows

**Comment by nunix** [comment]
good point, will retry as I did install it 🙌

if it works, Scott, I have a nice demo to share 🤩
