### ISSUE TITLE
How to sometimes uninstall everything, and sometimes just uninstall the app

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#465]
With dependencies, it may be desirable to uninstall just the app, but not the underlying dependencies (because they may still be in use, or you want to keep it around for backups, etc). How do we want to allow someone to do this in Porter?

One way would be a new flag that is just for uninstall:
```
porter uninstall wordpress --keep-deps
```

**Comment by brandonjbjelland** [comment]
To me, the flag you're pitching feels like the right UX. A more flexible approach would allow an executor to list all deps to exclude from uninstall while any NOT listed would be uninstalled:

```bash
porter uninstall wordpress --keep-deps dependent-anycloud-core-infra,dependent-anycloud-mysql-db # if not listed, perhaps a CDN bundle would be uninstalled
# alternatively throwing the flag multiple times
porter uninstall wordpress --keep-deps dependent-anycloud-core-infra --keep-deps dependent-anycloud-mysql-db
```

**Comment by carolynvs** [comment]
Closing. This is planned but will be tracked under a new PEP for dependency lifecycle management.
