### ISSUE TITLE
List bundles installed by duffle

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#528]
Bundles installed by duffle should be included when we list installed bundles. Our claim provider implementation should include ~/.porter/claims and ~/.duffle/claims. I think we can make this work since `Claim` is a common struct in cnab-go.

We may need to evaluate some of other other claims-based commands to make sure that they don't make assumptions about the location of the claim being in the porter home directory. It may need a wrapper to say where it came from, for example. Porter could then use that wrapper when consuming the claim so that it know where to load it from (if necessary, I haven't looked at the code lately so ignore if what's coming out of the ClaimProvider has what we need already).

Some other areas that may be impacted as well
* Listing outputs
* Showing outputs
* Any command with `--claim`

**Comment by squillace** [comment]
If we can, yes. Should it be pluggable location? docker-app, for example?

**Comment by carolynvs** [comment]
It really doesn't have anything to do with duffle anymore and more to do with supporting multiple sources of claims. But yes, it doesn't have to be specific to duffle at all, since the claim format is in the spec, it would work for claims created by docker-app too.

Now that we have plugins though, this feature most likely needs to be re-thought. 

I am in the middle of re-doing the claim plugin to be a storage plugin, instead of specific to just claims, see https://github.com/deislabs/porter/pull/804. That would have a large impact on the design on this feature.

Let's hold off on this one until the dust settles on that. I think it will be easier to reason about how this should look once it's complete.

**Comment by carolynvs** [comment]
Duffle is no longer an active project. Closing.
