### ISSUE TITLE
Thick Bundle with Dependencies

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#554]
🖐 I'm explicitly not putting this into the thick or dependencies milestones because it's cross cutting and may need both milestones to settle a bit before we decide to tackle this.

For now, when a user attempts to create thick bundle from a bundle with dependencies, they are informed that it isn't supported. We think that we can support it though once we have dependencies and thick bundles fully implemented. Let's consider what that would entail:

* When the thick bundle is built:
  * Each dependency of the bundle is pulled and built into a thick bundle.
  * The dependency section for the bundle is rewritten to reference relative paths to the thick bundle representation of its dependencies.
* When the thick bundle is moved around, it must be moved with its dependencies. For example thing-0.1.0.tgz, stuff-0.1.1.tgz and filler-0.2.0.tgz.
* When the thick bundle is published, every dependency tgz is published before the final tgz.
* Dependency resolution would be rewritten (including the spec) to support referencing a thick bundle from the dependencies section.
* Probably more...

**Comment by squillace** [comment]
I think this is a reasonably tough scenario.

**Comment by jeffersonbenson** [comment]
I think it'd be a much easier time if the dependent images were "rolled in" to the parent bundle, similar to the `charts` folder in a helm repo. Particularly in air-gapped situations (one of the main appeals of thick bundles imho) it's much nicer to have a singular bundle to install, rather than numerous files that all need to be collated together. 

In particular, I like the idea of the resulting bundle rewriting the sections to reference the dependencies, and each dependency would be published or installed prior to it's parent bundle.

**Comment by squillace** [comment]
my understanding is that you don't do that "collating together" work; the publish --archive does that work for you. you "carry" one bundle with all artifacts in it, then "expand" it back into the local registry for usage. In theory, an airgap bundle could NOT be published and be deployed out of the tarballs inside the invocation image...... @carolynvs ?

**Comment by carolynvs** [comment]
Here's my latest notes on how we must support this in Porter after we implement the advanced dependencies feature (copied from duplicate #1947):

Let's say that we have a bundle that depends upon another bundle, and its dependency section contains an exact full reference, e.g. `getporter/mysql:v1.2.3`. When the root bundle is relocated across an airgap, the referenced dependency is no longer accessible. Even if the dependency is relocated manually, how would the root bundle resolve the dependency to the new location?

When porter archives a bundle, it should archive the dependencies into the same archive file. When the archive is published, porter should publish each dependency, and then publish the root bundle with a relocation-mapping.json file that includes the mapping for each dependency.

```
bundlename-version.tgz
- layers
- manifest.json
- dependencies/
  - bundlename-version/ ...
    - layers
    - manifest.json
```

It should be an option to only archive the root bundle or archive all dependencies (not sure which should be the default). This will allow an administrator to do a simplified transfer of a bundle and all its dependencies, or when transferring lots of bundles, do each one separately to avoid redundantly large bundles.

We could potentially support archiving all dependencies into separate archives, and if we encounter an archive with the same desired name, do not overwrite it. That way the admin could call archive on each bundle they care about and would ultimately get a directory filled with all unique bundles to move to the airgapped environment.

```
wordpress-v1.2.3.tgz
mysql-v5.7.14.tgz
nginx-v0.23.2.tgz
```

**Comment by carolynvs** [comment]
Closing since this is superseded by [PEP005](https://github.com/getporter/proposals/blob/main/pep/003-dependency-namespaces-and-labels.md). I'll add a section to the specification with details on how we are changing the archive command, and how we will track dependencies after they have been relocated. We will probably need something similar to the image remapping file but for deps. Or reuse it (which is easier) and change the format.
