### ISSUE TITLE
kubernetes mixin needs a wait flag

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#555]
Since it may take a while for the a kubernetes apply command to actually takes affect, the mixin needs a wait flag.

* We can use the [kubectl wait](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait) to wait until a condition, such as a deployment or service is ready before collecting outputs
* Anytime we have an output, we need to wait until that output isn't empty if we don't have a wait condition to rely upon. This may need fine tuning, we don't want to end up waiting forever on a legitimately blank output.

We need to document how to use this flag properly so that people understand what they are waiting on, what the flag affects, and how waffles work.

**Comment by squillace** [comment]
Or Service IP? What kinds of things can "wait"?

**Comment by carolynvs** [comment]
Closing, implemented and k8s is in another repo now
