### ISSUE TITLE
Step outputs should default to creating bundle level outputs

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#556]
People have reported confusion when they create a step level output and then can't find the output anywhere after the bundle is run. It would help meet their expectations if step level outputs were automatically promoted to bundle level outputs.

* Add type to step level output (along with description).
* `apply_to` can be inferred from the location of the step.
* We need a way for the author to prevent the output from being promoted to the bundle level. A boolean flag that is defaulted to true, that they can flip to false. Maybe `promote: false` or `export-output: false`?

**Comment by ffoysal** [comment]
how to take output from one mixin and input to another mixin.
after outputing from mixin1, and refer it to mixin2 like this `{{bundle.outputs.hello}}`. In mixin2 code , the printed value is like `******`.
Looks like some type of masking happening somewhere, but could not figure out where?

**Comment by vdice** [comment]
@ffoysal masking is done if an output has `sensitive: true` associated with it in the porter manifest.  Is the output you need passed on to another mixin marked as `sensitive` in this way?

**Comment by squillace** [comment]
I don't really like step output automatically promoted, as it leads to the oppose problem; dumping out things that ought not to have been dumped out. However, I'm kinda interested in having step outputs right-click promoted in VS code.....

**Comment by carolynvs** [comment]
I'm going with Ralph here and am closing.
