### ISSUE TITLE
Verify dependencies are accessible on build

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#578]
When you build a bundle with dependencies (or perhaps publish), we should verify that its dependencies are accessible at the locations referenced in the dependencies section. So for example, if the bundle references `deislabs/mysql:5.7` then we should check that is pushed and warn/error about that missing dependency.

If the dependency doesn't use an exact version, we should verify that a version can be resolved and that the resolved version is accessible.

**Comment by carolynvs** [comment]
@lrskyum Can you tell me more about a "semantic of porter.yaml"? I would love to know what that is and understand if there is a gap in Porter today.

**Comment by lrskyum** [comment]
I meant to say "semantic test of porter", sorry. Anyway, it has to do with our use of the helm3 mixin mostly, and whatever images are referenced in our charts also has to be referenced in a thick bundle. So we have identified these upfront:
Check that bundle definition in porter.yaml is consistent.

- an image is included twice, possibly using different image names (not tags)
- an image is added, updated, or deleted from a chart, but not from the bundle
- an image is added to the bundle, but not referenced during installation/upgrade
- an image is not defined, but installed by the bundle (through helm3).

**Comment by carolynvs** [comment]
Thanks for sharing these are great checks! @MChorfa @vdice What do you think about incorporating checks like these into helm3's linter? I think these are good things for everyone to check?

**Comment by carolynvs** [comment]
Closing since this is addressed in PEP 003. We are going to pull the bundle definition for reach bundle during build to verify the bundle interface.
