### ISSUE TITLE
Add command to validate a bundle against the CNAB spec

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#649]
Right now this is how we validate that bundles created by porter "validate" against the CNAB spec:

1. Build Porter
2. Install ajv using npm 😱 
3. Download cnab spec and the CNAB spec's canonical json schema.
4. Build the _full_ bundle, including the invocation image which we don't need, using porter. All we do need from this step is the bundle.json.
3. Run magic ajv command that references these files against the bundle.json

I'm wondering if other people, not just us porter devs, would be interested in a command in porter that does this in a much more streamlined fashion?

1. Uses a specific version of the cnab spec that they can name, e.g. 1.0, 1.1, 2.0
2. Doesn't require ajv, or downloading external specs and associated files themselves
3. Doesn't require building the invocation image, which is 100x slower than just making the bundle.json

I'm being selfish because if this _is_ useful externally, then we may want to build it and then use it to validate our example bundles. It would save us 10+ minutes off of every CI run. It may be worth doing just for that, and maybe just having it as a useful thing that only nerds use, or just in a special dev build. 🤷

**Comment by vdice** [comment]
Great idea!  I think this'd be something other tools/implementations might also want to make use of (e.g. duffle), so it could be worth exploring if a base set of validation functionality could be added to cnab-go and wrapped/used by Porter in the form of a cli command...

**Comment by squillace** [comment]
I think this is generically useful, not merely selfish. :-)
