### ISSUE TITLE
Should porter help define env vars?

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#663]
Right now there are two ways to define environment variables:

1. Make a dockerfile template and use `ENV MYVAR=SOMEVAL`
2. Define a parameter with a default value.

1 is the recommend way, but is annoying when you didn't need the dockerfile for anything other than defining an env var. So 2 is tempting in that case, but it's a total hack because the parameter wasn't necessary and exposes you to having your env var messed with.

Do you think people would find it helpful to be able to define env vars quickly directly inside porter? Then when we build the dockerfile, we can inject the ENV lines for them.

```
environment-variables:
  myvar: somevalue
```

**Comment by squillace** [comment]
I'm trying to imagine what you get with an ENV that isn't provided by a default value for a param.

**Comment by carolynvs** [comment]
Closing since params work well for this.
