### ISSUE TITLE
Provide a way to create credential sets without terminal interaction

### ISSUE THREAD

**Issue by itowlson** [getporter/porter#689]
`porter credentials generate` provides an interactive experience for creating credential sets at the CLI.  However this is not suitable for when a GUI or script needs to create a credential set.  It would be useful to provide a way to generate an empty credential set without user interaction (cf. Duffle's `--no-prompt` option).

A GUI could then have a command to create a stub credential set and immediately open the text file for editing.  (Note the latter assumes that it's okay to take a dependency on the location and naming of credential sets... otherwise we would need another command for that.)

**Comment by jeremyrickard** [comment]
I think we can add the flag pretty easily. Most of the logic came across, we just didn't surface it. I'll look into this.

**Comment by carolynvs** [comment]
We now have `porter credentials create` which generates a commented file that you can then edit.
