### ISSUE TITLE
How to publish with multiple tags?

### ISSUE THREAD

**Issue by MikeLarah** [getporter/porter#720]
The porter manifest seems to support only a single tag for the invocation image and bundle. What is the correct way to publish a bundle with multiple tags (e.g. `latest` and `1.0.0`)? Do we have to build and publish the bundle twice with separate tags?

Related: should the version of the bundle flow into the image tags?

**Comment by vdice** [comment]
@carolynvs and I are grooming the backlog in anticipation of proposing functionality improvements in this area.  For this issue in particular, there have been improvements that I think may address the questions here.

Today, the way to publish a bundle with multiple tags is to invoke `porter publish --tag mybundle:<tag>` for as many tags of the bundle needed.  It isn't necessary to re-build prior to each publish.  Porter will take the initial build and publish off of this.

The version of the bundle will indeed flow into the published invocation images.  For example, if `porter publish --tag myregistry/mybundle:latest` is issued, the resulting image will be `myregistry/mybundle-installer:latest`.

As for next improvements, we are thinking of including in the proposal something like the following:
1. `--tag` on `porter publish` will be reserved exclusively for the bundle/image Docker tag (`latest`, `v1.0.0`, etc.)
2. `--repository` on `porter publish` will be in essence what `--tag` is today: the entire bundle reference intended to be published, e.g. `myregistry/mybundle:latest`.

How does that sound moving forward?

**Comment by MikeLarah** [comment]
This sounds like a perfectly reasonable solution to me. The details in the proposal look good, and enable us to put in place the CI/CD processes we were looking to implement.

**Comment by vdice** [comment]
With https://github.com/getporter/porter/issues/1151 now implemented, we believe the enhancements mentioned in this issue have been addressed.

To answer the original questions directly:

> What is the correct way to publish a bundle with multiple tags (e.g. latest and 1.0.0)?

One can run `porter publish --tag latest` and `porter publish --tag 1.0.0` for a given bundle

> Do we have to build and publish the bundle twice with separate tags?

No, the bundle can be built once via `porter build` and then published any number of times with differing tag/registry/reference values afterwards, without needing to rebuild the bundle.
