### ISSUE TITLE
Make porter more CI/CD friendly

### ISSUE THREAD

**Issue by MikeLarah** [getporter/porter#721]
We are currently trying to integrate Porter into a CI/CD process (in GitHub Actions) and currently 
facing a number of integration pain points.

Some of these may be alleviated by allowing the following:
a) Pass in variables to manifest (as suggested in #319)
b) Rename `tag` to `bundle`  - the current `tag` property seems to represent the bundle repository and tag (similar to `invocationImage`), so the naming seems misleading.
c) Separate out the tags that are applied to `invocationImage` and `bundle` from the `invocationImage` and `bundle` definitions themselves

For example, the manifest could look something like:

```
name: sql-server-always-on
version: {{ version }}
description: "SQL Server Always On for AKS"
dockerfile: cnab/app/Dockerfile.base
invocationImage: myregistry.io/porter/sql-server-always-on
bundle: myregistry.io/porter/sql-server-always-on/bundle
tags: {{ tags }}
```

Then from a CI process, the version could be set dynamically (e.g. using a semantic versioning plugin like [GitVersion](https://gitversion.readthedocs.io/en/latest/)), and the tags could set based on the version and branch. 

For instance, scenario 1 may be CI on feature branch / PR, where
```
version = '0.1.0-feature1.1'
tags = [ '0.1.0-feature1.1' ]
```
and would produce the following:
```
myregistry.io/porter/sql-server-always-on:0.1.0-feature1.1
myregistry.io/porter/sql-server-always-on/bundle:0.1.0-feature1.1
```

Scenario 2 may be CI on master branch after merging, where
```
version = '0.1.0'
tags = [ '0.1.0', 'latest']
```
and would produce the following:
```
myregistry.io/porter/sql-server-always-on:0.1.0
myregistry.io/porter/sql-server-always-on:latest
myregistry.io/porter/sql-server-always-on/bundle:0.1.0
myregistry.io/porter/sql-server-always-on/bundle:latest
```

We've noticed that by default when using `porter publish` if the tags are excluded from `invocationImage` and `tag` (e.g. `myregistry.io/porter/sql-server-always-on` and `myregistry.io/porter/sql-server-always-on/bundle`), then the invocation image automatically has the `latest` tag applied, but the bundle is pushed without any tag.

(Coming back to point `b)`, this is harder to describe than it should be due the naming of the `tag` property)

**Comment by sdeoras** [comment]
We are exploring this path as well. I am having difficulty understanding how to automate `param` and `creds` generation. Is it possible to generate params and creds without interactive mode? Thanks.

**Comment by vdice** [comment]
Hi @sdeoras , currently the porter CLI only supports interactive generation of creds and params, though we'd like to change this (see https://github.com/getporter/porter/issues/1080).  That being said, if one creates a JSON file from scractch following the pattern of an existing cred or param set and then supplies this when running an action on a bundle, it should work.  (Not ideal, of course!)

**Comment by sdeoras** [comment]
Thank you @vdice . I'll work with JSON files in the mean time.

**Comment by vdice** [comment]
Thanks again for the original issue here.  It motivated us to revisit various aspects of Porter, its manifest and its publishing logic to better support CI/CD scenarios.  We've just completed implementation in the proposal tracking improvements to these areas: https://github.com/getporter/porter/issues/1151

Please take a look at the overview in that issue when convenient.  Hopefully the updated functionality will support the use cases described above.  If not, or if there remain other areas we should take a look at, please create new issue(s) to track.
