### ISSUE TITLE
Mixin feed updates should use a blob lease

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#750]
When we publish mixins, we should use blob leases, so that we don't accidentally clobber the atom.xml file.

**Comment by carolynvs** [comment]
I have been seeing this more often in failed builds and I have a suspicion it's due to this issue not being done.

bad status returned when downloading https://cdn.porter.sh/plugins/atom.xml (503)

**Comment by MikkelHegn** [comment]
Seeing this more and more... It will break codespace creation if you rely on porter in your dev container :-(

**Comment by carolynvs** [comment]
@MikkelHegn The 503 errors from our azure blob storage has been brutal. I just tweaked the CDN in front of it and if that doesn't work I am going to try to get Azure support to help us out. 

I am really sorry that the downloads have been so flakey...

**Comment by MikkelHegn** [comment]
Thx - I'll let you know if I see then again...

**Comment by MikkelHegn** [comment]
😭 - from right now...
![image](https://user-images.githubusercontent.com/12242001/107043787-c10bed00-67c3-11eb-9393-f615b33fc888.png)

**Comment by carolynvs** [comment]
Thanks for confirming that nothing works. 😭 

@squillace is helping me figure something out. I may move us to the Verizon CDN and see if that helps.

**Comment by squillace** [comment]
Hey all, I've reached the CDN team and now that it's Monday I'll have an answer here for the instability. (@carolynvs @MikkelHegn)

**Comment by MikkelHegn** [comment]
@bec-lyons - who also ran into this earlier today
