### ISSUE TITLE
Proposal: Instance Storage config per Bundle

### ISSUE THREAD

**Issue by vdice** [getporter/porter#763]
A framework for remote claim storage was added in https://github.com/deislabs/porter/pull/699 (:tada:!)

Currently, configuration of instance storage is done Porter-wide via Porter's [Configuration file](https://porter.sh/configuration/).

However, I'm wondering if it would be useful to offer the ability to set (or override) this particular instance storage config _per bundle_.

Say, if I use the same porter client to manage bundles using the local/default filesystem instance storage plugin but then wish to use the same client to manage bundles using remote instance storage plugins (perhaps via https://github.com/deislabs/porter-azure-plugins).  In such a scenario, it would be preferred not to have to toggle the Porter-wide setting when switching contexts.  Perhaps a bundle-specific override could take precedence over any Porter-wide setting?

**Comment by squillace** [comment]
Hmmmm. let's game the user story. Should a dev have the ability to flip storage per anything? Yes. Should a tool, or a team player? Hmmmmmmmmmmmmmmm. Why would a bundle be involved at all? It's the mode of the user, not the bundle-scoping, that must change periodically.

Of course, this leaves an easy UX problem: I "forgot" I was in Azure cloud mode, now I upgraded a claim but the claim is in the cloud and I was supposed to be doing that in AWS S3 mode. So..... uh.... how do we do this and prevent easy "forgotten context" problems?

**Comment by carolynvs** [comment]
Closing now that we have a more mature storage system.
