### ISSUE TITLE
Kubernetes Mixin: Auto-install compatible cli version

### ISSUE THREAD

**Issue by vdice** [getporter/porter#766]
For the Kubernetes mixin: Add logic to auto-install a `kubectl` cli version appropriate for the server version detected at runtime, overriding the built-in `kubectl` cli version.

Extra context: https://github.com/deislabs/porter/pull/755#issuecomment-545643054

**Comment by carolynvs** [comment]
This issue was migrated to the new k8s mixin repo: https://github.com/getporter/kubernetes-mixin/issues/18
