### ISSUE TITLE
Kubernetes Mixin: Support version declaration for build-time install

### ISSUE THREAD

**Issue by vdice** [getporter/porter#767]
For the Kubernetes mixin: Support Kubernetes version declaration and use this value, when provided, to download the corresponding `kubectl` cli binary at build-time.  For example, the `kubernetes` mixin declaration in a Porter manifest could look like:

```
mixins:
- kubernetes:
    version: v1.14.1
```

We'd then update the installation steps/lines added to the generated invocation image Dockerfile to download the `v1.14.1` kubectl binary.

Further context at https://github.com/deislabs/porter/pull/755#issuecomment-545617318

**Comment by MChorfa** [comment]
@vdice this issue is resolved
