### ISSUE TITLE
Make additional bundle metadata available to template

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#78]
Right now the porter manifest lets a bundle author template out values for certain things, `bundle.parameters.NAME`, `bundle.credentials.NAME`, etc.

But metadata about the bundle can't be substituted in yet. I would like to be able to do something like this in my porter manifest:

```
bundle.name
```

We have a view pieces of information in our bundle metadata that would be nice to make available:

* Name
* Description
* Version
* Image

It may help you when you implement this to move those fields into a new embedded struct on the Manifest. If you need to do that, feel free.

This is the function that would need to be modified:
https://github.com/deislabs/porter/blob/9eed13889d855c5665c42b9b4b2ac8153a8feae4/pkg/config/manifest.go#L647

That would let someone use `bundle.*`

There is another function 

https://github.com/deislabs/porter/blob/9eed13889d855c5665c42b9b4b2ac8153a8feae4/pkg/config/manifest.go#L83

That lets someone use `bundle.dependencies.NAME.*`, for example to access metadata about one of their dependencies, `bundle.dependencies.mysql.version`.

It would be nice (though not required), if both were updated.

See https://porter.sh/authoring-bundles/ for more context on the porter manifest.

**Comment by nunix** [comment]
oh nice, for my "next crazy evolution" of WSL+CNAB I would need something like:
bundle.dependencies.myOtherBundle.invocationName

as a readonly field of course, as the bundle would be already installed

Looking forward to this one 😈

**Comment by dev-drprasad** [comment]
@carolynvs is this feature still required ? If yes, i would like to pick it up

**Comment by carolynvs** [comment]
@dev-drprasad It is still needed. The code where these values are resolved has moved. The code where these values are set is now located here:

https://github.com/deislabs/porter/blob/790e7f97542ef2ae85b04594a145692a630bff26/pkg/config/runtime-manifest.go#L164

I realize that the template paths that I used in the issue were incorrect as well. I said `bundle.metadata.name`, but it is `bundle.name`. I'll update the original issue to correct that.

**Comment by dev-drprasad** [comment]
@carolynvs is substitution/templating possible only in **actions** ?

**Comment by carolynvs** [comment]
At the moment, yes. It's out of scope for this issue to change that. We do want to change this so that we can use templating anywhere.

**Comment by dev-drprasad** [comment]
@carolynvs I found that `Bundle` has multiple `InvocationImages` and there is no name field in `InvocationImage` struct. Then how authors can do something like `bundle.dependencies.mysql.invocationImage` ?

**Comment by carolynvs** [comment]
I recommend not exposing some fields for dependencies. InvocationImage is one of them. 

A bundle can have multiple invocation images and it can be selected by the user when they run the bundle. We are still working on the dependencies spec, and invocationImage is one of the values that won't be something that can be determined after the bundle was executed. There may not be much value anyway in knowing the invocation image executed by a dependency (that remains to be seen as we collect use cases and feedback). So for now let's just leave it off.

Thanks for checking! 👍
