### ISSUE TITLE
Update JSON Schema to reflect reality

### ISSUE THREAD

**Issue by jeremyrickard** [getporter/porter#787]
The JSON Schema doesn't currently accurately model the manifest. This means that tools that are driven from the schema can't correctly render or suggest things based on the schema. We should update it to properly reflect the manifest.

**Comment by squillace** [comment]
As a user, I'd call this one of the highest UX issues to address. _but who wants to touch json schema?_

**Comment by MikeLarah** [comment]
You get red squiggles even with a fresh `porter create` in VS Code with the Porter extension enabled (because the JSON schema specifies that `invocationImage` is required, when it is not)

![image](https://user-images.githubusercontent.com/2104606/78671458-3c1c2280-78d7-11ea-8485-a8aef4920ed6.png)

**Comment by carolynvs** [comment]
I'll add this to our PR checklist so that PRs have to update the schema in the same PR as well. We will get the schema updated ASAP to match and then keep it in sync going forward.

**Comment by carolynvs** [comment]
Closing since I think any remaining schema gaps are in individual mixins.
