### ISSUE TITLE
Official OCI registry for porter

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#807]
We should pick a name + location for porter's official location for it's OCI registry. Right now we publish unimportant things, like our testdata bundles during our CI run to make sure they work. It would be nice to officially publish and document a few things:

* porter image, for running porter in a container
* how to make a porter image yourself if you want to customize it
* porter hello world bundle to try out
* other porter example images, like cowsay 🐮 

We should select a main OCI provider and also camp on the name on the others, including hub, to protect the name and avoid the well known problem of default registry fallback.

I vote for quay as our main, since it's free, hasn't been bought recently, and has fine grained security.

**Comment by squillace** [comment]
As ACR can be public, and is also free, let's make sure our argument for quay is complemented by the features that ACR does not give us, or does not give us yet. :-)

**Comment by carolynvs** [comment]
Our official registry is ghcr.io/getporter
