### ISSUE TITLE
variable support in porter.yaml

### ISSUE THREAD

**Issue by ffoysal** [getporter/porter#814]
Is there a way to do variable references in `porter.yaml` file. for example in the `porter.yaml`
```
name: SampleApp
version: 0.1.0
description: "Sample app cnab bundle"
invocationImage: ffoysal/hello-invocation:0.1.0
tag: ffoysal/hello-bundle:0.1.0
```
in this code snippet if we could declare `0.1.0` in variable and reference that in three places would be good for us.

**Comment by carolynvs** [comment]
We don't have variable support yet. That would come in #1002. However the invocationImage field is optional now (and will be deprecated in the next release) and the tag no longer requires you to put the version in it, so the manifest can now look like this

```
name: SampleApp
version: 0.1.0
description: "Sample app cnab bundle"
tag: ffoysal/hello-bundle
```

Vaughn is working on defaulting the tag as well in a new enhancement proposal too. But I hope this helps for your current bundles!

**Comment by carolynvs** [comment]
Closing now that we have workarounds for most of this, such as `porter build --version --name`, `porter publish --registry --tag --reference`, and the ability to set custom metadata and reference it with templating (#1899).

If there is additional scenarios we need to support, let's open a new issue.
