### ISSUE TITLE
Improve error message when porter is used with an unsupported registry

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#822]
Since we are going to have registries in play that don't fully support the OCI registry spec for a while, let's have Porter gracefully degrade the `publish` command when it detects that it's working with one instead of hard erroring out.

When it attempts to publish the bundle to the registry, and porter detects that the error was caused by a non-OCI compliant registry (as opposed to say an authentication error), Porter should print a message linking to our docs on how to work with non-OCI compliant registries and then return with a 0 exit code. Essentially, only push the images and not the bundle.

**Comment by squillace** [comment]
Or have no pushing be the default, with a config that says, push invocation but not bundle? But, yes yes yes.... :-)

**Comment by carolynvs** [comment]
Closing since a bunch of registries have proper OCI support now
