### ISSUE TITLE
Provide option for outputs output format

### ISSUE THREAD

**Issue by bkuschel** [getporter/porter#830]
## Describe the feature request
Provide the ability to specify output formats, something like `-output` option, suggestions could be
 default, value, table, json and or yaml.

 - default: Current output
 - value: each step output per line (ordered as in yaml)
 - table: an ascii table with the other step fields like description, name, and output
 - json/yaml: table rendered as fixed json/yaml schema

It may also be desirable to provide another option to select steps (instead of all)

## To Reproduce
Create an action with an output
```
PS> porter bundle invoke --action product_version            
invoking custom action product_version on test-version...
executing product_version action from test-version (bundle instance: test-version)
Get the product version
1.2.13
execution completed successfully!
```

## Expected behavior
```
PS> porter bundle invoke --action product_version -output value
1.2.13
```

**Comment by vdice** [comment]
Thanks for the issue @bkuschel .  Although Porter has separate commands for listing and showing outputs, e.g.,

```
 $ porter instance outputs list basic-tf-example -o yaml
- name: a
  definition:
    type: string
  value: |
    a
  displayvalue: |
    a
  type: string

$ porter instance outputs show a -i basic-tf-example
a
```

only `list` supports `-o table/yaml/json`.

However, it sounds like it would be preferred to support passing the output format through in the `invoke --action` or `install/upgrade/uninstall` command (as shown above) such that any bundle outputs are printed in the supplied output format.  If the output format is not default, then is the request also to mask all other action output/logs besides the bundle outputs themselves?

**Comment by bkuschel** [comment]
Yes, basically, to allow for output from an `invoke` and providing some means  to control and format that output, similar to `list` but also a means by which to select the outputs that should be displayed in the output like `show`. 
Ideally, for an given action, in the `porter.yaml`, you could specify the default output format  and which ones to show by default for the given invocation action. 
The user could override it with similar options to `list` and `show` but in the `invoke` command.
Example:
> `porter invoke --action about`
This is an output message
>
> `porter invoke --action about -o yaml'
This is an output message
>
could be the result of something like:
```yaml
- name: about
  definition:
    type: string
  value: |
    "This is an output message"
  displayvalue: |
    "This is an output message"
  type: string
```

**Comment by carolynvs** [comment]
Closing. The recommended way to do this is with `porter install/update/invoke/uninstall` followed by `porter installation outputs show`
