### ISSUE TITLE
In 5 minutes Content

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#871]
Create an article/video (or more) walking through how to perform a common task in 5 minutes. Promote it on our resources page, twitter, etc.

**Rando Ideas**

* Write your first bundle (create, edit, build, install / iterate)
* Bundle a helm application (use the helm mixin, pinning a version, kubeconfig)
* Upgrade an application (same bundle? new bundle version?)
* Find a bundle on the internet and install it
* Bundle your application in a CI Pipeline

**Comment by jeremyrickard** [comment]
I WANT TO MAKE SOME VIDEOS

**Comment by squillace** [comment]
I'm totes in!
