### ISSUE TITLE
Improve error message when a docker image is passed to --reference

### ISSUE THREAD

**Issue by dev-drprasad** [getporter/porter#904]
## Describe the bug
For some reason `porter explain` not able to show bundle information for some bundles from https://hub.docker.com/r/getporter . I don't think its a bug. something to do with version mismatch

## To Reproduce
1. Run `porter explain --tag getporter/mysql:v0.1.1`
2. You see information
1. Run `porter explain --tag getporter/porter-hello-installer:0.1.0`
4. You See error

## Expected behavior
`porter explain --tag getporter/porter-hello-installer:0.1.0` should work. right ?

## Porter Command and Output

```console
➜ porter explain --tag getporter/porter-hello-installer:0.1.0

Error: unable to pull bundle before invoking explain command: unable to pull bundle getporter/porter-hello-installer:0.1.0: unable to pull remote bundle: invalid media type "application/vnd.docker.distribution.manifest.v2+json" for bundle manifest
```

## Version
porter v0.22.1-beta.1-14-g4401e74 (4401e74)

**Comment by carolynvs** [comment]
The problem is that `getporter/porter-hello-installer` is the invocation image, and explain requires that you pass in the tag for a bundle. Try the command again and pass in this instead `getporter/porter-hello:v0.1.0` and you will see output

```console
$ porter explain -t getporter/porter-hello:v0.1.0
Name: HELLO
Description: An example Porter configuration
Version: 0.1.0

No credentials defined

Parameters:
Name           Description                                                     Type      Default   Required   Applies To
porter-debug   Print debug information from Porter when executing the bundle   boolean   false     false      All Actions

No outputs defined

No custom actions defined
```

**Comment by carolynvs** [comment]
It would be great if porter detected the type of the image pulled, and if it's a regular docker image, it should give you a better error message like "--tag should be the tag of a bundle, but an image tag was specified".

**Comment by dev-drprasad** [comment]
I see error coming directly from dependency package: `cnab-to-oci` . I don't think porter can detect what type of image it is

**Comment by carolynvs** [comment]
cnab-to-oci is a dependency of ours that we can contribute to in the cnabio org, similar to cnab-go. So no worries, we aren't limited to just solutions that are within Porter's codebase.
