### ISSUE TITLE
Support importing an existing credential set from a file

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#946]
When someone already has a credential set, for example they were using it in duffle previously or had it committed in a repository, they need a way to get it into their porter environment. This is especially important now that it could be remote (a blob store, a database, etc).

Let's add a command to porter that accepts an existing credential set file and imports it into our credential store:

```
porter credentials import [--validate-only] FILE... 
```

* `FILE` is required
* There can be more than one `FILE` specified
* Before any files are imported, they are all validated first.  If any files are invalid, the command is halted before any imports begin.
* Each file is imported in parallel, if there is a problem with importing a file an error message is printed for that file and a non-zero exit code is returned, but the other files will be imported.
* If a file is imported for a credential set that already exists, it is overwritten without any message printed.
* When `--validate-only` is specified, the credentials are validated but nothing is imported.

See the GenerateCredentials command for ideas for how to go about implementing this command

https://github.com/deislabs/porter/blob/9110c71d4d65c5b1d2d0705b618b035efd93c672/cmd/porter/credentials.go#L42-L47

https://github.com/deislabs/porter/blob/9110c71d4d65c5b1d2d0705b618b035efd93c672/pkg/porter/credentials.go#L126-L144

It's not exactly the same, but they will both use `p.Credentials` to manage validating, and saving the credential sets which that demonstrates how to do.

This will need unit tests that exercise our stub Credentials and use the afero file system, so look at the existing credentials tests and [this bundle build test](https://github.com/deislabs/porter/blob/9110c71d4d65c5b1d2d0705b618b035efd93c672/pkg/porter/build_test.go#L15-L21) for examples of how to do that.

**Comment by dev-drprasad** [comment]
>  This is especially important now that it could be remote (a blob store, a database, etc).
I have few questions regarding this
 * Where do user specify remote options ? In `config.toml` ?
 * Do we need to implement logic inside porter to read from remote sources ? or Refactor plugin storage to read them ?

**Comment by carolynvs** [comment]
This has been implemented with the `porter credentials apply` command.
