### ISSUE TITLE
Support creating a credential set from the command line

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#947]
When scripting porter, the user may know the sources for all the credentials ahead of time and not need to go through the interactive prompt that `porter credentials generate` walks the user through. In that case what they really want help with is not having to write out all the encoding themselves to make a credential set.

This command accepts the credential name and its sources and uses it build a completed credential set:

```
porter credentials create NAME [--cred SOURCE_NAME=SOURCE_KEY:SOURCE_VALUE]...
```

*  `NAME` is the name of the credential set and is required.
* `--cred|c` is the credential source. It is optional and may be specified multiple times.
* The format for credential sources is mapped onto the credential set like so:

```json
{
    "name": "NAME",
    "created": "CREATED",
    "modified": "MODIFIED",
    "credentials": [
        {
            "name": "SOURCE_NAME",
            "source": {
                "SOURCE_KEY": "SOURCE_VALUE"
            }
        }
    ]
}
```

See the GenerateCredentials command for ideas for how to go about implementing this command

https://github.com/deislabs/porter/blob/9110c71d4d65c5b1d2d0705b618b035efd93c672/cmd/porter/credentials.go#L42-L47

https://github.com/deislabs/porter/blob/9110c71d4d65c5b1d2d0705b618b035efd93c672/pkg/porter/credentials.go#L126-L144

It's not exactly the same, but they will both use `p.Credentials` to manage saving the credential set which that demonstrates how to do.

This will need unit tests that exercise our stub Credentials and use the afero file system, so look at the existing credentials tests and [this bundle build test](https://github.com/deislabs/porter/blob/9110c71d4d65c5b1d2d0705b618b035efd93c672/pkg/porter/build_test.go#L15-L21) for examples of how to do that.

**Comment by carolynvs** [comment]
This is similar to #689 but not the same because it's not setting up a template for the user to finish. The user is expected to know what to enter, and this just saves them to making the entire properly encoded file themselves and saving it to porter's backend. Once this is implemented, it could use this code to implement itself though perhaps.

**Comment by carolynvs** [comment]
@jeremyrickard @vdice Question for y'all. I believe that any character can be encoded into the credential source name. For example, you could have a credential source name like this

```json
{
    "name": "awfulcreds",
    "created": "CREATED",
    "modified": "MODIFIED",
    "credentials": [
        {
            "name": "hell:\n%$scape-~`\"'name",
            "source": {
                "env": "hellscape"
            }
        }
    ]
}
```

Do you agree?

I'd like to say that if you have a situation like that where you have gone off the rails, to say "you need to use #946 instead". Thoughts?

**Comment by vdice** [comment]
@carolynvs I *think* so?  The CNAB Spec merely states that `The name key MUST be human-readable` for a credential.  (Of course, Porter can be more strict if it wishes...)

**Comment by carolynvs** [comment]
Haha, no it's not human readable IMO but maybe they are just saying no unicode? That feels a bit subjective. I was asking because the format for the command that I am suggesting would preclude setting credential sources that have names with a colon in them.

I would like to document that if you have a name with certain special characters, like a colon, that you should use the other command instead (where you import the file). Instead of trying to design around a very unlikely (and unsympathetic) edge case. 😀

**Comment by fernandoBRS** [comment]
Hello @carolynvs, any updates about the command line support? Thanks!

**Comment by carolynvs** [comment]
@fernandoBRS Nope! With Porter our GitHub issues is the most up-to-date source of information so whatever you see is the current state. 😀 

As for a workaround, if you are aren't using a storage plugin so your credentials are stored on the local filesystem in ~/.porter/credentials you can generate those files yourself in a script. The format is in first post of this issue or you can run through `porter credentials generate` and go look at the file to see what the resulting file looks like for a particular bundle.

**Comment by fernandoBRS** [comment]
It worked, thanks @carolynvs! 😊

**Comment by carolynvs** [comment]
Closing in favor of #1787. Now that we support porter credentials apply, we don't need a command that creates and saves a credential set. People can make a file with their credentials, assisted by the create command in #1787, and then apply it. Generating real credentials contents of the file is no longer necessary.
