### ISSUE TITLE
Random Execution of the dependencies at Runtime

### ISSUE THREAD

**Issue by MChorfa** [getporter/porter#969]
## Describe the Issue
Since the nested dependencies are not supported yet. So we decided to create multiple dependent bundles, and we want the execute bundle in a certain orders. But on each run we get a random elections at Runtime.

Here what we get:

##### Declared

MYDEP-core
MYDEP-s3
MYDEP-db
MYDEP-experiments

---

##### Executed

MYDEP-experiments
MYDEP-s3
MYDEP-core
MYDEP-db

## To Reproduce
1. Create bundle with multiple dependencies
2. install 
4. Observe the declaration and the execution plan

## Expected behavior
Get the dependent bundle to execute for now in the exact same way they were declared

## Version
porter v0.23.0-beta.1 (9c49056)

**Comment by MChorfa** [comment]
After a quick scanning of the code, this issue will require changes all the up to CNAB dependencies spec. 
By changing from map `Dependencies map[string]Dependency  `yaml:"dependencies,omitempty"`` to to a list `Dependencies []Dependency  `yaml:"dependencies,omitempty"` will require a lot code changes. The other way would be to add an extra property like `order`  within the dependency object b but I wonder if this won't impact the spec?

**Comment by MChorfa** [comment]
Hello @carolynvs, @vdice,
Potential solution: 
1. Add Prop: Dependency struct [dependencies.go] 
```go
// Dependency describes a dependency on another bundle
type Dependency struct {
	// Bundle is the location of the bundle in a registry, for example REGISTRY/NAME:TAG
	Bundle string `json:"bundle" mapstructure:"bundle"`

	// Version is a set of allowed versions
	Version *DependencyVersion `json:"version,omitempty" mapstructure:"version"`

	// Order is a way to indicate precedence within the dependencies
	Order int `json:"order,omitempty" mapstructure:"order"`
}
```
2. Add Prop: DependencyLock struct [solver.go] 
```go
type DependencyLock struct {
	Alias string
	Tag   string
	Order int
}
```
3. Sort the DependencyLocks within the ResolveDependencies func
```go
...
	q := make([]DependencyLock, 0, len(deps.Requires))
	for alias, dep := range deps.Requires {
		bundle := strings.Split(dep.Bundle, ":")[0]
		version, err := s.ResolveVersion(alias, dep)
		if err != nil {
			return nil, err
		}
		lock := DependencyLock{
			Alias: alias,
			Tag:   fmt.Sprintf("%s:%s", bundle, version),
			Order: dep.Order,
		}
		q = append(q, lock)
	}

	sort.SliceStable(q, func(i, j int) bool {
		return q[i].Order < q[j].Order
	})
```
WDYT?

**Comment by vdice** [comment]
Thank you for raising this issue @MChorfa .  I'd favor proposing a change to the [spec](https://github.com/cnabio/cnab-spec/blob/master/500-CNAB-dependencies.md) around the listint structure, from `map[string]Dependency` to `[]Dependency`, as you'd suggested above.

In doing so, Porter could then establish the precedent of executing dependencies based on the order they are declared in the manifest.  For example, if the dependencies are declared like so,

```
dependencies:
  - name: mysql
    tag: myregistry/mysql:v0.1.0
  - name: wordpress
    tag: myregistry/wordpress:v0.1.0
```
Porter would install according to the order listed.  So, the `mysql` dep would be installed, then `wordpress`, and so on, in the same order no matter the action, ensuring repeatable/predictable dependency execution.

Note how a new field was added, `name`, to the `Dependency` object.  This would be needed to maintain functionality of templating values, e.g. `{{ bundle.dependencies.mysql.output.foo }}`, etc.

Would you be interested in proposing the CNAB Spec change (listing changes to an array, an individual listing now has a `name` field, runtimes are expected to process listings in order of appearance)?  Once consensus is reached there, we can update Porter's implementation to ensure repeatable dependency execution.

**Comment by MChorfa** [comment]
Change proposal submitted: https://github.com/cnabio/cnab-spec/issues/361 🤞
