### ISSUE TITLE
Document CI/CD workflows

### ISSUE THREAD

**Issue by MChorfa** [getporter/porter#997]
First draft / a few ideas:
- Document Porter CI Flow, Docker CI Flow, Application CI Flow
- Document Porter CD Flow, Docker CD Flow, Application CD Flow
- Document how to retrieve status for a given action
- Document how to verify a bundle with dependencies
- Document how to clean up the intermediary images resulting from stages 

Please feel free to add any other points. 
Related #721

**Comment by vdice** [comment]
The listing above seems like a great start.  Perhaps more ideas will arise after reviewing an initial PR, but I'd say we can start with this. 👍

**Comment by carolynvs** [comment]
We have a start with https://getporter.org/best-practices/github-workflow/.
